apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: agentgateway-secrets
  labels:
    app.kubernetes.io/instance: agentgateway
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: projects/neuraltrust-app-prod/secrets/agentgateway/versions/latest
        path: .env
      - resourceName: projects/neuraltrust-app-prod/secrets/agentgateway-config-sync-tls-cert/versions/latest
        path: config-sync/tls.crt
      - resourceName: projects/neuraltrust-app-prod/secrets/agentgateway-config-sync-tls-key/versions/latest
        path: config-sync/tls.key
      - resourceName: projects/neuraltrust-app-prod/secrets/agentgateway-config-sync-tls-ca/versions/latest
        path: config-sync/ca.crt
