// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	gateway "github.com/NeuralTrust/TrustGate/pkg/domain/gateway"
	ids "github.com/NeuralTrust/TrustGate/pkg/domain/ids"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// CountByTenantID provides a mock function with given fields: ctx, tenantID
func (_m *Repository) CountByTenantID(ctx context.Context, tenantID string) (int, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for CountByTenantID")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, tenantID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_CountByTenantID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByTenantID'
type Repository_CountByTenantID_Call struct {
	*mock.Call
}

// CountByTenantID is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
func (_e *Repository_Expecter) CountByTenantID(ctx interface{}, tenantID interface{}) *Repository_CountByTenantID_Call {
	return &Repository_CountByTenantID_Call{Call: _e.mock.On("CountByTenantID", ctx, tenantID)}
}

func (_c *Repository_CountByTenantID_Call) Run(run func(ctx context.Context, tenantID string)) *Repository_CountByTenantID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_CountByTenantID_Call) Return(_a0 int, _a1 error) *Repository_CountByTenantID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_CountByTenantID_Call) RunAndReturn(run func(context.Context, string) (int, error)) *Repository_CountByTenantID_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Repository) Delete(ctx context.Context, id ids.ID[ids.GatewayKind]) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind]) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Repository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id ids.ID[ids.GatewayKind]
func (_e *Repository_Expecter) Delete(ctx interface{}, id interface{}) *Repository_Delete_Call {
	return &Repository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *Repository_Delete_Call) Run(run func(ctx context.Context, id ids.ID[ids.GatewayKind])) *Repository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]))
	})
	return _c
}

func (_c *Repository_Delete_Call) Return(_a0 error) *Repository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Delete_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind]) error) *Repository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByDomain provides a mock function with given fields: ctx, domain
func (_m *Repository) FindByDomain(ctx context.Context, domain string) (*gateway.Gateway, error) {
	ret := _m.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for FindByDomain")
	}

	var r0 *gateway.Gateway
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*gateway.Gateway, error)); ok {
		return rf(ctx, domain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *gateway.Gateway); ok {
		r0 = rf(ctx, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.Gateway)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByDomain'
type Repository_FindByDomain_Call struct {
	*mock.Call
}

// FindByDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *Repository_Expecter) FindByDomain(ctx interface{}, domain interface{}) *Repository_FindByDomain_Call {
	return &Repository_FindByDomain_Call{Call: _e.mock.On("FindByDomain", ctx, domain)}
}

func (_c *Repository_FindByDomain_Call) Run(run func(ctx context.Context, domain string)) *Repository_FindByDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_FindByDomain_Call) Return(_a0 *gateway.Gateway, _a1 error) *Repository_FindByDomain_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByDomain_Call) RunAndReturn(run func(context.Context, string) (*gateway.Gateway, error)) *Repository_FindByDomain_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *Repository) FindByID(ctx context.Context, id ids.ID[ids.GatewayKind]) (*gateway.Gateway, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *gateway.Gateway
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind]) (*gateway.Gateway, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind]) *gateway.Gateway); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.Gateway)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.GatewayKind]) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type Repository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id ids.ID[ids.GatewayKind]
func (_e *Repository_Expecter) FindByID(ctx interface{}, id interface{}) *Repository_FindByID_Call {
	return &Repository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *Repository_FindByID_Call) Run(run func(ctx context.Context, id ids.ID[ids.GatewayKind])) *Repository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]))
	})
	return _c
}

func (_c *Repository_FindByID_Call) Return(_a0 *gateway.Gateway, _a1 error) *Repository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByID_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind]) (*gateway.Gateway, error)) *Repository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySlug provides a mock function with given fields: ctx, slug
func (_m *Repository) FindBySlug(ctx context.Context, slug string) (*gateway.Gateway, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for FindBySlug")
	}

	var r0 *gateway.Gateway
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*gateway.Gateway, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *gateway.Gateway); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.Gateway)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySlug'
type Repository_FindBySlug_Call struct {
	*mock.Call
}

// FindBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *Repository_Expecter) FindBySlug(ctx interface{}, slug interface{}) *Repository_FindBySlug_Call {
	return &Repository_FindBySlug_Call{Call: _e.mock.On("FindBySlug", ctx, slug)}
}

func (_c *Repository_FindBySlug_Call) Run(run func(ctx context.Context, slug string)) *Repository_FindBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_FindBySlug_Call) Return(_a0 *gateway.Gateway, _a1 error) *Repository_FindBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindBySlug_Call) RunAndReturn(run func(context.Context, string) (*gateway.Gateway, error)) *Repository_FindBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *Repository) List(ctx context.Context, filter gateway.ListFilter) ([]*gateway.Gateway, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*gateway.Gateway
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, gateway.ListFilter) ([]*gateway.Gateway, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, gateway.ListFilter) []*gateway.Gateway); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gateway.Gateway)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, gateway.ListFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, gateway.ListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Repository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter gateway.ListFilter
func (_e *Repository_Expecter) List(ctx interface{}, filter interface{}) *Repository_List_Call {
	return &Repository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *Repository_List_Call) Run(run func(ctx context.Context, filter gateway.ListFilter)) *Repository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(gateway.ListFilter))
	})
	return _c
}

func (_c *Repository_List_Call) Return(items []*gateway.Gateway, total int, err error) *Repository_List_Call {
	_c.Call.Return(items, total, err)
	return _c
}

func (_c *Repository_List_Call) RunAndReturn(run func(context.Context, gateway.ListFilter) ([]*gateway.Gateway, int, error)) *Repository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, g
func (_m *Repository) Save(ctx context.Context, g *gateway.Gateway) error {
	ret := _m.Called(ctx, g)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Gateway) error); ok {
		r0 = rf(ctx, g)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Repository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - g *gateway.Gateway
func (_e *Repository_Expecter) Save(ctx interface{}, g interface{}) *Repository_Save_Call {
	return &Repository_Save_Call{Call: _e.mock.On("Save", ctx, g)}
}

func (_c *Repository_Save_Call) Run(run func(ctx context.Context, g *gateway.Gateway)) *Repository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.Gateway))
	})
	return _c
}

func (_c *Repository_Save_Call) Return(_a0 error) *Repository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Save_Call) RunAndReturn(run func(context.Context, *gateway.Gateway) error) *Repository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveWithTenantCap provides a mock function with given fields: ctx, g, tenantID, maxInstances
func (_m *Repository) SaveWithTenantCap(ctx context.Context, g *gateway.Gateway, tenantID string, maxInstances int) error {
	ret := _m.Called(ctx, g, tenantID, maxInstances)

	if len(ret) == 0 {
		panic("no return value specified for SaveWithTenantCap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Gateway, string, int) error); ok {
		r0 = rf(ctx, g, tenantID, maxInstances)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_SaveWithTenantCap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveWithTenantCap'
type Repository_SaveWithTenantCap_Call struct {
	*mock.Call
}

// SaveWithTenantCap is a helper method to define mock.On call
//   - ctx context.Context
//   - g *gateway.Gateway
//   - tenantID string
//   - maxInstances int
func (_e *Repository_Expecter) SaveWithTenantCap(ctx interface{}, g interface{}, tenantID interface{}, maxInstances interface{}) *Repository_SaveWithTenantCap_Call {
	return &Repository_SaveWithTenantCap_Call{Call: _e.mock.On("SaveWithTenantCap", ctx, g, tenantID, maxInstances)}
}

func (_c *Repository_SaveWithTenantCap_Call) Run(run func(ctx context.Context, g *gateway.Gateway, tenantID string, maxInstances int)) *Repository_SaveWithTenantCap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.Gateway), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *Repository_SaveWithTenantCap_Call) Return(_a0 error) *Repository_SaveWithTenantCap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_SaveWithTenantCap_Call) RunAndReturn(run func(context.Context, *gateway.Gateway, string, int) error) *Repository_SaveWithTenantCap_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, g
func (_m *Repository) Update(ctx context.Context, g *gateway.Gateway) error {
	ret := _m.Called(ctx, g)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Gateway) error); ok {
		r0 = rf(ctx, g)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - g *gateway.Gateway
func (_e *Repository_Expecter) Update(ctx interface{}, g interface{}) *Repository_Update_Call {
	return &Repository_Update_Call{Call: _e.mock.On("Update", ctx, g)}
}

func (_c *Repository_Update_Call) Run(run func(ctx context.Context, g *gateway.Gateway)) *Repository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.Gateway))
	})
	return _c
}

func (_c *Repository_Update_Call) Return(_a0 error) *Repository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Update_Call) RunAndReturn(run func(context.Context, *gateway.Gateway) error) *Repository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithTenantCap provides a mock function with given fields: ctx, g, tenantID, maxInstances
func (_m *Repository) UpdateWithTenantCap(ctx context.Context, g *gateway.Gateway, tenantID string, maxInstances int) error {
	ret := _m.Called(ctx, g, tenantID, maxInstances)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithTenantCap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Gateway, string, int) error); ok {
		r0 = rf(ctx, g, tenantID, maxInstances)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateWithTenantCap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithTenantCap'
type Repository_UpdateWithTenantCap_Call struct {
	*mock.Call
}

// UpdateWithTenantCap is a helper method to define mock.On call
//   - ctx context.Context
//   - g *gateway.Gateway
//   - tenantID string
//   - maxInstances int
func (_e *Repository_Expecter) UpdateWithTenantCap(ctx interface{}, g interface{}, tenantID interface{}, maxInstances interface{}) *Repository_UpdateWithTenantCap_Call {
	return &Repository_UpdateWithTenantCap_Call{Call: _e.mock.On("UpdateWithTenantCap", ctx, g, tenantID, maxInstances)}
}

func (_c *Repository_UpdateWithTenantCap_Call) Run(run func(ctx context.Context, g *gateway.Gateway, tenantID string, maxInstances int)) *Repository_UpdateWithTenantCap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.Gateway), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *Repository_UpdateWithTenantCap_Call) Return(_a0 error) *Repository_UpdateWithTenantCap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_UpdateWithTenantCap_Call) RunAndReturn(run func(context.Context, *gateway.Gateway, string, int) error) *Repository_UpdateWithTenantCap_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
