// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	consumer "github.com/NeuralTrust/TrustGate/pkg/app/consumer"

	domainconsumer "github.com/NeuralTrust/TrustGate/pkg/domain/consumer"

	mock "github.com/stretchr/testify/mock"
)

// LabelSetUpdater is an autogenerated mock type for the LabelSetUpdater type
type LabelSetUpdater struct {
	mock.Mock
}

type LabelSetUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *LabelSetUpdater) EXPECT() *LabelSetUpdater_Expecter {
	return &LabelSetUpdater_Expecter{mock: &_m.Mock}
}

// UpdateLabelSets provides a mock function with given fields: ctx, in
func (_m *LabelSetUpdater) UpdateLabelSets(ctx context.Context, in consumer.UpdateLabelSetsInput) (*domainconsumer.Consumer, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLabelSets")
	}

	var r0 *domainconsumer.Consumer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, consumer.UpdateLabelSetsInput) (*domainconsumer.Consumer, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, consumer.UpdateLabelSetsInput) *domainconsumer.Consumer); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainconsumer.Consumer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, consumer.UpdateLabelSetsInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LabelSetUpdater_UpdateLabelSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLabelSets'
type LabelSetUpdater_UpdateLabelSets_Call struct {
	*mock.Call
}

// UpdateLabelSets is a helper method to define mock.On call
//   - ctx context.Context
//   - in consumer.UpdateLabelSetsInput
func (_e *LabelSetUpdater_Expecter) UpdateLabelSets(ctx interface{}, in interface{}) *LabelSetUpdater_UpdateLabelSets_Call {
	return &LabelSetUpdater_UpdateLabelSets_Call{Call: _e.mock.On("UpdateLabelSets", ctx, in)}
}

func (_c *LabelSetUpdater_UpdateLabelSets_Call) Run(run func(ctx context.Context, in consumer.UpdateLabelSetsInput)) *LabelSetUpdater_UpdateLabelSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(consumer.UpdateLabelSetsInput))
	})
	return _c
}

func (_c *LabelSetUpdater_UpdateLabelSets_Call) Return(_a0 *domainconsumer.Consumer, _a1 error) *LabelSetUpdater_UpdateLabelSets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LabelSetUpdater_UpdateLabelSets_Call) RunAndReturn(run func(context.Context, consumer.UpdateLabelSetsInput) (*domainconsumer.Consumer, error)) *LabelSetUpdater_UpdateLabelSets_Call {
	_c.Call.Return(run)
	return _c
}

// NewLabelSetUpdater creates a new instance of LabelSetUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLabelSetUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *LabelSetUpdater {
	mock := &LabelSetUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
