version: 2

run:
  timeout: 10m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"
  exclude-rules:
    - linters:
        - errcheck
      text: "Error return value of `.*Close` is not checked"
