linters:
  enable:
    - gofmt
    - govet
    - gosec
    - gosimple
    - staticcheck
    - typecheck
    - unused
    - misspell
    - errcheck

run:
  timeout: 5m
  exclude-dirs-use-default: false
  exclude-files:
    - "vendor/.*"
    - "_test\\.go$"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    ignore: fmt:.*,write,close

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: pkg/server/proxy_server\.go
      text: "Error return value of .* is not checked"
      linters:
        - errcheck
    - path: pkg/plugins/manager\.go
      text: "Error return value of .* is not checked"
      linters:
        - errcheck
    - path: pkg/loadbalancer/load_balancer\.go
      text: "Error return value of .* is not checked"
      linters:
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0 