server:
  admin_port: 8080
  proxy_port: 8081
  base_domain: example.com

redis:
  host: redis
  port: 6379
  password: ""
  db: 0

database:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  dbname: ai_gateway
  ssl_mode: disable 