apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: agentgateway-proxy-psc-healthcheck
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    config:
      type: HTTP
      httpHealthCheck:
        port: 8081
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: agentgateway-proxy-psc
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: agentgateway-mcp-psc-healthcheck
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    config:
      type: HTTP
      httpHealthCheck:
        port: 8082
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: agentgateway-mcp-psc
