apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentgateway-admin
spec:
  template:
    spec:
      containers:
      - name: admin
        resources:
          limits:
            cpu: 200m
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentgateway-proxy
spec:
  template:
    spec:
      containers:
      - name: proxy
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "2"
            memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentgateway-mcp
spec:
  template:
    spec:
      containers:
      - name: mcp
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi
