// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	ids "github.com/NeuralTrust/TrustGate/pkg/domain/ids"
	domainregistry "github.com/NeuralTrust/TrustGate/pkg/domain/registry"

	mock "github.com/stretchr/testify/mock"

	registry "github.com/NeuralTrust/TrustGate/pkg/app/registry"
)

// PinnedToolService is an autogenerated mock type for the PinnedToolService type
type PinnedToolService struct {
	mock.Mock
}

type PinnedToolService_Expecter struct {
	mock *mock.Mock
}

func (_m *PinnedToolService) EXPECT() *PinnedToolService_Expecter {
	return &PinnedToolService_Expecter{mock: &_m.Mock}
}

// Decide provides a mock function with given fields: ctx, in
func (_m *PinnedToolService) Decide(ctx context.Context, in registry.DecideToolsInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Decide")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, registry.DecideToolsInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PinnedToolService_Decide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decide'
type PinnedToolService_Decide_Call struct {
	*mock.Call
}

// Decide is a helper method to define mock.On call
//   - ctx context.Context
//   - in registry.DecideToolsInput
func (_e *PinnedToolService_Expecter) Decide(ctx interface{}, in interface{}) *PinnedToolService_Decide_Call {
	return &PinnedToolService_Decide_Call{Call: _e.mock.On("Decide", ctx, in)}
}

func (_c *PinnedToolService_Decide_Call) Run(run func(ctx context.Context, in registry.DecideToolsInput)) *PinnedToolService_Decide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(registry.DecideToolsInput))
	})
	return _c
}

func (_c *PinnedToolService_Decide_Call) Return(_a0 error) *PinnedToolService_Decide_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PinnedToolService_Decide_Call) RunAndReturn(run func(context.Context, registry.DecideToolsInput) error) *PinnedToolService_Decide_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, gatewayID, registryID, status
func (_m *PinnedToolService) List(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], registryID ids.ID[ids.RegistryKind], status *domainregistry.ToolStatus) (*registry.PinnedToolList, error) {
	ret := _m.Called(ctx, gatewayID, registryID, status)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *registry.PinnedToolList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind], *domainregistry.ToolStatus) (*registry.PinnedToolList, error)); ok {
		return rf(ctx, gatewayID, registryID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind], *domainregistry.ToolStatus) *registry.PinnedToolList); ok {
		r0 = rf(ctx, gatewayID, registryID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.PinnedToolList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind], *domainregistry.ToolStatus) error); ok {
		r1 = rf(ctx, gatewayID, registryID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PinnedToolService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PinnedToolService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - registryID ids.ID[ids.RegistryKind]
//   - status *domainregistry.ToolStatus
func (_e *PinnedToolService_Expecter) List(ctx interface{}, gatewayID interface{}, registryID interface{}, status interface{}) *PinnedToolService_List_Call {
	return &PinnedToolService_List_Call{Call: _e.mock.On("List", ctx, gatewayID, registryID, status)}
}

func (_c *PinnedToolService_List_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], registryID ids.ID[ids.RegistryKind], status *domainregistry.ToolStatus)) *PinnedToolService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].(ids.ID[ids.RegistryKind]), args[3].(*domainregistry.ToolStatus))
	})
	return _c
}

func (_c *PinnedToolService_List_Call) Return(_a0 *registry.PinnedToolList, _a1 error) *PinnedToolService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PinnedToolService_List_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind], *domainregistry.ToolStatus) (*registry.PinnedToolList, error)) *PinnedToolService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Pin provides a mock function with given fields: ctx, in
func (_m *PinnedToolService) Pin(ctx context.Context, in registry.PinToolsInput) (*domainregistry.Registry, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Pin")
	}

	var r0 *domainregistry.Registry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, registry.PinToolsInput) (*domainregistry.Registry, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, registry.PinToolsInput) *domainregistry.Registry); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainregistry.Registry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, registry.PinToolsInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PinnedToolService_Pin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pin'
type PinnedToolService_Pin_Call struct {
	*mock.Call
}

// Pin is a helper method to define mock.On call
//   - ctx context.Context
//   - in registry.PinToolsInput
func (_e *PinnedToolService_Expecter) Pin(ctx interface{}, in interface{}) *PinnedToolService_Pin_Call {
	return &PinnedToolService_Pin_Call{Call: _e.mock.On("Pin", ctx, in)}
}

func (_c *PinnedToolService_Pin_Call) Run(run func(ctx context.Context, in registry.PinToolsInput)) *PinnedToolService_Pin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(registry.PinToolsInput))
	})
	return _c
}

func (_c *PinnedToolService_Pin_Call) Return(_a0 *domainregistry.Registry, _a1 error) *PinnedToolService_Pin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PinnedToolService_Pin_Call) RunAndReturn(run func(context.Context, registry.PinToolsInput) (*domainregistry.Registry, error)) *PinnedToolService_Pin_Call {
	_c.Call.Return(run)
	return _c
}

// NewPinnedToolService creates a new instance of PinnedToolService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPinnedToolService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PinnedToolService {
	mock := &PinnedToolService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
