// Copyright 2026 NeuralTrust
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: configsync.proto

package snapshotpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigSync_Sync_FullMethodName        = "/snapshotpb.ConfigSync/Sync"
	ConfigSync_GetSnapshot_FullMethodName = "/snapshotpb.ConfigSync/GetSnapshot"
)

// ConfigSyncClient is the client API for ConfigSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfigSync is the DP-initiated config-sync transport. The data plane dials the
// control plane (egress-only) and holds one long-lived Sync stream for change
// notices and acks; it pulls the compiled snapshot out-of-band via GetSnapshot.
type ConfigSyncClient interface {
	// Sync is the long-lived control channel: the data plane sends Hello, then reads
	// VersionNotice messages and replies with Ack after each successful swap.
	Sync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
	// GetSnapshot streams the current compiled snapshot as ordered byte chunks. The
	// first message is a SnapshotHeader; when the applied version already matches the
	// header carries not_modified=true and no data chunks follow.
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotChunk], error)
}

type configSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigSyncClient(cc grpc.ClientConnInterface) ConfigSyncClient {
	return &configSyncClient{cc}
}

func (c *configSyncClient) Sync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfigSync_ServiceDesc.Streams[0], ConfigSync_Sync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigSync_SyncClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

func (c *configSyncClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfigSync_ServiceDesc.Streams[1], ConfigSync_GetSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetSnapshotRequest, SnapshotChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigSync_GetSnapshotClient = grpc.ServerStreamingClient[SnapshotChunk]

// ConfigSyncServer is the server API for ConfigSync service.
// All implementations must embed UnimplementedConfigSyncServer
// for forward compatibility.
//
// ConfigSync is the DP-initiated config-sync transport. The data plane dials the
// control plane (egress-only) and holds one long-lived Sync stream for change
// notices and acks; it pulls the compiled snapshot out-of-band via GetSnapshot.
type ConfigSyncServer interface {
	// Sync is the long-lived control channel: the data plane sends Hello, then reads
	// VersionNotice messages and replies with Ack after each successful swap.
	Sync(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	// GetSnapshot streams the current compiled snapshot as ordered byte chunks. The
	// first message is a SnapshotHeader; when the applied version already matches the
	// header carries not_modified=true and no data chunks follow.
	GetSnapshot(*GetSnapshotRequest, grpc.ServerStreamingServer[SnapshotChunk]) error
	mustEmbedUnimplementedConfigSyncServer()
}

// UnimplementedConfigSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigSyncServer struct{}

func (UnimplementedConfigSyncServer) Sync(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedConfigSyncServer) GetSnapshot(*GetSnapshotRequest, grpc.ServerStreamingServer[SnapshotChunk]) error {
	return status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedConfigSyncServer) mustEmbedUnimplementedConfigSyncServer() {}
func (UnimplementedConfigSyncServer) testEmbeddedByValue()                    {}

// UnsafeConfigSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigSyncServer will
// result in compilation errors.
type UnsafeConfigSyncServer interface {
	mustEmbedUnimplementedConfigSyncServer()
}

func RegisterConfigSyncServer(s grpc.ServiceRegistrar, srv ConfigSyncServer) {
	// If the following call panics, it indicates UnimplementedConfigSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigSync_ServiceDesc, srv)
}

func _ConfigSync_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConfigSyncServer).Sync(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigSync_SyncServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

func _ConfigSync_GetSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigSyncServer).GetSnapshot(m, &grpc.GenericServerStream[GetSnapshotRequest, SnapshotChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigSync_GetSnapshotServer = grpc.ServerStreamingServer[SnapshotChunk]

// ConfigSync_ServiceDesc is the grpc.ServiceDesc for ConfigSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snapshotpb.ConfigSync",
	HandlerType: (*ConfigSyncServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _ConfigSync_Sync_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetSnapshot",
			Handler:       _ConfigSync_GetSnapshot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "configsync.proto",
}
