// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	bedrock "github.com/NeuralTrust/TrustGate/pkg/infra/bedrock"
	bedrockruntime "github.com/aws/aws-sdk-go-v2/service/bedrockruntime"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// BuildClient provides a mock function with given fields: ctx, accessKey, secretKey, sessionToken, region, useRole, roleARN, sessionName
func (_m *Client) BuildClient(ctx context.Context, accessKey string, secretKey string, sessionToken string, region string, useRole bool, roleARN string, sessionName string) (bedrock.Client, error) {
	ret := _m.Called(ctx, accessKey, secretKey, sessionToken, region, useRole, roleARN, sessionName)

	if len(ret) == 0 {
		panic("no return value specified for BuildClient")
	}

	var r0 bedrock.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, bool, string, string) (bedrock.Client, error)); ok {
		return rf(ctx, accessKey, secretKey, sessionToken, region, useRole, roleARN, sessionName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, bool, string, string) bedrock.Client); ok {
		r0 = rf(ctx, accessKey, secretKey, sessionToken, region, useRole, roleARN, sessionName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bedrock.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, bool, string, string) error); ok {
		r1 = rf(ctx, accessKey, secretKey, sessionToken, region, useRole, roleARN, sessionName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_BuildClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildClient'
type Client_BuildClient_Call struct {
	*mock.Call
}

// BuildClient is a helper method to define mock.On call
//   - ctx context.Context
//   - accessKey string
//   - secretKey string
//   - sessionToken string
//   - region string
//   - useRole bool
//   - roleARN string
//   - sessionName string
func (_e *Client_Expecter) BuildClient(ctx interface{}, accessKey interface{}, secretKey interface{}, sessionToken interface{}, region interface{}, useRole interface{}, roleARN interface{}, sessionName interface{}) *Client_BuildClient_Call {
	return &Client_BuildClient_Call{Call: _e.mock.On("BuildClient", ctx, accessKey, secretKey, sessionToken, region, useRole, roleARN, sessionName)}
}

func (_c *Client_BuildClient_Call) Run(run func(ctx context.Context, accessKey string, secretKey string, sessionToken string, region string, useRole bool, roleARN string, sessionName string)) *Client_BuildClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(bool), args[6].(string), args[7].(string))
	})
	return _c
}

func (_c *Client_BuildClient_Call) Return(_a0 bedrock.Client, _a1 error) *Client_BuildClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_BuildClient_Call) RunAndReturn(run func(context.Context, string, string, string, string, bool, string, string) (bedrock.Client, error)) *Client_BuildClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetRuntimeClient provides a mock function with no fields
func (_m *Client) GetRuntimeClient() *bedrockruntime.Client {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRuntimeClient")
	}

	var r0 *bedrockruntime.Client
	if rf, ok := ret.Get(0).(func() *bedrockruntime.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bedrockruntime.Client)
		}
	}

	return r0
}

// Client_GetRuntimeClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRuntimeClient'
type Client_GetRuntimeClient_Call struct {
	*mock.Call
}

// GetRuntimeClient is a helper method to define mock.On call
func (_e *Client_Expecter) GetRuntimeClient() *Client_GetRuntimeClient_Call {
	return &Client_GetRuntimeClient_Call{Call: _e.mock.On("GetRuntimeClient")}
}

func (_c *Client_GetRuntimeClient_Call) Run(run func()) *Client_GetRuntimeClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_GetRuntimeClient_Call) Return(_a0 *bedrockruntime.Client) *Client_GetRuntimeClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_GetRuntimeClient_Call) RunAndReturn(run func() *bedrockruntime.Client) *Client_GetRuntimeClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
