// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	ids "github.com/NeuralTrust/AgentGateway/pkg/domain/ids"
	mock "github.com/stretchr/testify/mock"
)

// Associator is an autogenerated mock type for the Associator type
type Associator struct {
	mock.Mock
}

type Associator_Expecter struct {
	mock *mock.Mock
}

func (_m *Associator) EXPECT() *Associator_Expecter {
	return &Associator_Expecter{mock: &_m.Mock}
}

// AttachRegistry provides a mock function with given fields: ctx, gatewayID, roleID, registryID
func (_m *Associator) AttachRegistry(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], roleID ids.ID[ids.RoleKind], registryID ids.ID[ids.RegistryKind]) error {
	ret := _m.Called(ctx, gatewayID, roleID, registryID)

	if len(ret) == 0 {
		panic("no return value specified for AttachRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RoleKind], ids.ID[ids.RegistryKind]) error); ok {
		r0 = rf(ctx, gatewayID, roleID, registryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Associator_AttachRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachRegistry'
type Associator_AttachRegistry_Call struct {
	*mock.Call
}

// AttachRegistry is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - roleID ids.ID[ids.RoleKind]
//   - registryID ids.ID[ids.RegistryKind]
func (_e *Associator_Expecter) AttachRegistry(ctx interface{}, gatewayID interface{}, roleID interface{}, registryID interface{}) *Associator_AttachRegistry_Call {
	return &Associator_AttachRegistry_Call{Call: _e.mock.On("AttachRegistry", ctx, gatewayID, roleID, registryID)}
}

func (_c *Associator_AttachRegistry_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], roleID ids.ID[ids.RoleKind], registryID ids.ID[ids.RegistryKind])) *Associator_AttachRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].(ids.ID[ids.RoleKind]), args[3].(ids.ID[ids.RegistryKind]))
	})
	return _c
}

func (_c *Associator_AttachRegistry_Call) Return(_a0 error) *Associator_AttachRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Associator_AttachRegistry_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RoleKind], ids.ID[ids.RegistryKind]) error) *Associator_AttachRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// DetachRegistry provides a mock function with given fields: ctx, gatewayID, roleID, registryID
func (_m *Associator) DetachRegistry(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], roleID ids.ID[ids.RoleKind], registryID ids.ID[ids.RegistryKind]) error {
	ret := _m.Called(ctx, gatewayID, roleID, registryID)

	if len(ret) == 0 {
		panic("no return value specified for DetachRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RoleKind], ids.ID[ids.RegistryKind]) error); ok {
		r0 = rf(ctx, gatewayID, roleID, registryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Associator_DetachRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetachRegistry'
type Associator_DetachRegistry_Call struct {
	*mock.Call
}

// DetachRegistry is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - roleID ids.ID[ids.RoleKind]
//   - registryID ids.ID[ids.RegistryKind]
func (_e *Associator_Expecter) DetachRegistry(ctx interface{}, gatewayID interface{}, roleID interface{}, registryID interface{}) *Associator_DetachRegistry_Call {
	return &Associator_DetachRegistry_Call{Call: _e.mock.On("DetachRegistry", ctx, gatewayID, roleID, registryID)}
}

func (_c *Associator_DetachRegistry_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], roleID ids.ID[ids.RoleKind], registryID ids.ID[ids.RegistryKind])) *Associator_DetachRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].(ids.ID[ids.RoleKind]), args[3].(ids.ID[ids.RegistryKind]))
	})
	return _c
}

func (_c *Associator_DetachRegistry_Call) Return(_a0 error) *Associator_DetachRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Associator_DetachRegistry_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RoleKind], ids.ID[ids.RegistryKind]) error) *Associator_DetachRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// NewAssociator creates a new instance of Associator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAssociator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Associator {
	mock := &Associator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
