// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	catalog "github.com/NeuralTrust/TrustGate/pkg/app/catalog"

	mock "github.com/stretchr/testify/mock"
)

// ModelListing is an autogenerated mock type for the ModelListing type
type ModelListing struct {
	mock.Mock
}

type ModelListing_Expecter struct {
	mock *mock.Mock
}

func (_m *ModelListing) EXPECT() *ModelListing_Expecter {
	return &ModelListing_Expecter{mock: &_m.Mock}
}

// InvalidateCache provides a mock function with no fields
func (_m *ModelListing) InvalidateCache() {
	_m.Called()
}

// ModelListing_InvalidateCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateCache'
type ModelListing_InvalidateCache_Call struct {
	*mock.Call
}

// InvalidateCache is a helper method to define mock.On call
func (_e *ModelListing_Expecter) InvalidateCache() *ModelListing_InvalidateCache_Call {
	return &ModelListing_InvalidateCache_Call{Call: _e.mock.On("InvalidateCache")}
}

func (_c *ModelListing_InvalidateCache_Call) Run(run func()) *ModelListing_InvalidateCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ModelListing_InvalidateCache_Call) Return() *ModelListing_InvalidateCache_Call {
	_c.Call.Return()
	return _c
}

func (_c *ModelListing_InvalidateCache_Call) RunAndReturn(run func()) *ModelListing_InvalidateCache_Call {
	_c.Run(run)
	return _c
}

// Lists provides a mock function with given fields: ctx, providerCode, model
func (_m *ModelListing) Lists(ctx context.Context, providerCode string, model string) catalog.Verdict {
	ret := _m.Called(ctx, providerCode, model)

	if len(ret) == 0 {
		panic("no return value specified for Lists")
	}

	var r0 catalog.Verdict
	if rf, ok := ret.Get(0).(func(context.Context, string, string) catalog.Verdict); ok {
		r0 = rf(ctx, providerCode, model)
	} else {
		r0 = ret.Get(0).(catalog.Verdict)
	}

	return r0
}

// ModelListing_Lists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lists'
type ModelListing_Lists_Call struct {
	*mock.Call
}

// Lists is a helper method to define mock.On call
//   - ctx context.Context
//   - providerCode string
//   - model string
func (_e *ModelListing_Expecter) Lists(ctx interface{}, providerCode interface{}, model interface{}) *ModelListing_Lists_Call {
	return &ModelListing_Lists_Call{Call: _e.mock.On("Lists", ctx, providerCode, model)}
}

func (_c *ModelListing_Lists_Call) Run(run func(ctx context.Context, providerCode string, model string)) *ModelListing_Lists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ModelListing_Lists_Call) Return(_a0 catalog.Verdict) *ModelListing_Lists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ModelListing_Lists_Call) RunAndReturn(run func(context.Context, string, string) catalog.Verdict) *ModelListing_Lists_Call {
	_c.Call.Return(run)
	return _c
}

// NewModelListing creates a new instance of ModelListing. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelListing(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelListing {
	mock := &ModelListing{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
