// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	catalog "github.com/NeuralTrust/TrustGate/pkg/app/catalog"

	mock "github.com/stretchr/testify/mock"
)

// ModelAvailability is an autogenerated mock type for the ModelAvailability type
type ModelAvailability struct {
	mock.Mock
}

type ModelAvailability_Expecter struct {
	mock *mock.Mock
}

func (_m *ModelAvailability) EXPECT() *ModelAvailability_Expecter {
	return &ModelAvailability_Expecter{mock: &_m.Mock}
}

// InvalidateCache provides a mock function with no fields
func (_m *ModelAvailability) InvalidateCache() {
	_m.Called()
}

// ModelAvailability_InvalidateCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateCache'
type ModelAvailability_InvalidateCache_Call struct {
	*mock.Call
}

// InvalidateCache is a helper method to define mock.On call
func (_e *ModelAvailability_Expecter) InvalidateCache() *ModelAvailability_InvalidateCache_Call {
	return &ModelAvailability_InvalidateCache_Call{Call: _e.mock.On("InvalidateCache")}
}

func (_c *ModelAvailability_InvalidateCache_Call) Run(run func()) *ModelAvailability_InvalidateCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ModelAvailability_InvalidateCache_Call) Return() *ModelAvailability_InvalidateCache_Call {
	_c.Call.Return()
	return _c
}

func (_c *ModelAvailability_InvalidateCache_Call) RunAndReturn(run func()) *ModelAvailability_InvalidateCache_Call {
	_c.Run(run)
	return _c
}

// Serves provides a mock function with given fields: ctx, providerCode, model
func (_m *ModelAvailability) Serves(ctx context.Context, providerCode string, model string) catalog.Verdict {
	ret := _m.Called(ctx, providerCode, model)

	if len(ret) == 0 {
		panic("no return value specified for Serves")
	}

	var r0 catalog.Verdict
	if rf, ok := ret.Get(0).(func(context.Context, string, string) catalog.Verdict); ok {
		r0 = rf(ctx, providerCode, model)
	} else {
		r0 = ret.Get(0).(catalog.Verdict)
	}

	return r0
}

// ModelAvailability_Serves_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serves'
type ModelAvailability_Serves_Call struct {
	*mock.Call
}

// Serves is a helper method to define mock.On call
//   - ctx context.Context
//   - providerCode string
//   - model string
func (_e *ModelAvailability_Expecter) Serves(ctx interface{}, providerCode interface{}, model interface{}) *ModelAvailability_Serves_Call {
	return &ModelAvailability_Serves_Call{Call: _e.mock.On("Serves", ctx, providerCode, model)}
}

func (_c *ModelAvailability_Serves_Call) Run(run func(ctx context.Context, providerCode string, model string)) *ModelAvailability_Serves_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ModelAvailability_Serves_Call) Return(_a0 catalog.Verdict) *ModelAvailability_Serves_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ModelAvailability_Serves_Call) RunAndReturn(run func(context.Context, string, string) catalog.Verdict) *ModelAvailability_Serves_Call {
	_c.Call.Return(run)
	return _c
}

// NewModelAvailability creates a new instance of ModelAvailability. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelAvailability(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelAvailability {
	mock := &ModelAvailability{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
