// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	catalog "github.com/NeuralTrust/TrustGate/pkg/app/catalog"

	domaincatalog "github.com/NeuralTrust/TrustGate/pkg/domain/catalog"

	mock "github.com/stretchr/testify/mock"
)

// RegistryAvailability is an autogenerated mock type for the RegistryAvailability type
type RegistryAvailability struct {
	mock.Mock
}

type RegistryAvailability_Expecter struct {
	mock *mock.Mock
}

func (_m *RegistryAvailability) EXPECT() *RegistryAvailability_Expecter {
	return &RegistryAvailability_Expecter{mock: &_m.Mock}
}

// Narrow provides a mock function with given fields: ctx, in
func (_m *RegistryAvailability) Narrow(ctx context.Context, in catalog.ServerlessFilterInput) ([]domaincatalog.Model, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Narrow")
	}

	var r0 []domaincatalog.Model
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, catalog.ServerlessFilterInput) ([]domaincatalog.Model, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, catalog.ServerlessFilterInput) []domaincatalog.Model); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domaincatalog.Model)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, catalog.ServerlessFilterInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistryAvailability_Narrow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Narrow'
type RegistryAvailability_Narrow_Call struct {
	*mock.Call
}

// Narrow is a helper method to define mock.On call
//   - ctx context.Context
//   - in catalog.ServerlessFilterInput
func (_e *RegistryAvailability_Expecter) Narrow(ctx interface{}, in interface{}) *RegistryAvailability_Narrow_Call {
	return &RegistryAvailability_Narrow_Call{Call: _e.mock.On("Narrow", ctx, in)}
}

func (_c *RegistryAvailability_Narrow_Call) Run(run func(ctx context.Context, in catalog.ServerlessFilterInput)) *RegistryAvailability_Narrow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(catalog.ServerlessFilterInput))
	})
	return _c
}

func (_c *RegistryAvailability_Narrow_Call) Return(_a0 []domaincatalog.Model, _a1 error) *RegistryAvailability_Narrow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegistryAvailability_Narrow_Call) RunAndReturn(run func(context.Context, catalog.ServerlessFilterInput) ([]domaincatalog.Model, error)) *RegistryAvailability_Narrow_Call {
	_c.Call.Return(run)
	return _c
}

// NewRegistryAvailability creates a new instance of RegistryAvailability. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistryAvailability(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegistryAvailability {
	mock := &RegistryAvailability{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
