// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	topic "github.com/NeuralTrust/TrustGate/pkg/domain/topic"
	mock "github.com/stretchr/testify/mock"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

type Cache_Expecter struct {
	mock *mock.Mock
}

func (_m *Cache) EXPECT() *Cache_Expecter {
	return &Cache_Expecter{mock: &_m.Mock}
}

// GetMany provides a mock function with given fields: ctx, keys
func (_m *Cache) GetMany(ctx context.Context, keys []string) (map[string]topic.Classification, error) {
	ret := _m.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for GetMany")
	}

	var r0 map[string]topic.Classification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]topic.Classification, error)); ok {
		return rf(ctx, keys)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]topic.Classification); ok {
		r0 = rf(ctx, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]topic.Classification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, keys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cache_GetMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMany'
type Cache_GetMany_Call struct {
	*mock.Call
}

// GetMany is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
func (_e *Cache_Expecter) GetMany(ctx interface{}, keys interface{}) *Cache_GetMany_Call {
	return &Cache_GetMany_Call{Call: _e.mock.On("GetMany", ctx, keys)}
}

func (_c *Cache_GetMany_Call) Run(run func(ctx context.Context, keys []string)) *Cache_GetMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *Cache_GetMany_Call) Return(_a0 map[string]topic.Classification, _a1 error) *Cache_GetMany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Cache_GetMany_Call) RunAndReturn(run func(context.Context, []string) (map[string]topic.Classification, error)) *Cache_GetMany_Call {
	_c.Call.Return(run)
	return _c
}

// SetMany provides a mock function with given fields: ctx, entries
func (_m *Cache) SetMany(ctx context.Context, entries map[string]topic.Classification) error {
	ret := _m.Called(ctx, entries)

	if len(ret) == 0 {
		panic("no return value specified for SetMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]topic.Classification) error); ok {
		r0 = rf(ctx, entries)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cache_SetMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMany'
type Cache_SetMany_Call struct {
	*mock.Call
}

// SetMany is a helper method to define mock.On call
//   - ctx context.Context
//   - entries map[string]topic.Classification
func (_e *Cache_Expecter) SetMany(ctx interface{}, entries interface{}) *Cache_SetMany_Call {
	return &Cache_SetMany_Call{Call: _e.mock.On("SetMany", ctx, entries)}
}

func (_c *Cache_SetMany_Call) Run(run func(ctx context.Context, entries map[string]topic.Classification)) *Cache_SetMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]topic.Classification))
	})
	return _c
}

func (_c *Cache_SetMany_Call) Return(_a0 error) *Cache_SetMany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Cache_SetMany_Call) RunAndReturn(run func(context.Context, map[string]topic.Classification) error) *Cache_SetMany_Call {
	_c.Call.Return(run)
	return _c
}

// NewCache creates a new instance of Cache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cache {
	mock := &Cache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
