// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	topicclassifier "github.com/NeuralTrust/TrustGate/pkg/app/topicclassifier"
	mock "github.com/stretchr/testify/mock"
)

// Intake is an autogenerated mock type for the Intake type
type Intake struct {
	mock.Mock
}

type Intake_Expecter struct {
	mock *mock.Mock
}

func (_m *Intake) EXPECT() *Intake_Expecter {
	return &Intake_Expecter{mock: &_m.Mock}
}

// Shutdown provides a mock function with given fields: ctx
func (_m *Intake) Shutdown(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Intake_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type Intake_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Intake_Expecter) Shutdown(ctx interface{}) *Intake_Shutdown_Call {
	return &Intake_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *Intake_Shutdown_Call) Run(run func(ctx context.Context)) *Intake_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Intake_Shutdown_Call) Return(_a0 error) *Intake_Shutdown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Intake_Shutdown_Call) RunAndReturn(run func(context.Context) error) *Intake_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with no fields
func (_m *Intake) Start() {
	_m.Called()
}

// Intake_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Intake_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *Intake_Expecter) Start() *Intake_Start_Call {
	return &Intake_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *Intake_Start_Call) Run(run func()) *Intake_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Intake_Start_Call) Return() *Intake_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *Intake_Start_Call) RunAndReturn(run func()) *Intake_Start_Call {
	_c.Run(run)
	return _c
}

// Submit provides a mock function with given fields: c
func (_m *Intake) Submit(c topicclassifier.Candidate) bool {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(topicclassifier.Candidate) bool); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Intake_Submit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submit'
type Intake_Submit_Call struct {
	*mock.Call
}

// Submit is a helper method to define mock.On call
//   - c topicclassifier.Candidate
func (_e *Intake_Expecter) Submit(c interface{}) *Intake_Submit_Call {
	return &Intake_Submit_Call{Call: _e.mock.On("Submit", c)}
}

func (_c *Intake_Submit_Call) Run(run func(c topicclassifier.Candidate)) *Intake_Submit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(topicclassifier.Candidate))
	})
	return _c
}

func (_c *Intake_Submit_Call) Return(_a0 bool) *Intake_Submit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Intake_Submit_Call) RunAndReturn(run func(topicclassifier.Candidate) bool) *Intake_Submit_Call {
	_c.Call.Return(run)
	return _c
}

// NewIntake creates a new instance of Intake. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIntake(t interface {
	mock.TestingT
	Cleanup(func())
}) *Intake {
	mock := &Intake{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
