// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	events "github.com/NeuralTrust/TrustGate/pkg/infra/metrics/events"
	mock "github.com/stretchr/testify/mock"

	telemetry "github.com/NeuralTrust/TrustGate/pkg/domain/telemetry"
)

// TopicPublisher is an autogenerated mock type for the TopicPublisher type
type TopicPublisher struct {
	mock.Mock
}

type TopicPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *TopicPublisher) EXPECT() *TopicPublisher_Expecter {
	return &TopicPublisher_Expecter{mock: &_m.Mock}
}

// PublishTopic provides a mock function with given fields: ctx, evt, exporters
func (_m *TopicPublisher) PublishTopic(ctx context.Context, evt *events.TopicClassification, exporters []telemetry.ExporterConfig) {
	_m.Called(ctx, evt, exporters)
}

// TopicPublisher_PublishTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishTopic'
type TopicPublisher_PublishTopic_Call struct {
	*mock.Call
}

// PublishTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - evt *events.TopicClassification
//   - exporters []telemetry.ExporterConfig
func (_e *TopicPublisher_Expecter) PublishTopic(ctx interface{}, evt interface{}, exporters interface{}) *TopicPublisher_PublishTopic_Call {
	return &TopicPublisher_PublishTopic_Call{Call: _e.mock.On("PublishTopic", ctx, evt, exporters)}
}

func (_c *TopicPublisher_PublishTopic_Call) Run(run func(ctx context.Context, evt *events.TopicClassification, exporters []telemetry.ExporterConfig)) *TopicPublisher_PublishTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*events.TopicClassification), args[2].([]telemetry.ExporterConfig))
	})
	return _c
}

func (_c *TopicPublisher_PublishTopic_Call) Return() *TopicPublisher_PublishTopic_Call {
	_c.Call.Return()
	return _c
}

func (_c *TopicPublisher_PublishTopic_Call) RunAndReturn(run func(context.Context, *events.TopicClassification, []telemetry.ExporterConfig)) *TopicPublisher_PublishTopic_Call {
	_c.Run(run)
	return _c
}

// NewTopicPublisher creates a new instance of TopicPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTopicPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *TopicPublisher {
	mock := &TopicPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
