// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	trafficlabel "github.com/NeuralTrust/TrustGate/pkg/domain/trafficlabel"
	mock "github.com/stretchr/testify/mock"

	trafficlabels "github.com/NeuralTrust/TrustGate/pkg/app/trafficlabels"
)

// Classifier is an autogenerated mock type for the Classifier type
type Classifier struct {
	mock.Mock
}

type Classifier_Expecter struct {
	mock *mock.Mock
}

func (_m *Classifier) EXPECT() *Classifier_Expecter {
	return &Classifier_Expecter{mock: &_m.Mock}
}

// Classify provides a mock function with given fields: ctx, in
func (_m *Classifier) Classify(ctx context.Context, in trafficlabels.ClassifyInput) (trafficlabel.Classification, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Classify")
	}

	var r0 trafficlabel.Classification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, trafficlabels.ClassifyInput) (trafficlabel.Classification, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, trafficlabels.ClassifyInput) trafficlabel.Classification); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(trafficlabel.Classification)
	}

	if rf, ok := ret.Get(1).(func(context.Context, trafficlabels.ClassifyInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Classifier_Classify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Classify'
type Classifier_Classify_Call struct {
	*mock.Call
}

// Classify is a helper method to define mock.On call
//   - ctx context.Context
//   - in trafficlabels.ClassifyInput
func (_e *Classifier_Expecter) Classify(ctx interface{}, in interface{}) *Classifier_Classify_Call {
	return &Classifier_Classify_Call{Call: _e.mock.On("Classify", ctx, in)}
}

func (_c *Classifier_Classify_Call) Run(run func(ctx context.Context, in trafficlabels.ClassifyInput)) *Classifier_Classify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(trafficlabels.ClassifyInput))
	})
	return _c
}

func (_c *Classifier_Classify_Call) Return(_a0 trafficlabel.Classification, _a1 error) *Classifier_Classify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Classifier_Classify_Call) RunAndReturn(run func(context.Context, trafficlabels.ClassifyInput) (trafficlabel.Classification, error)) *Classifier_Classify_Call {
	_c.Call.Return(run)
	return _c
}

// NewClassifier creates a new instance of Classifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClassifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Classifier {
	mock := &Classifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
