// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	gateway "github.com/NeuralTrust/TrustGate/pkg/domain/gateway"
	ids "github.com/NeuralTrust/TrustGate/pkg/domain/ids"

	mock "github.com/stretchr/testify/mock"
)

// GatewayFinder is an autogenerated mock type for the GatewayFinder type
type GatewayFinder struct {
	mock.Mock
}

type GatewayFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *GatewayFinder) EXPECT() *GatewayFinder_Expecter {
	return &GatewayFinder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *GatewayFinder) FindByID(ctx context.Context, id ids.ID[ids.GatewayKind]) (*gateway.Gateway, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *gateway.Gateway
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind]) (*gateway.Gateway, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind]) *gateway.Gateway); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.Gateway)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.GatewayKind]) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GatewayFinder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type GatewayFinder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id ids.ID[ids.GatewayKind]
func (_e *GatewayFinder_Expecter) FindByID(ctx interface{}, id interface{}) *GatewayFinder_FindByID_Call {
	return &GatewayFinder_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *GatewayFinder_FindByID_Call) Run(run func(ctx context.Context, id ids.ID[ids.GatewayKind])) *GatewayFinder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]))
	})
	return _c
}

func (_c *GatewayFinder_FindByID_Call) Return(_a0 *gateway.Gateway, _a1 error) *GatewayFinder_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GatewayFinder_FindByID_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind]) (*gateway.Gateway, error)) *GatewayFinder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewGatewayFinder creates a new instance of GatewayFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGatewayFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *GatewayFinder {
	mock := &GatewayFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
