// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Recorder is an autogenerated mock type for the Recorder type
type Recorder struct {
	mock.Mock
}

type Recorder_Expecter struct {
	mock *mock.Mock
}

func (_m *Recorder) EXPECT() *Recorder_Expecter {
	return &Recorder_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: outcome, d
func (_m *Recorder) Call(outcome string, d time.Duration) {
	_m.Called(outcome, d)
}

// Recorder_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type Recorder_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - outcome string
//   - d time.Duration
func (_e *Recorder_Expecter) Call(outcome interface{}, d interface{}) *Recorder_Call_Call {
	return &Recorder_Call_Call{Call: _e.mock.On("Call", outcome, d)}
}

func (_c *Recorder_Call_Call) Run(run func(outcome string, d time.Duration)) *Recorder_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration))
	})
	return _c
}

func (_c *Recorder_Call_Call) Return() *Recorder_Call_Call {
	_c.Call.Return()
	return _c
}

func (_c *Recorder_Call_Call) RunAndReturn(run func(string, time.Duration)) *Recorder_Call_Call {
	_c.Run(run)
	return _c
}

// Enqueue provides a mock function with given fields: outcome
func (_m *Recorder) Enqueue(outcome string) {
	_m.Called(outcome)
}

// Recorder_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type Recorder_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - outcome string
func (_e *Recorder_Expecter) Enqueue(outcome interface{}) *Recorder_Enqueue_Call {
	return &Recorder_Enqueue_Call{Call: _e.mock.On("Enqueue", outcome)}
}

func (_c *Recorder_Enqueue_Call) Run(run func(outcome string)) *Recorder_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Recorder_Enqueue_Call) Return() *Recorder_Enqueue_Call {
	_c.Call.Return()
	return _c
}

func (_c *Recorder_Enqueue_Call) RunAndReturn(run func(string)) *Recorder_Enqueue_Call {
	_c.Run(run)
	return _c
}

// Intake provides a mock function with given fields: outcome
func (_m *Recorder) Intake(outcome string) {
	_m.Called(outcome)
}

// Recorder_Intake_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Intake'
type Recorder_Intake_Call struct {
	*mock.Call
}

// Intake is a helper method to define mock.On call
//   - outcome string
func (_e *Recorder_Expecter) Intake(outcome interface{}) *Recorder_Intake_Call {
	return &Recorder_Intake_Call{Call: _e.mock.On("Intake", outcome)}
}

func (_c *Recorder_Intake_Call) Run(run func(outcome string)) *Recorder_Intake_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Recorder_Intake_Call) Return() *Recorder_Intake_Call {
	_c.Call.Return()
	return _c
}

func (_c *Recorder_Intake_Call) RunAndReturn(run func(string)) *Recorder_Intake_Call {
	_c.Run(run)
	return _c
}

// Result provides a mock function with given fields: outcome, n
func (_m *Recorder) Result(outcome string, n int) {
	_m.Called(outcome, n)
}

// Recorder_Result_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Result'
type Recorder_Result_Call struct {
	*mock.Call
}

// Result is a helper method to define mock.On call
//   - outcome string
//   - n int
func (_e *Recorder_Expecter) Result(outcome interface{}, n interface{}) *Recorder_Result_Call {
	return &Recorder_Result_Call{Call: _e.mock.On("Result", outcome, n)}
}

func (_c *Recorder_Result_Call) Run(run func(outcome string, n int)) *Recorder_Result_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *Recorder_Result_Call) Return() *Recorder_Result_Call {
	_c.Call.Return()
	return _c
}

func (_c *Recorder_Result_Call) RunAndReturn(run func(string, int)) *Recorder_Result_Call {
	_c.Run(run)
	return _c
}

// NewRecorder creates a new instance of Recorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Recorder {
	mock := &Recorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
