// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/NeuralTrust/TrustGate/pkg/domain/auth"
	identity "github.com/NeuralTrust/TrustGate/pkg/domain/identity"
	mock "github.com/stretchr/testify/mock"
)

// JWTValidator is an autogenerated mock type for the JWTValidator type
type JWTValidator struct {
	mock.Mock
}

type JWTValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *JWTValidator) EXPECT() *JWTValidator_Expecter {
	return &JWTValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with given fields: ctx, raw, cfg
func (_m *JWTValidator) Validate(ctx context.Context, raw string, cfg *auth.OAuth2Config) (*identity.Principal, error) {
	ret := _m.Called(ctx, raw, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *identity.Principal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *auth.OAuth2Config) (*identity.Principal, error)); ok {
		return rf(ctx, raw, cfg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *auth.OAuth2Config) *identity.Principal); ok {
		r0 = rf(ctx, raw, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*identity.Principal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *auth.OAuth2Config) error); ok {
		r1 = rf(ctx, raw, cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JWTValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type JWTValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - raw string
//   - cfg *auth.OAuth2Config
func (_e *JWTValidator_Expecter) Validate(ctx interface{}, raw interface{}, cfg interface{}) *JWTValidator_Validate_Call {
	return &JWTValidator_Validate_Call{Call: _e.mock.On("Validate", ctx, raw, cfg)}
}

func (_c *JWTValidator_Validate_Call) Run(run func(ctx context.Context, raw string, cfg *auth.OAuth2Config)) *JWTValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*auth.OAuth2Config))
	})
	return _c
}

func (_c *JWTValidator_Validate_Call) Return(_a0 *identity.Principal, _a1 error) *JWTValidator_Validate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JWTValidator_Validate_Call) RunAndReturn(run func(context.Context, string, *auth.OAuth2Config) (*identity.Principal, error)) *JWTValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewJWTValidator creates a new instance of JWTValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTValidator {
	mock := &JWTValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
