// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/NeuralTrust/TrustGate/pkg/domain/auth"
	mock "github.com/stretchr/testify/mock"
)

// IdentityProviderFinder is an autogenerated mock type for the IdentityProviderFinder type
type IdentityProviderFinder struct {
	mock.Mock
}

type IdentityProviderFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *IdentityProviderFinder) EXPECT() *IdentityProviderFinder_Expecter {
	return &IdentityProviderFinder_Expecter{mock: &_m.Mock}
}

// FindCandidates provides a mock function with given fields: ctx, auths, token
func (_m *IdentityProviderFinder) FindCandidates(ctx context.Context, auths []*auth.Auth, token string) ([]*auth.Auth, error) {
	ret := _m.Called(ctx, auths, token)

	if len(ret) == 0 {
		panic("no return value specified for FindCandidates")
	}

	var r0 []*auth.Auth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*auth.Auth, string) ([]*auth.Auth, error)); ok {
		return rf(ctx, auths, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*auth.Auth, string) []*auth.Auth); ok {
		r0 = rf(ctx, auths, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*auth.Auth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*auth.Auth, string) error); ok {
		r1 = rf(ctx, auths, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IdentityProviderFinder_FindCandidates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCandidates'
type IdentityProviderFinder_FindCandidates_Call struct {
	*mock.Call
}

// FindCandidates is a helper method to define mock.On call
//   - ctx context.Context
//   - auths []*auth.Auth
//   - token string
func (_e *IdentityProviderFinder_Expecter) FindCandidates(ctx interface{}, auths interface{}, token interface{}) *IdentityProviderFinder_FindCandidates_Call {
	return &IdentityProviderFinder_FindCandidates_Call{Call: _e.mock.On("FindCandidates", ctx, auths, token)}
}

func (_c *IdentityProviderFinder_FindCandidates_Call) Run(run func(ctx context.Context, auths []*auth.Auth, token string)) *IdentityProviderFinder_FindCandidates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*auth.Auth), args[2].(string))
	})
	return _c
}

func (_c *IdentityProviderFinder_FindCandidates_Call) Return(_a0 []*auth.Auth, _a1 error) *IdentityProviderFinder_FindCandidates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IdentityProviderFinder_FindCandidates_Call) RunAndReturn(run func(context.Context, []*auth.Auth, string) ([]*auth.Auth, error)) *IdentityProviderFinder_FindCandidates_Call {
	_c.Call.Return(run)
	return _c
}

// NewIdentityProviderFinder creates a new instance of IdentityProviderFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentityProviderFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentityProviderFinder {
	mock := &IdentityProviderFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
