// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/NeuralTrust/TrustGate/pkg/app/auth"

	domainauth "github.com/NeuralTrust/TrustGate/pkg/domain/auth"

	mock "github.com/stretchr/testify/mock"
)

// BudgetSetter is an autogenerated mock type for the BudgetSetter type
type BudgetSetter struct {
	mock.Mock
}

type BudgetSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *BudgetSetter) EXPECT() *BudgetSetter_Expecter {
	return &BudgetSetter_Expecter{mock: &_m.Mock}
}

// SetBudget provides a mock function with given fields: ctx, in
func (_m *BudgetSetter) SetBudget(ctx context.Context, in auth.SetBudgetInput) (*domainauth.Auth, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for SetBudget")
	}

	var r0 *domainauth.Auth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.SetBudgetInput) (*domainauth.Auth, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.SetBudgetInput) *domainauth.Auth); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainauth.Auth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.SetBudgetInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BudgetSetter_SetBudget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBudget'
type BudgetSetter_SetBudget_Call struct {
	*mock.Call
}

// SetBudget is a helper method to define mock.On call
//   - ctx context.Context
//   - in auth.SetBudgetInput
func (_e *BudgetSetter_Expecter) SetBudget(ctx interface{}, in interface{}) *BudgetSetter_SetBudget_Call {
	return &BudgetSetter_SetBudget_Call{Call: _e.mock.On("SetBudget", ctx, in)}
}

func (_c *BudgetSetter_SetBudget_Call) Run(run func(ctx context.Context, in auth.SetBudgetInput)) *BudgetSetter_SetBudget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.SetBudgetInput))
	})
	return _c
}

func (_c *BudgetSetter_SetBudget_Call) Return(_a0 *domainauth.Auth, _a1 error) *BudgetSetter_SetBudget_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BudgetSetter_SetBudget_Call) RunAndReturn(run func(context.Context, auth.SetBudgetInput) (*domainauth.Auth, error)) *BudgetSetter_SetBudget_Call {
	_c.Call.Return(run)
	return _c
}

// NewBudgetSetter creates a new instance of BudgetSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBudgetSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *BudgetSetter {
	mock := &BudgetSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
