// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	x509 "crypto/x509"

	mock "github.com/stretchr/testify/mock"
)

// ClientCertificateExtractor is an autogenerated mock type for the ClientCertificateExtractor type
type ClientCertificateExtractor struct {
	mock.Mock
}

type ClientCertificateExtractor_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientCertificateExtractor) EXPECT() *ClientCertificateExtractor_Expecter {
	return &ClientCertificateExtractor_Expecter{mock: &_m.Mock}
}

// FromXFCC provides a mock function with given fields: header
func (_m *ClientCertificateExtractor) FromXFCC(header string) (*x509.Certificate, error) {
	ret := _m.Called(header)

	if len(ret) == 0 {
		panic("no return value specified for FromXFCC")
	}

	var r0 *x509.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*x509.Certificate, error)); ok {
		return rf(header)
	}
	if rf, ok := ret.Get(0).(func(string) *x509.Certificate); ok {
		r0 = rf(header)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*x509.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(header)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientCertificateExtractor_FromXFCC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromXFCC'
type ClientCertificateExtractor_FromXFCC_Call struct {
	*mock.Call
}

// FromXFCC is a helper method to define mock.On call
//   - header string
func (_e *ClientCertificateExtractor_Expecter) FromXFCC(header interface{}) *ClientCertificateExtractor_FromXFCC_Call {
	return &ClientCertificateExtractor_FromXFCC_Call{Call: _e.mock.On("FromXFCC", header)}
}

func (_c *ClientCertificateExtractor_FromXFCC_Call) Run(run func(header string)) *ClientCertificateExtractor_FromXFCC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ClientCertificateExtractor_FromXFCC_Call) Return(_a0 *x509.Certificate, _a1 error) *ClientCertificateExtractor_FromXFCC_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientCertificateExtractor_FromXFCC_Call) RunAndReturn(run func(string) (*x509.Certificate, error)) *ClientCertificateExtractor_FromXFCC_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientCertificateExtractor creates a new instance of ClientCertificateExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientCertificateExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientCertificateExtractor {
	mock := &ClientCertificateExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
