// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/NeuralTrust/TrustGate/pkg/app/auth"

	domainauth "github.com/NeuralTrust/TrustGate/pkg/domain/auth"

	mock "github.com/stretchr/testify/mock"
)

// OwnerGroupsSetter is an autogenerated mock type for the OwnerGroupsSetter type
type OwnerGroupsSetter struct {
	mock.Mock
}

type OwnerGroupsSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *OwnerGroupsSetter) EXPECT() *OwnerGroupsSetter_Expecter {
	return &OwnerGroupsSetter_Expecter{mock: &_m.Mock}
}

// SetOwnerGroups provides a mock function with given fields: ctx, in
func (_m *OwnerGroupsSetter) SetOwnerGroups(ctx context.Context, in auth.SetOwnerGroupsInput) (*domainauth.Auth, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for SetOwnerGroups")
	}

	var r0 *domainauth.Auth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.SetOwnerGroupsInput) (*domainauth.Auth, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.SetOwnerGroupsInput) *domainauth.Auth); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domainauth.Auth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.SetOwnerGroupsInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OwnerGroupsSetter_SetOwnerGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOwnerGroups'
type OwnerGroupsSetter_SetOwnerGroups_Call struct {
	*mock.Call
}

// SetOwnerGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - in auth.SetOwnerGroupsInput
func (_e *OwnerGroupsSetter_Expecter) SetOwnerGroups(ctx interface{}, in interface{}) *OwnerGroupsSetter_SetOwnerGroups_Call {
	return &OwnerGroupsSetter_SetOwnerGroups_Call{Call: _e.mock.On("SetOwnerGroups", ctx, in)}
}

func (_c *OwnerGroupsSetter_SetOwnerGroups_Call) Run(run func(ctx context.Context, in auth.SetOwnerGroupsInput)) *OwnerGroupsSetter_SetOwnerGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.SetOwnerGroupsInput))
	})
	return _c
}

func (_c *OwnerGroupsSetter_SetOwnerGroups_Call) Return(_a0 *domainauth.Auth, _a1 error) *OwnerGroupsSetter_SetOwnerGroups_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OwnerGroupsSetter_SetOwnerGroups_Call) RunAndReturn(run func(context.Context, auth.SetOwnerGroupsInput) (*domainauth.Auth, error)) *OwnerGroupsSetter_SetOwnerGroups_Call {
	_c.Call.Return(run)
	return _c
}

// NewOwnerGroupsSetter creates a new instance of OwnerGroupsSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOwnerGroupsSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *OwnerGroupsSetter {
	mock := &OwnerGroupsSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
