// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/NeuralTrust/AgentGateway/pkg/domain/auth"
	mock "github.com/stretchr/testify/mock"
)

// IDPFinder is an autogenerated mock type for the IDPFinder type
type IDPFinder struct {
	mock.Mock
}

type IDPFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *IDPFinder) EXPECT() *IDPFinder_Expecter {
	return &IDPFinder_Expecter{mock: &_m.Mock}
}

// FindIDPAuth provides a mock function with given fields: ctx, auths, token
func (_m *IDPFinder) FindIDPAuth(ctx context.Context, auths []*auth.Auth, token string) (*auth.Auth, error) {
	ret := _m.Called(ctx, auths, token)

	if len(ret) == 0 {
		panic("no return value specified for FindIDPAuth")
	}

	var r0 *auth.Auth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*auth.Auth, string) (*auth.Auth, error)); ok {
		return rf(ctx, auths, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*auth.Auth, string) *auth.Auth); ok {
		r0 = rf(ctx, auths, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Auth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*auth.Auth, string) error); ok {
		r1 = rf(ctx, auths, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IDPFinder_FindIDPAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIDPAuth'
type IDPFinder_FindIDPAuth_Call struct {
	*mock.Call
}

// FindIDPAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - auths []*auth.Auth
//   - token string
func (_e *IDPFinder_Expecter) FindIDPAuth(ctx interface{}, auths interface{}, token interface{}) *IDPFinder_FindIDPAuth_Call {
	return &IDPFinder_FindIDPAuth_Call{Call: _e.mock.On("FindIDPAuth", ctx, auths, token)}
}

func (_c *IDPFinder_FindIDPAuth_Call) Run(run func(ctx context.Context, auths []*auth.Auth, token string)) *IDPFinder_FindIDPAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*auth.Auth), args[2].(string))
	})
	return _c
}

func (_c *IDPFinder_FindIDPAuth_Call) Return(_a0 *auth.Auth, _a1 error) *IDPFinder_FindIDPAuth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IDPFinder_FindIDPAuth_Call) RunAndReturn(run func(context.Context, []*auth.Auth, string) (*auth.Auth, error)) *IDPFinder_FindIDPAuth_Call {
	_c.Call.Return(run)
	return _c
}

// NewIDPFinder creates a new instance of IDPFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDPFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDPFinder {
	mock := &IDPFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
