// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/NeuralTrust/TrustGate/pkg/app/auth"
	domainauth "github.com/NeuralTrust/TrustGate/pkg/domain/auth"
	mock "github.com/stretchr/testify/mock"
)

// OIDCVerifier is an autogenerated mock type for the OIDCVerifier type
type OIDCVerifier struct {
	mock.Mock
}

type OIDCVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *OIDCVerifier) EXPECT() *OIDCVerifier_Expecter {
	return &OIDCVerifier_Expecter{mock: &_m.Mock}
}

// Peek provides a mock function with given fields: token
func (_m *OIDCVerifier) Peek(token string) (auth.TokenHints, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Peek")
	}

	var r0 auth.TokenHints
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (auth.TokenHints, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) auth.TokenHints); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(auth.TokenHints)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OIDCVerifier_Peek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Peek'
type OIDCVerifier_Peek_Call struct {
	*mock.Call
}

// Peek is a helper method to define mock.On call
//   - token string
func (_e *OIDCVerifier_Expecter) Peek(token interface{}) *OIDCVerifier_Peek_Call {
	return &OIDCVerifier_Peek_Call{Call: _e.mock.On("Peek", token)}
}

func (_c *OIDCVerifier_Peek_Call) Run(run func(token string)) *OIDCVerifier_Peek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *OIDCVerifier_Peek_Call) Return(_a0 auth.TokenHints, _a1 error) *OIDCVerifier_Peek_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OIDCVerifier_Peek_Call) RunAndReturn(run func(string) (auth.TokenHints, error)) *OIDCVerifier_Peek_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function with given fields: ctx, token, cfg
func (_m *OIDCVerifier) Verify(ctx context.Context, token string, cfg domainauth.OIDCConfig) (*auth.VerifiedClaims, error) {
	ret := _m.Called(ctx, token, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *auth.VerifiedClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domainauth.OIDCConfig) (*auth.VerifiedClaims, error)); ok {
		return rf(ctx, token, cfg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domainauth.OIDCConfig) *auth.VerifiedClaims); ok {
		r0 = rf(ctx, token, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.VerifiedClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domainauth.OIDCConfig) error); ok {
		r1 = rf(ctx, token, cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OIDCVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type OIDCVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - cfg domainauth.OIDCConfig
func (_e *OIDCVerifier_Expecter) Verify(ctx interface{}, token interface{}, cfg interface{}) *OIDCVerifier_Verify_Call {
	return &OIDCVerifier_Verify_Call{Call: _e.mock.On("Verify", ctx, token, cfg)}
}

func (_c *OIDCVerifier_Verify_Call) Run(run func(ctx context.Context, token string, cfg domainauth.OIDCConfig)) *OIDCVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domainauth.OIDCConfig))
	})
	return _c
}

func (_c *OIDCVerifier_Verify_Call) Return(_a0 *auth.VerifiedClaims, _a1 error) *OIDCVerifier_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OIDCVerifier_Verify_Call) RunAndReturn(run func(context.Context, string, domainauth.OIDCConfig) (*auth.VerifiedClaims, error)) *OIDCVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewOIDCVerifier creates a new instance of OIDCVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOIDCVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *OIDCVerifier {
	mock := &OIDCVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
