// Copyright 2026 NeuralTrust
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gateway

import (
	"context"
	"errors"
	"log/slog"
	"strings"

	"github.com/NeuralTrust/TrustGate/pkg/app/configsyncport"
	appmetrics "github.com/NeuralTrust/TrustGate/pkg/app/metrics"
	domain "github.com/NeuralTrust/TrustGate/pkg/domain/gateway"
	"github.com/NeuralTrust/TrustGate/pkg/domain/ratelimit"
	"github.com/NeuralTrust/TrustGate/pkg/domain/telemetry"
	"github.com/NeuralTrust/TrustGate/pkg/infra/cache"
)

const maxSlugCollisionRetries = 3

type CreateInput struct {
	Slug            string
	Domain          string
	TenantID        string
	Metadata        map[string]string
	Telemetry       *telemetry.Telemetry
	ClientTLSConfig domain.ClientTLSConfig
	SessionConfig   *domain.SessionConfig
	// Entitlements overrides the default free tier when the admin API sets it explicitly.
	Entitlements *domain.Entitlements
}

//go:generate mockery --name=Creator --dir=. --output=./mocks --filename=gateway_creator_mock.go --case=underscore --with-expecter
type Creator interface {
	Create(ctx context.Context, in CreateInput) (*domain.Gateway, error)
}

var _ Creator = (*creator)(nil)

type creator struct {
	repo                domain.Repository
	memoryCache         *cache.TTLMap
	exporterFactory     appmetrics.ExporterFactory
	logger              *slog.Logger
	signaler            configsyncport.SnapshotSignaler
	rateLimitEnabled    bool
	entitlementsMutable bool
}

func NewCreator(
	repo domain.Repository,
	manager *cache.TTLMapManager,
	exporterFactory appmetrics.ExporterFactory,
	logger *slog.Logger,
	signaler configsyncport.SnapshotSignaler,
	rateLimitEnabled bool,
	entitlementsMutable bool,
) Creator {
	return &creator{
		repo:                repo,
		memoryCache:         manager.GetTTLMap(cache.GatewayTTLName),
		exporterFactory:     exporterFactory,
		logger:              logger,
		signaler:            signaler,
		rateLimitEnabled:    rateLimitEnabled,
		entitlementsMutable: entitlementsMutable,
	}
}

func (c *creator) Create(ctx context.Context, in CreateInput) (*domain.Gateway, error) {
	if err := validateExporters(c.exporterFactory, in.Telemetry); err != nil {
		return nil, err
	}
	g, err := domain.New(in.Slug)
	if err != nil {
		return nil, err
	}
	g.Domain = in.Domain
	g.Metadata = domain.WithTenantID(domain.SanitizeClientMetadata(in.Metadata), in.TenantID)
	g.Telemetry = in.Telemetry
	g.ClientTLSConfig = in.ClientTLSConfig
	g.SessionConfig = in.SessionConfig
	if g.SessionConfig == nil {
		g.SessionConfig = domain.DefaultSessionConfig()
	}
	// Only platform admins (empty tenant) may set entitlements unless mutation is explicitly enabled.
	if in.Entitlements != nil && (in.TenantID == "" || c.entitlementsMutable) {
		g.Entitlements = *in.Entitlements
	}
	if err := g.Validate(); err != nil {
		return nil, err
	}
	maxInstances := 0
	if c.rateLimitEnabled {
		maxInstances = instanceCap(in.TenantID, g.Entitlements)
	}
	slugAutoGenerated := strings.TrimSpace(in.Slug) == ""
	if err := c.saveWithSlugRetry(ctx, g, slugAutoGenerated, in.TenantID, maxInstances); err != nil {
		return nil, err
	}
	setGatewayCache(c.memoryCache, g)
	if c.signaler != nil {
		c.signaler.Signal(ctx)
	}
	return g, nil
}

// instanceCap resolves the tier's max-instances cap; 0 means unlimited or no tenant to scope by.
func instanceCap(tenantID string, entitlements domain.Entitlements) int {
	if tenantID == "" {
		return 0
	}
	limits, ok := ratelimit.LimitsFor(entitlements.Tier)
	if !ok || !limits.HasInstanceCap() {
		return 0
	}
	return limits.MaxInstances
}

// saveWithSlugRetry inserts g via the repository's tenant-cap-locked save, retrying with a fresh slug on collision when one wasn't requested.
func (c *creator) saveWithSlugRetry(ctx context.Context, g *domain.Gateway, regenerateOnCollision bool, tenantID string, maxInstances int) error {
	for attempt := 0; ; attempt++ {
		err := c.repo.SaveWithTenantCap(ctx, g, tenantID, maxInstances)
		if err == nil {
			return nil
		}
		if !regenerateOnCollision || !errors.Is(err, domain.ErrAlreadyExists) || attempt == maxSlugCollisionRetries-1 {
			return err
		}
		slug, slugErr := domain.NewSlug()
		if slugErr != nil {
			return slugErr
		}
		g.Slug = slug
	}
}
