// Copyright 2026 NeuralTrust
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gateway

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strings"

	"github.com/NeuralTrust/TrustGate/pkg/app/configsyncport"
	appmetrics "github.com/NeuralTrust/TrustGate/pkg/app/metrics"
	commonerrors "github.com/NeuralTrust/TrustGate/pkg/common/errors"
	domain "github.com/NeuralTrust/TrustGate/pkg/domain/gateway"
	"github.com/NeuralTrust/TrustGate/pkg/domain/ratelimit"
	"github.com/NeuralTrust/TrustGate/pkg/domain/telemetry"
	"github.com/NeuralTrust/TrustGate/pkg/infra/cache"
)

const (
	maxSlugCollisionRetries = 3
	siblingListPageSize     = 100
)

type CreateInput struct {
	Slug            string
	Domain          string
	TenantID        string
	Metadata        map[string]string
	Telemetry       *telemetry.Telemetry
	ClientTLSConfig domain.ClientTLSConfig
	SessionConfig   *domain.SessionConfig
	// Entitlements is required when PlatformAdmin is true (full stamped caps).
	Entitlements *domain.Entitlements
	// PlatformAdmin is true when the JWT has no tenant claim (must stamp entitlements; TenantID comes from the body).
	PlatformAdmin bool
}

//go:generate mockery --name=Creator --dir=. --output=./mocks --filename=gateway_creator_mock.go --case=underscore --with-expecter
type Creator interface {
	Create(ctx context.Context, in CreateInput) (*domain.Gateway, error)
}

var _ Creator = (*creator)(nil)

type creator struct {
	repo             domain.Repository
	memoryCache      *cache.TTLMap
	exporterFactory  appmetrics.ExporterFactory
	logger           *slog.Logger
	signaler         configsyncport.SnapshotSignaler
	rateLimitEnabled bool
}

func NewCreator(
	repo domain.Repository,
	manager *cache.TTLMapManager,
	exporterFactory appmetrics.ExporterFactory,
	logger *slog.Logger,
	signaler configsyncport.SnapshotSignaler,
	rateLimitEnabled bool,
) Creator {
	return &creator{
		repo:             repo,
		memoryCache:      manager.GetTTLMap(cache.GatewayTTLName),
		exporterFactory:  exporterFactory,
		logger:           logger,
		signaler:         signaler,
		rateLimitEnabled: rateLimitEnabled,
	}
}

func (c *creator) Create(ctx context.Context, in CreateInput) (*domain.Gateway, error) {
	if strings.TrimSpace(in.TenantID) == "" {
		return nil, fmt.Errorf("tenant_id is required: %w", commonerrors.ErrValidation)
	}
	if err := validateExporters(c.exporterFactory, in.Telemetry); err != nil {
		return nil, err
	}
	g, err := domain.New(in.Slug)
	if err != nil {
		return nil, err
	}
	g.Domain = in.Domain
	g.Metadata = domain.WithTenantID(domain.SanitizeClientMetadata(in.Metadata), in.TenantID)
	g.Telemetry = in.Telemetry
	g.ClientTLSConfig = in.ClientTLSConfig
	g.SessionConfig = in.SessionConfig
	if g.SessionConfig == nil {
		g.SessionConfig = domain.DefaultSessionConfig()
	}
	// Platform create must stamp full entitlements; tenant callers cannot set them.
	if in.PlatformAdmin {
		if in.Entitlements == nil || !in.Entitlements.HasStampedLimits() {
			return nil, fmt.Errorf("entitlements are required for platform create: %w", commonerrors.ErrValidation)
		}
		g.Entitlements = *in.Entitlements
	} else if in.Entitlements != nil {
		return nil, fmt.Errorf("entitlements may only be set by platform admins: %w", commonerrors.ErrValidation)
	}
	// Under immutable entitlements, a new gateway still inherits the tenant's highest sibling tier so MaxInstances matches the plan.
	if isDefaultFreeTier(g.Entitlements) {
		inherited, err := c.highestSiblingTier(ctx, in.TenantID)
		if err != nil {
			return nil, err
		}
		if !isDefaultFreeTier(inherited) {
			g.Entitlements = inherited
		}
	}
	if err := g.Validate(); err != nil {
		return nil, err
	}
	maxInstances := 0
	if c.rateLimitEnabled {
		maxInstances = instanceCap(in.TenantID, g.Entitlements)
	}
	slugAutoGenerated := strings.TrimSpace(in.Slug) == ""
	if err := c.saveWithSlugRetry(ctx, g, slugAutoGenerated, in.TenantID, maxInstances); err != nil {
		return nil, err
	}
	setGatewayCache(c.memoryCache, g)
	if c.signaler != nil {
		c.signaler.Signal(ctx)
	}
	return g, nil
}

// instanceCap resolves stamped max-instances; 0 means unlimited or unstamped.
func instanceCap(tenantID string, entitlements domain.Entitlements) int {
	if strings.TrimSpace(tenantID) == "" {
		return 0
	}
	limits, ok := entitlements.ResolveLimits()
	if !ok || !limits.HasInstanceCap() {
		return 0
	}
	return limits.MaxInstances
}

func isDefaultFreeTier(ent domain.Entitlements) bool {
	tier := strings.ToLower(strings.TrimSpace(ent.Tier))
	return tier == "" || tier == ratelimit.TierFree
}

func tierRank(tier string) int {
	switch strings.ToLower(strings.TrimSpace(tier)) {
	case ratelimit.TierEnterprise:
		return 3
	case ratelimit.TierStandard:
		return 2
	default:
		return 1
	}
}

func (c *creator) highestSiblingTier(ctx context.Context, tenantID string) (domain.Entitlements, error) {
	highest := domain.DefaultEntitlements()
	for page := 1; ; page++ {
		items, total, err := c.repo.List(ctx, domain.ListFilter{
			TenantID: tenantID,
			Page:     page,
			Size:     siblingListPageSize,
		})
		if err != nil {
			return domain.Entitlements{}, err
		}
		for _, sibling := range items {
			if sibling == nil {
				continue
			}
			if tierRank(sibling.Entitlements.Tier) > tierRank(highest.Tier) {
				highest = sibling.Entitlements
			}
		}
		if len(items) == 0 || page*siblingListPageSize >= total {
			return highest, nil
		}
	}
}

// saveWithSlugRetry inserts g via the repository's tenant-cap-locked save, retrying with a fresh slug on collision when one wasn't requested.
func (c *creator) saveWithSlugRetry(ctx context.Context, g *domain.Gateway, regenerateOnCollision bool, tenantID string, maxInstances int) error {
	for attempt := 0; ; attempt++ {
		err := c.repo.SaveWithTenantCap(ctx, g, tenantID, maxInstances)
		if err == nil {
			return nil
		}
		if !regenerateOnCollision || !errors.Is(err, domain.ErrAlreadyExists) || attempt == maxSlugCollisionRetries-1 {
			return err
		}
		slug, slugErr := domain.NewSlug()
		if slugErr != nil {
			return slugErr
		}
		g.Slug = slug
	}
}
