// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	oauth "github.com/NeuralTrust/TrustGate/pkg/app/oauth"
	ids "github.com/NeuralTrust/TrustGate/pkg/domain/ids"
	registry "github.com/NeuralTrust/TrustGate/pkg/domain/registry"
	mock "github.com/stretchr/testify/mock"
)

// ConnectService is an autogenerated mock type for the ConnectService type
type ConnectService struct {
	mock.Mock
}

type ConnectService_Expecter struct {
	mock *mock.Mock
}

func (_m *ConnectService) EXPECT() *ConnectService_Expecter {
	return &ConnectService_Expecter{mock: &_m.Mock}
}

// Callback provides a mock function with given fields: ctx, baseURL, provider, state, code, errCode, errDesc
func (_m *ConnectService) Callback(ctx context.Context, baseURL string, provider string, state string, code string, errCode string, errDesc string) (string, error) {
	ret := _m.Called(ctx, baseURL, provider, state, code, errCode, errDesc)

	if len(ret) == 0 {
		panic("no return value specified for Callback")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) (string, error)); ok {
		return rf(ctx, baseURL, provider, state, code, errCode, errDesc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) string); ok {
		r0 = rf(ctx, baseURL, provider, state, code, errCode, errDesc)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, string) error); ok {
		r1 = rf(ctx, baseURL, provider, state, code, errCode, errDesc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConnectService_Callback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Callback'
type ConnectService_Callback_Call struct {
	*mock.Call
}

// Callback is a helper method to define mock.On call
//   - ctx context.Context
//   - baseURL string
//   - provider string
//   - state string
//   - code string
//   - errCode string
//   - errDesc string
func (_e *ConnectService_Expecter) Callback(ctx interface{}, baseURL interface{}, provider interface{}, state interface{}, code interface{}, errCode interface{}, errDesc interface{}) *ConnectService_Callback_Call {
	return &ConnectService_Callback_Call{Call: _e.mock.On("Callback", ctx, baseURL, provider, state, code, errCode, errDesc)}
}

func (_c *ConnectService_Callback_Call) Run(run func(ctx context.Context, baseURL string, provider string, state string, code string, errCode string, errDesc string)) *ConnectService_Callback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].(string))
	})
	return _c
}

func (_c *ConnectService_Callback_Call) Return(_a0 string, _a1 error) *ConnectService_Callback_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConnectService_Callback_Call) RunAndReturn(run func(context.Context, string, string, string, string, string, string) (string, error)) *ConnectService_Callback_Call {
	_c.Call.Return(run)
	return _c
}

// ChainURL provides a mock function with given fields: ctx, baseURL, gatewayID, resource, principalSub, resumeURL
func (_m *ConnectService) ChainURL(ctx context.Context, baseURL string, gatewayID ids.ID[ids.GatewayKind], resource string, principalSub string, resumeURL string) (string, error) {
	ret := _m.Called(ctx, baseURL, gatewayID, resource, principalSub, resumeURL)

	if len(ret) == 0 {
		panic("no return value specified for ChainURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ids.ID[ids.GatewayKind], string, string, string) (string, error)); ok {
		return rf(ctx, baseURL, gatewayID, resource, principalSub, resumeURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ids.ID[ids.GatewayKind], string, string, string) string); ok {
		r0 = rf(ctx, baseURL, gatewayID, resource, principalSub, resumeURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ids.ID[ids.GatewayKind], string, string, string) error); ok {
		r1 = rf(ctx, baseURL, gatewayID, resource, principalSub, resumeURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConnectService_ChainURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChainURL'
type ConnectService_ChainURL_Call struct {
	*mock.Call
}

// ChainURL is a helper method to define mock.On call
//   - ctx context.Context
//   - baseURL string
//   - gatewayID ids.ID[ids.GatewayKind]
//   - resource string
//   - principalSub string
//   - resumeURL string
func (_e *ConnectService_Expecter) ChainURL(ctx interface{}, baseURL interface{}, gatewayID interface{}, resource interface{}, principalSub interface{}, resumeURL interface{}) *ConnectService_ChainURL_Call {
	return &ConnectService_ChainURL_Call{Call: _e.mock.On("ChainURL", ctx, baseURL, gatewayID, resource, principalSub, resumeURL)}
}

func (_c *ConnectService_ChainURL_Call) Run(run func(ctx context.Context, baseURL string, gatewayID ids.ID[ids.GatewayKind], resource string, principalSub string, resumeURL string)) *ConnectService_ChainURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(ids.ID[ids.GatewayKind]), args[3].(string), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *ConnectService_ChainURL_Call) Return(_a0 string, _a1 error) *ConnectService_ChainURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConnectService_ChainURL_Call) RunAndReturn(run func(context.Context, string, ids.ID[ids.GatewayKind], string, string, string) (string, error)) *ConnectService_ChainURL_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTicket provides a mock function with given fields: ctx, gatewayID, principalSub, consumerPath
func (_m *ConnectService) CreateTicket(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], principalSub string, consumerPath string) (string, error) {
	ret := _m.Called(ctx, gatewayID, principalSub, consumerPath)

	if len(ret) == 0 {
		panic("no return value specified for CreateTicket")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], string, string) (string, error)); ok {
		return rf(ctx, gatewayID, principalSub, consumerPath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], string, string) string); ok {
		r0 = rf(ctx, gatewayID, principalSub, consumerPath)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.GatewayKind], string, string) error); ok {
		r1 = rf(ctx, gatewayID, principalSub, consumerPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConnectService_CreateTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTicket'
type ConnectService_CreateTicket_Call struct {
	*mock.Call
}

// CreateTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - principalSub string
//   - consumerPath string
func (_e *ConnectService_Expecter) CreateTicket(ctx interface{}, gatewayID interface{}, principalSub interface{}, consumerPath interface{}) *ConnectService_CreateTicket_Call {
	return &ConnectService_CreateTicket_Call{Call: _e.mock.On("CreateTicket", ctx, gatewayID, principalSub, consumerPath)}
}

func (_c *ConnectService_CreateTicket_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], principalSub string, consumerPath string)) *ConnectService_CreateTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ConnectService_CreateTicket_Call) Return(_a0 string, _a1 error) *ConnectService_CreateTicket_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConnectService_CreateTicket_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], string, string) (string, error)) *ConnectService_CreateTicket_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function with given fields: ctx, ticketID, provider
func (_m *ConnectService) Disconnect(ctx context.Context, ticketID string, provider string) error {
	ret := _m.Called(ctx, ticketID, provider)

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, ticketID, provider)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConnectService_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type ConnectService_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID string
//   - provider string
func (_e *ConnectService_Expecter) Disconnect(ctx interface{}, ticketID interface{}, provider interface{}) *ConnectService_Disconnect_Call {
	return &ConnectService_Disconnect_Call{Call: _e.mock.On("Disconnect", ctx, ticketID, provider)}
}

func (_c *ConnectService_Disconnect_Call) Run(run func(ctx context.Context, ticketID string, provider string)) *ConnectService_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ConnectService_Disconnect_Call) Return(_a0 error) *ConnectService_Disconnect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectService_Disconnect_Call) RunAndReturn(run func(context.Context, string, string) error) *ConnectService_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// Page provides a mock function with given fields: ctx, ticketID
func (_m *ConnectService) Page(ctx context.Context, ticketID string) (*oauth.ConnectPage, error) {
	ret := _m.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for Page")
	}

	var r0 *oauth.ConnectPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*oauth.ConnectPage, error)); ok {
		return rf(ctx, ticketID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *oauth.ConnectPage); ok {
		r0 = rf(ctx, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.ConnectPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ticketID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConnectService_Page_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Page'
type ConnectService_Page_Call struct {
	*mock.Call
}

// Page is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID string
func (_e *ConnectService_Expecter) Page(ctx interface{}, ticketID interface{}) *ConnectService_Page_Call {
	return &ConnectService_Page_Call{Call: _e.mock.On("Page", ctx, ticketID)}
}

func (_c *ConnectService_Page_Call) Run(run func(ctx context.Context, ticketID string)) *ConnectService_Page_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ConnectService_Page_Call) Return(_a0 *oauth.ConnectPage, _a1 error) *ConnectService_Page_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConnectService_Page_Call) RunAndReturn(run func(context.Context, string) (*oauth.ConnectPage, error)) *ConnectService_Page_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshAuth provides a mock function with given fields: ctx, gatewayID, reg
func (_m *ConnectService) RefreshAuth(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], reg *registry.Registry) (*registry.MCPAuth, error) {
	ret := _m.Called(ctx, gatewayID, reg)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAuth")
	}

	var r0 *registry.MCPAuth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], *registry.Registry) (*registry.MCPAuth, error)); ok {
		return rf(ctx, gatewayID, reg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], *registry.Registry) *registry.MCPAuth); ok {
		r0 = rf(ctx, gatewayID, reg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.MCPAuth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.GatewayKind], *registry.Registry) error); ok {
		r1 = rf(ctx, gatewayID, reg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConnectService_RefreshAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAuth'
type ConnectService_RefreshAuth_Call struct {
	*mock.Call
}

// RefreshAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - reg *registry.Registry
func (_e *ConnectService_Expecter) RefreshAuth(ctx interface{}, gatewayID interface{}, reg interface{}) *ConnectService_RefreshAuth_Call {
	return &ConnectService_RefreshAuth_Call{Call: _e.mock.On("RefreshAuth", ctx, gatewayID, reg)}
}

func (_c *ConnectService_RefreshAuth_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], reg *registry.Registry)) *ConnectService_RefreshAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].(*registry.Registry))
	})
	return _c
}

func (_c *ConnectService_RefreshAuth_Call) Return(_a0 *registry.MCPAuth, _a1 error) *ConnectService_RefreshAuth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConnectService_RefreshAuth_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], *registry.Registry) (*registry.MCPAuth, error)) *ConnectService_RefreshAuth_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx, baseURL, ticketID, provider
func (_m *ConnectService) Start(ctx context.Context, baseURL string, ticketID string, provider string) (string, error) {
	ret := _m.Called(ctx, baseURL, ticketID, provider)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, baseURL, ticketID, provider)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, baseURL, ticketID, provider)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, baseURL, ticketID, provider)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConnectService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type ConnectService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - baseURL string
//   - ticketID string
//   - provider string
func (_e *ConnectService_Expecter) Start(ctx interface{}, baseURL interface{}, ticketID interface{}, provider interface{}) *ConnectService_Start_Call {
	return &ConnectService_Start_Call{Call: _e.mock.On("Start", ctx, baseURL, ticketID, provider)}
}

func (_c *ConnectService_Start_Call) Run(run func(ctx context.Context, baseURL string, ticketID string, provider string)) *ConnectService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ConnectService_Start_Call) Return(_a0 string, _a1 error) *ConnectService_Start_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConnectService_Start_Call) RunAndReturn(run func(context.Context, string, string, string) (string, error)) *ConnectService_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewConnectService creates a new instance of ConnectService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnectService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConnectService {
	mock := &ConnectService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
