// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	ids "github.com/NeuralTrust/TrustGate/pkg/domain/ids"
	mock "github.com/stretchr/testify/mock"
)

// APIKeyConnectService is an autogenerated mock type for the APIKeyConnectService type
type APIKeyConnectService struct {
	mock.Mock
}

type APIKeyConnectService_Expecter struct {
	mock *mock.Mock
}

func (_m *APIKeyConnectService) EXPECT() *APIKeyConnectService_Expecter {
	return &APIKeyConnectService_Expecter{mock: &_m.Mock}
}

// CreateTicket provides a mock function with given fields: ctx, gatewayID, slug, rawKey
func (_m *APIKeyConnectService) CreateTicket(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], slug string, rawKey string) (string, error) {
	ret := _m.Called(ctx, gatewayID, slug, rawKey)

	if len(ret) == 0 {
		panic("no return value specified for CreateTicket")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], string, string) (string, error)); ok {
		return rf(ctx, gatewayID, slug, rawKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], string, string) string); ok {
		r0 = rf(ctx, gatewayID, slug, rawKey)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.GatewayKind], string, string) error); ok {
		r1 = rf(ctx, gatewayID, slug, rawKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// APIKeyConnectService_CreateTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTicket'
type APIKeyConnectService_CreateTicket_Call struct {
	*mock.Call
}

// CreateTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - slug string
//   - rawKey string
func (_e *APIKeyConnectService_Expecter) CreateTicket(ctx interface{}, gatewayID interface{}, slug interface{}, rawKey interface{}) *APIKeyConnectService_CreateTicket_Call {
	return &APIKeyConnectService_CreateTicket_Call{Call: _e.mock.On("CreateTicket", ctx, gatewayID, slug, rawKey)}
}

func (_c *APIKeyConnectService_CreateTicket_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], slug string, rawKey string)) *APIKeyConnectService_CreateTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *APIKeyConnectService_CreateTicket_Call) Return(_a0 string, _a1 error) *APIKeyConnectService_CreateTicket_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *APIKeyConnectService_CreateTicket_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], string, string) (string, error)) *APIKeyConnectService_CreateTicket_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateTarget provides a mock function with given fields: ctx, gatewayID, slug
func (_m *APIKeyConnectService) ValidateTarget(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], slug string) error {
	ret := _m.Called(ctx, gatewayID, slug)

	if len(ret) == 0 {
		panic("no return value specified for ValidateTarget")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], string) error); ok {
		r0 = rf(ctx, gatewayID, slug)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// APIKeyConnectService_ValidateTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateTarget'
type APIKeyConnectService_ValidateTarget_Call struct {
	*mock.Call
}

// ValidateTarget is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - slug string
func (_e *APIKeyConnectService_Expecter) ValidateTarget(ctx interface{}, gatewayID interface{}, slug interface{}) *APIKeyConnectService_ValidateTarget_Call {
	return &APIKeyConnectService_ValidateTarget_Call{Call: _e.mock.On("ValidateTarget", ctx, gatewayID, slug)}
}

func (_c *APIKeyConnectService_ValidateTarget_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], slug string)) *APIKeyConnectService_ValidateTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].(string))
	})
	return _c
}

func (_c *APIKeyConnectService_ValidateTarget_Call) Return(_a0 error) *APIKeyConnectService_ValidateTarget_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *APIKeyConnectService_ValidateTarget_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], string) error) *APIKeyConnectService_ValidateTarget_Call {
	_c.Call.Return(run)
	return _c
}

// NewAPIKeyConnectService creates a new instance of APIKeyConnectService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPIKeyConnectService(t interface {
	mock.TestingT
	Cleanup(func())
}) *APIKeyConnectService {
	mock := &APIKeyConnectService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
