// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	oauth "github.com/NeuralTrust/AgentGateway/pkg/app/oauth"
	mock "github.com/stretchr/testify/mock"
)

// UpstreamRegistrar is an autogenerated mock type for the UpstreamRegistrar type
type UpstreamRegistrar struct {
	mock.Mock
}

type UpstreamRegistrar_Expecter struct {
	mock *mock.Mock
}

func (_m *UpstreamRegistrar) EXPECT() *UpstreamRegistrar_Expecter {
	return &UpstreamRegistrar_Expecter{mock: &_m.Mock}
}

// CachedClient provides a mock function with given fields: ctx, key
func (_m *UpstreamRegistrar) CachedClient(ctx context.Context, key string) (*oauth.RegisteredClient, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for CachedClient")
	}

	var r0 *oauth.RegisteredClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*oauth.RegisteredClient, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *oauth.RegisteredClient); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.RegisteredClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpstreamRegistrar_CachedClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CachedClient'
type UpstreamRegistrar_CachedClient_Call struct {
	*mock.Call
}

// CachedClient is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *UpstreamRegistrar_Expecter) CachedClient(ctx interface{}, key interface{}) *UpstreamRegistrar_CachedClient_Call {
	return &UpstreamRegistrar_CachedClient_Call{Call: _e.mock.On("CachedClient", ctx, key)}
}

func (_c *UpstreamRegistrar_CachedClient_Call) Run(run func(ctx context.Context, key string)) *UpstreamRegistrar_CachedClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UpstreamRegistrar_CachedClient_Call) Return(_a0 *oauth.RegisteredClient, _a1 error) *UpstreamRegistrar_CachedClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UpstreamRegistrar_CachedClient_Call) RunAndReturn(run func(context.Context, string) (*oauth.RegisteredClient, error)) *UpstreamRegistrar_CachedClient_Call {
	_c.Call.Return(run)
	return _c
}

// Discover provides a mock function with given fields: ctx, upstreamURL
func (_m *UpstreamRegistrar) Discover(ctx context.Context, upstreamURL string) (*oauth.UpstreamAuthServer, error) {
	ret := _m.Called(ctx, upstreamURL)

	if len(ret) == 0 {
		panic("no return value specified for Discover")
	}

	var r0 *oauth.UpstreamAuthServer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*oauth.UpstreamAuthServer, error)); ok {
		return rf(ctx, upstreamURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *oauth.UpstreamAuthServer); ok {
		r0 = rf(ctx, upstreamURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.UpstreamAuthServer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, upstreamURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpstreamRegistrar_Discover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Discover'
type UpstreamRegistrar_Discover_Call struct {
	*mock.Call
}

// Discover is a helper method to define mock.On call
//   - ctx context.Context
//   - upstreamURL string
func (_e *UpstreamRegistrar_Expecter) Discover(ctx interface{}, upstreamURL interface{}) *UpstreamRegistrar_Discover_Call {
	return &UpstreamRegistrar_Discover_Call{Call: _e.mock.On("Discover", ctx, upstreamURL)}
}

func (_c *UpstreamRegistrar_Discover_Call) Run(run func(ctx context.Context, upstreamURL string)) *UpstreamRegistrar_Discover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UpstreamRegistrar_Discover_Call) Return(_a0 *oauth.UpstreamAuthServer, _a1 error) *UpstreamRegistrar_Discover_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UpstreamRegistrar_Discover_Call) RunAndReturn(run func(context.Context, string) (*oauth.UpstreamAuthServer, error)) *UpstreamRegistrar_Discover_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureClient provides a mock function with given fields: ctx, key, meta, redirectURI
func (_m *UpstreamRegistrar) EnsureClient(ctx context.Context, key string, meta *oauth.UpstreamAuthServer, redirectURI string) (*oauth.RegisteredClient, error) {
	ret := _m.Called(ctx, key, meta, redirectURI)

	if len(ret) == 0 {
		panic("no return value specified for EnsureClient")
	}

	var r0 *oauth.RegisteredClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *oauth.UpstreamAuthServer, string) (*oauth.RegisteredClient, error)); ok {
		return rf(ctx, key, meta, redirectURI)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *oauth.UpstreamAuthServer, string) *oauth.RegisteredClient); ok {
		r0 = rf(ctx, key, meta, redirectURI)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.RegisteredClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *oauth.UpstreamAuthServer, string) error); ok {
		r1 = rf(ctx, key, meta, redirectURI)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpstreamRegistrar_EnsureClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureClient'
type UpstreamRegistrar_EnsureClient_Call struct {
	*mock.Call
}

// EnsureClient is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - meta *oauth.UpstreamAuthServer
//   - redirectURI string
func (_e *UpstreamRegistrar_Expecter) EnsureClient(ctx interface{}, key interface{}, meta interface{}, redirectURI interface{}) *UpstreamRegistrar_EnsureClient_Call {
	return &UpstreamRegistrar_EnsureClient_Call{Call: _e.mock.On("EnsureClient", ctx, key, meta, redirectURI)}
}

func (_c *UpstreamRegistrar_EnsureClient_Call) Run(run func(ctx context.Context, key string, meta *oauth.UpstreamAuthServer, redirectURI string)) *UpstreamRegistrar_EnsureClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*oauth.UpstreamAuthServer), args[3].(string))
	})
	return _c
}

func (_c *UpstreamRegistrar_EnsureClient_Call) Return(_a0 *oauth.RegisteredClient, _a1 error) *UpstreamRegistrar_EnsureClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UpstreamRegistrar_EnsureClient_Call) RunAndReturn(run func(context.Context, string, *oauth.UpstreamAuthServer, string) (*oauth.RegisteredClient, error)) *UpstreamRegistrar_EnsureClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewUpstreamRegistrar creates a new instance of UpstreamRegistrar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpstreamRegistrar(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpstreamRegistrar {
	mock := &UpstreamRegistrar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
