// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	oauth "github.com/NeuralTrust/TrustGate/pkg/app/oauth"
	registry "github.com/NeuralTrust/TrustGate/pkg/domain/registry"
	mock "github.com/stretchr/testify/mock"
)

// ProviderClient is an autogenerated mock type for the ProviderClient type
type ProviderClient struct {
	mock.Mock
}

type ProviderClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ProviderClient) EXPECT() *ProviderClient_Expecter {
	return &ProviderClient_Expecter{mock: &_m.Mock}
}

// AuthorizeURL provides a mock function with given fields: cfg, redirectURI, state, challenge
func (_m *ProviderClient) AuthorizeURL(cfg *registry.MCPAuth, redirectURI string, state string, challenge string) string {
	ret := _m.Called(cfg, redirectURI, state, challenge)

	if len(ret) == 0 {
		panic("no return value specified for AuthorizeURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(*registry.MCPAuth, string, string, string) string); ok {
		r0 = rf(cfg, redirectURI, state, challenge)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ProviderClient_AuthorizeURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizeURL'
type ProviderClient_AuthorizeURL_Call struct {
	*mock.Call
}

// AuthorizeURL is a helper method to define mock.On call
//   - cfg *registry.MCPAuth
//   - redirectURI string
//   - state string
//   - challenge string
func (_e *ProviderClient_Expecter) AuthorizeURL(cfg interface{}, redirectURI interface{}, state interface{}, challenge interface{}) *ProviderClient_AuthorizeURL_Call {
	return &ProviderClient_AuthorizeURL_Call{Call: _e.mock.On("AuthorizeURL", cfg, redirectURI, state, challenge)}
}

func (_c *ProviderClient_AuthorizeURL_Call) Run(run func(cfg *registry.MCPAuth, redirectURI string, state string, challenge string)) *ProviderClient_AuthorizeURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*registry.MCPAuth), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *ProviderClient_AuthorizeURL_Call) Return(_a0 string) *ProviderClient_AuthorizeURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProviderClient_AuthorizeURL_Call) RunAndReturn(run func(*registry.MCPAuth, string, string, string) string) *ProviderClient_AuthorizeURL_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangeCode provides a mock function with given fields: ctx, cfg, code, redirectURI, verifier
func (_m *ProviderClient) ExchangeCode(ctx context.Context, cfg *registry.MCPAuth, code string, redirectURI string, verifier string) (*oauth.ProviderToken, error) {
	ret := _m.Called(ctx, cfg, code, redirectURI, verifier)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeCode")
	}

	var r0 *oauth.ProviderToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *registry.MCPAuth, string, string, string) (*oauth.ProviderToken, error)); ok {
		return rf(ctx, cfg, code, redirectURI, verifier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *registry.MCPAuth, string, string, string) *oauth.ProviderToken); ok {
		r0 = rf(ctx, cfg, code, redirectURI, verifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.ProviderToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *registry.MCPAuth, string, string, string) error); ok {
		r1 = rf(ctx, cfg, code, redirectURI, verifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProviderClient_ExchangeCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeCode'
type ProviderClient_ExchangeCode_Call struct {
	*mock.Call
}

// ExchangeCode is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg *registry.MCPAuth
//   - code string
//   - redirectURI string
//   - verifier string
func (_e *ProviderClient_Expecter) ExchangeCode(ctx interface{}, cfg interface{}, code interface{}, redirectURI interface{}, verifier interface{}) *ProviderClient_ExchangeCode_Call {
	return &ProviderClient_ExchangeCode_Call{Call: _e.mock.On("ExchangeCode", ctx, cfg, code, redirectURI, verifier)}
}

func (_c *ProviderClient_ExchangeCode_Call) Run(run func(ctx context.Context, cfg *registry.MCPAuth, code string, redirectURI string, verifier string)) *ProviderClient_ExchangeCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*registry.MCPAuth), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *ProviderClient_ExchangeCode_Call) Return(_a0 *oauth.ProviderToken, _a1 error) *ProviderClient_ExchangeCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProviderClient_ExchangeCode_Call) RunAndReturn(run func(context.Context, *registry.MCPAuth, string, string, string) (*oauth.ProviderToken, error)) *ProviderClient_ExchangeCode_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, cfg, refreshToken
func (_m *ProviderClient) Refresh(ctx context.Context, cfg *registry.MCPAuth, refreshToken string) (*oauth.ProviderToken, error) {
	ret := _m.Called(ctx, cfg, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *oauth.ProviderToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *registry.MCPAuth, string) (*oauth.ProviderToken, error)); ok {
		return rf(ctx, cfg, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *registry.MCPAuth, string) *oauth.ProviderToken); ok {
		r0 = rf(ctx, cfg, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.ProviderToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *registry.MCPAuth, string) error); ok {
		r1 = rf(ctx, cfg, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProviderClient_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type ProviderClient_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg *registry.MCPAuth
//   - refreshToken string
func (_e *ProviderClient_Expecter) Refresh(ctx interface{}, cfg interface{}, refreshToken interface{}) *ProviderClient_Refresh_Call {
	return &ProviderClient_Refresh_Call{Call: _e.mock.On("Refresh", ctx, cfg, refreshToken)}
}

func (_c *ProviderClient_Refresh_Call) Run(run func(ctx context.Context, cfg *registry.MCPAuth, refreshToken string)) *ProviderClient_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*registry.MCPAuth), args[2].(string))
	})
	return _c
}

func (_c *ProviderClient_Refresh_Call) Return(_a0 *oauth.ProviderToken, _a1 error) *ProviderClient_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProviderClient_Refresh_Call) RunAndReturn(run func(context.Context, *registry.MCPAuth, string) (*oauth.ProviderToken, error)) *ProviderClient_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewProviderClient creates a new instance of ProviderClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProviderClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProviderClient {
	mock := &ProviderClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
