// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	apikey "github.com/NeuralTrust/TrustGate/pkg/domain/iam/apikey"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Finder is an autogenerated mock type for the Finder type
type Finder struct {
	mock.Mock
}

type Finder_Expecter struct {
	mock *mock.Mock
}

func (_m *Finder) EXPECT() *Finder_Expecter {
	return &Finder_Expecter{mock: &_m.Mock}
}

// Find provides a mock function with given fields: ctx, key
func (_m *Finder) Find(ctx context.Context, key string) (*apikey.APIKey, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *apikey.APIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*apikey.APIKey, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *apikey.APIKey); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apikey.APIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Finder_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type Finder_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *Finder_Expecter) Find(ctx interface{}, key interface{}) *Finder_Find_Call {
	return &Finder_Find_Call{Call: _e.mock.On("Find", ctx, key)}
}

func (_c *Finder_Find_Call) Run(run func(ctx context.Context, key string)) *Finder_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Finder_Find_Call) Return(_a0 *apikey.APIKey, _a1 error) *Finder_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Finder_Find_Call) RunAndReturn(run func(context.Context, string) (*apikey.APIKey, error)) *Finder_Find_Call {
	_c.Call.Return(run)
	return _c
}

// NewFinder creates a new instance of Finder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Finder {
	mock := &Finder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
