// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	firewall "github.com/NeuralTrust/TrustGate/pkg/infra/firewall"
	mock "github.com/stretchr/testify/mock"
)

// ClientFactory is an autogenerated mock type for the ClientFactory type
type ClientFactory struct {
	mock.Mock
}

type ClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientFactory) EXPECT() *ClientFactory_Expecter {
	return &ClientFactory_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: provider
func (_m *ClientFactory) Get(provider string) (firewall.Client, error) {
	ret := _m.Called(provider)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 firewall.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (firewall.Client, error)); ok {
		return rf(provider)
	}
	if rf, ok := ret.Get(0).(func(string) firewall.Client); ok {
		r0 = rf(provider)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(firewall.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(provider)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientFactory_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ClientFactory_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - provider string
func (_e *ClientFactory_Expecter) Get(provider interface{}) *ClientFactory_Get_Call {
	return &ClientFactory_Get_Call{Call: _e.mock.On("Get", provider)}
}

func (_c *ClientFactory_Get_Call) Run(run func(provider string)) *ClientFactory_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ClientFactory_Get_Call) Return(_a0 firewall.Client, _a1 error) *ClientFactory_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientFactory_Get_Call) RunAndReturn(run func(string) (firewall.Client, error)) *ClientFactory_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientFactory creates a new instance of ClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientFactory {
	mock := &ClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
