// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	tls "github.com/NeuralTrust/TrustGate/pkg/infra/tls"
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// CertWriter is an autogenerated mock type for the CertWriter type
type CertWriter struct {
	mock.Mock
}

type CertWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *CertWriter) EXPECT() *CertWriter_Expecter {
	return &CertWriter_Expecter{mock: &_m.Mock}
}

// DeleteAllGatewayCerts provides a mock function with given fields: gatewayID
func (_m *CertWriter) DeleteAllGatewayCerts(gatewayID uuid.UUID) error {
	ret := _m.Called(gatewayID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllGatewayCerts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(gatewayID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CertWriter_DeleteAllGatewayCerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllGatewayCerts'
type CertWriter_DeleteAllGatewayCerts_Call struct {
	*mock.Call
}

// DeleteAllGatewayCerts is a helper method to define mock.On call
//   - gatewayID uuid.UUID
func (_e *CertWriter_Expecter) DeleteAllGatewayCerts(gatewayID interface{}) *CertWriter_DeleteAllGatewayCerts_Call {
	return &CertWriter_DeleteAllGatewayCerts_Call{Call: _e.mock.On("DeleteAllGatewayCerts", gatewayID)}
}

func (_c *CertWriter_DeleteAllGatewayCerts_Call) Run(run func(gatewayID uuid.UUID)) *CertWriter_DeleteAllGatewayCerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *CertWriter_DeleteAllGatewayCerts_Call) Return(_a0 error) *CertWriter_DeleteAllGatewayCerts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CertWriter_DeleteAllGatewayCerts_Call) RunAndReturn(run func(uuid.UUID) error) *CertWriter_DeleteAllGatewayCerts_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCerts provides a mock function with given fields: gatewayID, host
func (_m *CertWriter) DeleteCerts(gatewayID uuid.UUID, host string) error {
	ret := _m.Called(gatewayID, host)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCerts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) error); ok {
		r0 = rf(gatewayID, host)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CertWriter_DeleteCerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCerts'
type CertWriter_DeleteCerts_Call struct {
	*mock.Call
}

// DeleteCerts is a helper method to define mock.On call
//   - gatewayID uuid.UUID
//   - host string
func (_e *CertWriter_Expecter) DeleteCerts(gatewayID interface{}, host interface{}) *CertWriter_DeleteCerts_Call {
	return &CertWriter_DeleteCerts_Call{Call: _e.mock.On("DeleteCerts", gatewayID, host)}
}

func (_c *CertWriter_DeleteCerts_Call) Run(run func(gatewayID uuid.UUID, host string)) *CertWriter_DeleteCerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string))
	})
	return _c
}

func (_c *CertWriter_DeleteCerts_Call) Return(_a0 error) *CertWriter_DeleteCerts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CertWriter_DeleteCerts_Call) RunAndReturn(run func(uuid.UUID, string) error) *CertWriter_DeleteCerts_Call {
	_c.Call.Return(run)
	return _c
}

// WriteCerts provides a mock function with given fields: gatewayID, host, caCert, clientCert, clientKey
func (_m *CertWriter) WriteCerts(gatewayID uuid.UUID, host string, caCert string, clientCert string, clientKey string) (*tls.CertPaths, error) {
	ret := _m.Called(gatewayID, host, caCert, clientCert, clientKey)

	if len(ret) == 0 {
		panic("no return value specified for WriteCerts")
	}

	var r0 *tls.CertPaths
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, string, string, string) (*tls.CertPaths, error)); ok {
		return rf(gatewayID, host, caCert, clientCert, clientKey)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, string, string, string) *tls.CertPaths); ok {
		r0 = rf(gatewayID, host, caCert, clientCert, clientKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tls.CertPaths)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string, string, string, string) error); ok {
		r1 = rf(gatewayID, host, caCert, clientCert, clientKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CertWriter_WriteCerts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteCerts'
type CertWriter_WriteCerts_Call struct {
	*mock.Call
}

// WriteCerts is a helper method to define mock.On call
//   - gatewayID uuid.UUID
//   - host string
//   - caCert string
//   - clientCert string
//   - clientKey string
func (_e *CertWriter_Expecter) WriteCerts(gatewayID interface{}, host interface{}, caCert interface{}, clientCert interface{}, clientKey interface{}) *CertWriter_WriteCerts_Call {
	return &CertWriter_WriteCerts_Call{Call: _e.mock.On("WriteCerts", gatewayID, host, caCert, clientCert, clientKey)}
}

func (_c *CertWriter_WriteCerts_Call) Run(run func(gatewayID uuid.UUID, host string, caCert string, clientCert string, clientKey string)) *CertWriter_WriteCerts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *CertWriter_WriteCerts_Call) Return(_a0 *tls.CertPaths, _a1 error) *CertWriter_WriteCerts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CertWriter_WriteCerts_Call) RunAndReturn(run func(uuid.UUID, string, string, string, string) (*tls.CertPaths, error)) *CertWriter_WriteCerts_Call {
	_c.Call.Return(run)
	return _c
}

// NewCertWriter creates a new instance of CertWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCertWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *CertWriter {
	mock := &CertWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
