server:
  admin_port: ${SERVER_ADMIN_PORT}
  metrics_port: ${SERVER_METRICS_PORT}
  proxy_port: ${SERVER_PROXY_PORT}
  base_domain: ${BASE_DOMAIN}

metrics:
  enabled: true
  enable_latency: true        # Basic latency metrics
  enable_upstream: true      # Upstream latency (high cardinality)
  enable_connections: true   # Connection tracking
  enable_per_route: true    # Per-route metrics (high cardinality)
  enable_detailed_status: true # Detailed status codes

database:
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT}
  user: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  name: ${DATABASE_NAME}
  ssl_mode: ${DATABASE_SSL_MODE}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ""
  db: ${REDIS_DB}

plugins:
  ignore_errors: true

tls:
  disabled: false
  enable_mtls: true
  disable_system_ca_pool: false
  ca_cert: ${TLS_CA_CERT}
  keys:
    public_key: ${TLS_KEYS_PUBLIC_KEY}
    private_key: ${TLS_KEYS_PRIVATE_KEY
  cipher_suites:
    - 4865
    - 4866
    - 4867
  curve_preferences:
    - 23
    - 24
    - 25
  min_version: TLS12
  max_version: TLS13


