server:
  admin_port: 8080
  metrics_port: 9090
  proxy_port: 8081
  base_domain: example.com

metrics:
  enabled: true
  enable_latency: true        # Basic latency metrics
  enable_upstream: true      # Upstream latency (high cardinality)
  enable_connections: true   # Connection tracking
  enable_per_route: true    # Per-route metrics (high cardinality)
  enable_detailed_status: true # Detailed status codes

database:
  host: localhost
  port: 5432
  user: trustgate
  password: ${DB_PASSWORD}
  dbname: trustgate
  ssl_mode: disable 

redis:
  host: localhost
  port: 6379
  db: 0
