providers:
  openai:
    base_url: "https://api.openai.com"
    endpoints:
      chat: "/v1/chat/completions"
      completions: "/v1/completions"
      embeddings: "/v1/embeddings"

  anthropic:
    base_url: "https://api.anthropic.com"
    endpoints:
      chat: "/v1/messages"

  mistral:
    base_url: "https://api.mistral.ai"
    endpoints:
      chat: "/v1/chat/completions"
      completions: "/v1/completions"

  llama:
    base_url: "https://api.llama.ai"
    endpoints:
      chat: "/v1/chat/completions"
      completions: "/v1/completions"
