providers:
  openai:
    name: openai
    base_url: "https://api.openai.com"
    endpoints:
      /v1/chat/completions:
        path: "/v1/chat/completions"
        schema:
          identifying_keys: ["messages", "model"]
          request_format:
            messages:
              type: array
              required: true
              path: messages
            model:
              type: string
              required: true
              path: model
            frequency_penalty:
              type: number
              required: false
              path: frequency_penalty
            logit_bias:
              type: object
              required: false
              path: logit_bias
            max_completion_tokens:
              type: integer
              required: false
              path: max_completion_tokens
            n:
              type: integer
              required: false
              path: n
            presence_penalty:
              type: number
              required: false
              path: presence_penalty
            response_format:
              type: object
              required: false
              path: response_format
            seed:
              type: integer
              required: false
              path: seed
            stop:
              type: array
              required: false
              path: stop
            temperature:
              type: number
              required: false
              path: temperature
            tools:
              type: array
              required: false
              path: tools
            tool_choice:
              type: object
              required: false
              path: tool_choice
            top_p:
              type: number
              required: false
              path: top_p
            user:
              type: string
              required: false
              path: user
            stream_options:
              type: object
              required: false
              path: stream_options
            stream:
              type: boolean
              required: false
              path: stream
      /v1/completions:
        path: "/v1/completions"
        schema:
          identifying_keys: ["prompt", "model"]
          request_format:
            model:
              type: string
              required: true
              path: model
            prompt:
              type: string
              required: true
              path: prompt
            frequency_penalty:
              type: number
              required: false
              path: frequency_penalty
            logit_bias:
              type: object
              required: false
              path: logit_bias
            max_tokens:
              type: integer
              required: false
              path: max_tokens
            n:
              type: integer
              required: false
              path: n
            presence_penalty:
              type: number
              required: false
              path: presence_penalty
            seed:
              type: integer
              required: false
              path: seed
            stop:
              type: array
              required: false
              path: stop
            temperature:
              type: number
              required: false
              path: temperature
            top_p:
              type: number
              required: false
              path: top_p
            user:
              type: string
              required: false
              path: user
      /v1/embeddings:
        path: "/v1/embeddings"
        schema:
          identifying_keys: ["input", "model"]
          request_format:
            model:
              type: string
              required: true
              path: model
            input:
              type: array
              required: true
              path: input
            encoding_format:
              type: string
              required: false
              path: encoding_format
            user:
              type: string
              required: false
              path: user

  anthropic:
    name: anthropic
    base_url: "https://api.anthropic.com"
    endpoints:
      /v1/messages:
        path: "/v1/messages"
        schema:
          identifying_keys: ["messages", "model"]
          request_format:
            model:
              type: string
              required: true
              path: model
              default: "claude-2"
            messages:
              type: array
              required: true
              path: messages
            max_tokens:
              type: integer
              required: true
              path: max_tokens
              default: 1024
            metadata:
              type: object
              required: false
              path: metadata
            stop_sequences:
              type: array
              required: false
              path: stop_sequences
            stream:
              type: boolean
              required: false
              path: stream
            system:
              type: string
              required: false
              path: system
            temperature:
              type: number
              required: false
              path: temperature
            tools:
              type: array
              required: false
              path: tools
            tool_choice:
              type: object
              required: false
              path: tool_choice

  mistral:
    name: mistral
    base_url: "https://api.mistral.ai"
    endpoints:
      /v1/chat/completions:
        path: "/v1/chat/completions"
        schema:
          identifying_keys: ["messages", "model"]
          request_format:
            model:
              type: string
              required: true
              path: model
            messages:
              type: array
              required: true
              path: messages
            temperature:
              type: number
              required: false
              path: temperature
            max_tokens:
              type: integer
              required: false
              path: max_tokens
            top_p:
              type: number
              required: false
              path: top_p
            random_seed:
              type: integer
              required: false
              path: random_seed
            safe_mode:
              type: boolean
              required: false
              path: safe_mode
      /v1/completions:
        path: "/v1/completions"
        schema:
          identifying_keys: ["prompt", "model"]
          request_format:
            model:
              type: string
              required: true
              path: model
            prompt:
              type: string
              required: true
              path: prompt
            # ... other fields same as chat

  llama:
    name: llama
    base_url: "https://api.llama.ai"
    endpoints:
      /v1/chat/completions:
        path: "/v1/chat/completions"
        schema:
          identifying_keys: ["messages", "model"]
          request_format:
            model:
              type: string
              required: true
              path: model
            messages:
              type: array
              required: true
              path: messages
            frequency_penalty:
              type: number
              required: false
              path: frequency_penalty
            max_tokens:
              type: integer
              required: false
              path: max_tokens
            presence_penalty:
              type: number
              required: false
              path: presence_penalty
            temperature:
              type: number
              required: false
              path: temperature
            top_p:
              type: number
              required: false
              path: top_p
            stop:
              type: array
              required: false
              path: stop
      /v1/completions:
        path: "/v1/completions"
        schema:
          identifying_keys: ["prompt", "model"]
          request_format:
            model:
              type: string
              required: true
              path: model
            prompt:
              type: string
              required: true
              path: prompt
            frequency_penalty:
              type: number
              required: false
              path: frequency_penalty
            logit_bias:
              type: object
              required: false
              path: logit_bias
            max_tokens:
              type: integer
              required: false
              path: max_tokens
            n:
              type: integer
              required: false
              path: n
            presence_penalty:
              type: number
              required: false
              path: presence_penalty
            seed:
              type: integer
              required: false
              path: seed
            stop:
              type: array
              required: false
              path: stop
            temperature:
              type: number
              required: false
              path: temperature
            top_p:
              type: number
              required: false
              path: top_p
            user:
              type: string
              required: false
              path: user
