// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	json "encoding/json"

	consumer "github.com/NeuralTrust/TrustGate/pkg/app/consumer"
	mcp "github.com/NeuralTrust/TrustGate/pkg/app/mcp"
	mock "github.com/stretchr/testify/mock"
)

// Composer is an autogenerated mock type for the Composer type
type Composer struct {
	mock.Mock
}

type Composer_Expecter struct {
	mock *mock.Mock
}

func (_m *Composer) EXPECT() *Composer_Expecter {
	return &Composer_Expecter{mock: &_m.Mock}
}

// CallTool provides a mock function with given fields: ctx, rc, call
func (_m *Composer) CallTool(ctx context.Context, rc *consumer.RoutableConsumer, call mcp.ToolCall) (json.RawMessage, error) {
	ret := _m.Called(ctx, rc, call)

	if len(ret) == 0 {
		panic("no return value specified for CallTool")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer, mcp.ToolCall) (json.RawMessage, error)); ok {
		return rf(ctx, rc, call)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer, mcp.ToolCall) json.RawMessage); ok {
		r0 = rf(ctx, rc, call)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *consumer.RoutableConsumer, mcp.ToolCall) error); ok {
		r1 = rf(ctx, rc, call)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Composer_CallTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallTool'
type Composer_CallTool_Call struct {
	*mock.Call
}

// CallTool is a helper method to define mock.On call
//   - ctx context.Context
//   - rc *consumer.RoutableConsumer
//   - call mcp.ToolCall
func (_e *Composer_Expecter) CallTool(ctx interface{}, rc interface{}, call interface{}) *Composer_CallTool_Call {
	return &Composer_CallTool_Call{Call: _e.mock.On("CallTool", ctx, rc, call)}
}

func (_c *Composer_CallTool_Call) Run(run func(ctx context.Context, rc *consumer.RoutableConsumer, call mcp.ToolCall)) *Composer_CallTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*consumer.RoutableConsumer), args[2].(mcp.ToolCall))
	})
	return _c
}

func (_c *Composer_CallTool_Call) Return(_a0 json.RawMessage, _a1 error) *Composer_CallTool_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Composer_CallTool_Call) RunAndReturn(run func(context.Context, *consumer.RoutableConsumer, mcp.ToolCall) (json.RawMessage, error)) *Composer_CallTool_Call {
	_c.Call.Return(run)
	return _c
}

// CancelTask provides a mock function with given fields: ctx, rc, handle
func (_m *Composer) CancelTask(ctx context.Context, rc *consumer.RoutableConsumer, handle string) (json.RawMessage, error) {
	ret := _m.Called(ctx, rc, handle)

	if len(ret) == 0 {
		panic("no return value specified for CancelTask")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer, string) (json.RawMessage, error)); ok {
		return rf(ctx, rc, handle)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer, string) json.RawMessage); ok {
		r0 = rf(ctx, rc, handle)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *consumer.RoutableConsumer, string) error); ok {
		r1 = rf(ctx, rc, handle)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Composer_CancelTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelTask'
type Composer_CancelTask_Call struct {
	*mock.Call
}

// CancelTask is a helper method to define mock.On call
//   - ctx context.Context
//   - rc *consumer.RoutableConsumer
//   - handle string
func (_e *Composer_Expecter) CancelTask(ctx interface{}, rc interface{}, handle interface{}) *Composer_CancelTask_Call {
	return &Composer_CancelTask_Call{Call: _e.mock.On("CancelTask", ctx, rc, handle)}
}

func (_c *Composer_CancelTask_Call) Run(run func(ctx context.Context, rc *consumer.RoutableConsumer, handle string)) *Composer_CancelTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*consumer.RoutableConsumer), args[2].(string))
	})
	return _c
}

func (_c *Composer_CancelTask_Call) Return(_a0 json.RawMessage, _a1 error) *Composer_CancelTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Composer_CancelTask_Call) RunAndReturn(run func(context.Context, *consumer.RoutableConsumer, string) (json.RawMessage, error)) *Composer_CancelTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrompt provides a mock function with given fields: ctx, rc, name, arguments
func (_m *Composer) GetPrompt(ctx context.Context, rc *consumer.RoutableConsumer, name string, arguments map[string]string) (json.RawMessage, error) {
	ret := _m.Called(ctx, rc, name, arguments)

	if len(ret) == 0 {
		panic("no return value specified for GetPrompt")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer, string, map[string]string) (json.RawMessage, error)); ok {
		return rf(ctx, rc, name, arguments)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer, string, map[string]string) json.RawMessage); ok {
		r0 = rf(ctx, rc, name, arguments)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *consumer.RoutableConsumer, string, map[string]string) error); ok {
		r1 = rf(ctx, rc, name, arguments)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Composer_GetPrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrompt'
type Composer_GetPrompt_Call struct {
	*mock.Call
}

// GetPrompt is a helper method to define mock.On call
//   - ctx context.Context
//   - rc *consumer.RoutableConsumer
//   - name string
//   - arguments map[string]string
func (_e *Composer_Expecter) GetPrompt(ctx interface{}, rc interface{}, name interface{}, arguments interface{}) *Composer_GetPrompt_Call {
	return &Composer_GetPrompt_Call{Call: _e.mock.On("GetPrompt", ctx, rc, name, arguments)}
}

func (_c *Composer_GetPrompt_Call) Run(run func(ctx context.Context, rc *consumer.RoutableConsumer, name string, arguments map[string]string)) *Composer_GetPrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*consumer.RoutableConsumer), args[2].(string), args[3].(map[string]string))
	})
	return _c
}

func (_c *Composer_GetPrompt_Call) Return(_a0 json.RawMessage, _a1 error) *Composer_GetPrompt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Composer_GetPrompt_Call) RunAndReturn(run func(context.Context, *consumer.RoutableConsumer, string, map[string]string) (json.RawMessage, error)) *Composer_GetPrompt_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function with given fields: ctx, rc, handle
func (_m *Composer) GetTask(ctx context.Context, rc *consumer.RoutableConsumer, handle string) (json.RawMessage, error) {
	ret := _m.Called(ctx, rc, handle)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer, string) (json.RawMessage, error)); ok {
		return rf(ctx, rc, handle)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer, string) json.RawMessage); ok {
		r0 = rf(ctx, rc, handle)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *consumer.RoutableConsumer, string) error); ok {
		r1 = rf(ctx, rc, handle)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Composer_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type Composer_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - rc *consumer.RoutableConsumer
//   - handle string
func (_e *Composer_Expecter) GetTask(ctx interface{}, rc interface{}, handle interface{}) *Composer_GetTask_Call {
	return &Composer_GetTask_Call{Call: _e.mock.On("GetTask", ctx, rc, handle)}
}

func (_c *Composer_GetTask_Call) Run(run func(ctx context.Context, rc *consumer.RoutableConsumer, handle string)) *Composer_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*consumer.RoutableConsumer), args[2].(string))
	})
	return _c
}

func (_c *Composer_GetTask_Call) Return(_a0 json.RawMessage, _a1 error) *Composer_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Composer_GetTask_Call) RunAndReturn(run func(context.Context, *consumer.RoutableConsumer, string) (json.RawMessage, error)) *Composer_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// ListPrompts provides a mock function with given fields: ctx, rc
func (_m *Composer) ListPrompts(ctx context.Context, rc *consumer.RoutableConsumer) ([]mcp.Prompt, error) {
	ret := _m.Called(ctx, rc)

	if len(ret) == 0 {
		panic("no return value specified for ListPrompts")
	}

	var r0 []mcp.Prompt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer) ([]mcp.Prompt, error)); ok {
		return rf(ctx, rc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer) []mcp.Prompt); ok {
		r0 = rf(ctx, rc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]mcp.Prompt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *consumer.RoutableConsumer) error); ok {
		r1 = rf(ctx, rc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Composer_ListPrompts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPrompts'
type Composer_ListPrompts_Call struct {
	*mock.Call
}

// ListPrompts is a helper method to define mock.On call
//   - ctx context.Context
//   - rc *consumer.RoutableConsumer
func (_e *Composer_Expecter) ListPrompts(ctx interface{}, rc interface{}) *Composer_ListPrompts_Call {
	return &Composer_ListPrompts_Call{Call: _e.mock.On("ListPrompts", ctx, rc)}
}

func (_c *Composer_ListPrompts_Call) Run(run func(ctx context.Context, rc *consumer.RoutableConsumer)) *Composer_ListPrompts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*consumer.RoutableConsumer))
	})
	return _c
}

func (_c *Composer_ListPrompts_Call) Return(_a0 []mcp.Prompt, _a1 error) *Composer_ListPrompts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Composer_ListPrompts_Call) RunAndReturn(run func(context.Context, *consumer.RoutableConsumer) ([]mcp.Prompt, error)) *Composer_ListPrompts_Call {
	_c.Call.Return(run)
	return _c
}

// ListResourceTemplates provides a mock function with given fields: ctx, rc
func (_m *Composer) ListResourceTemplates(ctx context.Context, rc *consumer.RoutableConsumer) ([]mcp.ResourceTemplate, error) {
	ret := _m.Called(ctx, rc)

	if len(ret) == 0 {
		panic("no return value specified for ListResourceTemplates")
	}

	var r0 []mcp.ResourceTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer) ([]mcp.ResourceTemplate, error)); ok {
		return rf(ctx, rc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer) []mcp.ResourceTemplate); ok {
		r0 = rf(ctx, rc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]mcp.ResourceTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *consumer.RoutableConsumer) error); ok {
		r1 = rf(ctx, rc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Composer_ListResourceTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListResourceTemplates'
type Composer_ListResourceTemplates_Call struct {
	*mock.Call
}

// ListResourceTemplates is a helper method to define mock.On call
//   - ctx context.Context
//   - rc *consumer.RoutableConsumer
func (_e *Composer_Expecter) ListResourceTemplates(ctx interface{}, rc interface{}) *Composer_ListResourceTemplates_Call {
	return &Composer_ListResourceTemplates_Call{Call: _e.mock.On("ListResourceTemplates", ctx, rc)}
}

func (_c *Composer_ListResourceTemplates_Call) Run(run func(ctx context.Context, rc *consumer.RoutableConsumer)) *Composer_ListResourceTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*consumer.RoutableConsumer))
	})
	return _c
}

func (_c *Composer_ListResourceTemplates_Call) Return(_a0 []mcp.ResourceTemplate, _a1 error) *Composer_ListResourceTemplates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Composer_ListResourceTemplates_Call) RunAndReturn(run func(context.Context, *consumer.RoutableConsumer) ([]mcp.ResourceTemplate, error)) *Composer_ListResourceTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// ListResources provides a mock function with given fields: ctx, rc
func (_m *Composer) ListResources(ctx context.Context, rc *consumer.RoutableConsumer) ([]mcp.Resource, error) {
	ret := _m.Called(ctx, rc)

	if len(ret) == 0 {
		panic("no return value specified for ListResources")
	}

	var r0 []mcp.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer) ([]mcp.Resource, error)); ok {
		return rf(ctx, rc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer) []mcp.Resource); ok {
		r0 = rf(ctx, rc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]mcp.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *consumer.RoutableConsumer) error); ok {
		r1 = rf(ctx, rc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Composer_ListResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListResources'
type Composer_ListResources_Call struct {
	*mock.Call
}

// ListResources is a helper method to define mock.On call
//   - ctx context.Context
//   - rc *consumer.RoutableConsumer
func (_e *Composer_Expecter) ListResources(ctx interface{}, rc interface{}) *Composer_ListResources_Call {
	return &Composer_ListResources_Call{Call: _e.mock.On("ListResources", ctx, rc)}
}

func (_c *Composer_ListResources_Call) Run(run func(ctx context.Context, rc *consumer.RoutableConsumer)) *Composer_ListResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*consumer.RoutableConsumer))
	})
	return _c
}

func (_c *Composer_ListResources_Call) Return(_a0 []mcp.Resource, _a1 error) *Composer_ListResources_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Composer_ListResources_Call) RunAndReturn(run func(context.Context, *consumer.RoutableConsumer) ([]mcp.Resource, error)) *Composer_ListResources_Call {
	_c.Call.Return(run)
	return _c
}

// ListTools provides a mock function with given fields: ctx, rc
func (_m *Composer) ListTools(ctx context.Context, rc *consumer.RoutableConsumer) ([]mcp.Tool, error) {
	ret := _m.Called(ctx, rc)

	if len(ret) == 0 {
		panic("no return value specified for ListTools")
	}

	var r0 []mcp.Tool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer) ([]mcp.Tool, error)); ok {
		return rf(ctx, rc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer) []mcp.Tool); ok {
		r0 = rf(ctx, rc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]mcp.Tool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *consumer.RoutableConsumer) error); ok {
		r1 = rf(ctx, rc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Composer_ListTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTools'
type Composer_ListTools_Call struct {
	*mock.Call
}

// ListTools is a helper method to define mock.On call
//   - ctx context.Context
//   - rc *consumer.RoutableConsumer
func (_e *Composer_Expecter) ListTools(ctx interface{}, rc interface{}) *Composer_ListTools_Call {
	return &Composer_ListTools_Call{Call: _e.mock.On("ListTools", ctx, rc)}
}

func (_c *Composer_ListTools_Call) Run(run func(ctx context.Context, rc *consumer.RoutableConsumer)) *Composer_ListTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*consumer.RoutableConsumer))
	})
	return _c
}

func (_c *Composer_ListTools_Call) Return(_a0 []mcp.Tool, _a1 error) *Composer_ListTools_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Composer_ListTools_Call) RunAndReturn(run func(context.Context, *consumer.RoutableConsumer) ([]mcp.Tool, error)) *Composer_ListTools_Call {
	_c.Call.Return(run)
	return _c
}

// ReadResource provides a mock function with given fields: ctx, rc, uri
func (_m *Composer) ReadResource(ctx context.Context, rc *consumer.RoutableConsumer, uri string) (json.RawMessage, error) {
	ret := _m.Called(ctx, rc, uri)

	if len(ret) == 0 {
		panic("no return value specified for ReadResource")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer, string) (json.RawMessage, error)); ok {
		return rf(ctx, rc, uri)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer, string) json.RawMessage); ok {
		r0 = rf(ctx, rc, uri)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *consumer.RoutableConsumer, string) error); ok {
		r1 = rf(ctx, rc, uri)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Composer_ReadResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadResource'
type Composer_ReadResource_Call struct {
	*mock.Call
}

// ReadResource is a helper method to define mock.On call
//   - ctx context.Context
//   - rc *consumer.RoutableConsumer
//   - uri string
func (_e *Composer_Expecter) ReadResource(ctx interface{}, rc interface{}, uri interface{}) *Composer_ReadResource_Call {
	return &Composer_ReadResource_Call{Call: _e.mock.On("ReadResource", ctx, rc, uri)}
}

func (_c *Composer_ReadResource_Call) Run(run func(ctx context.Context, rc *consumer.RoutableConsumer, uri string)) *Composer_ReadResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*consumer.RoutableConsumer), args[2].(string))
	})
	return _c
}

func (_c *Composer_ReadResource_Call) Return(_a0 json.RawMessage, _a1 error) *Composer_ReadResource_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Composer_ReadResource_Call) RunAndReturn(run func(context.Context, *consumer.RoutableConsumer, string) (json.RawMessage, error)) *Composer_ReadResource_Call {
	_c.Call.Return(run)
	return _c
}

// UnwrapTaskHandle provides a mock function with given fields: ctx, rc, handle
func (_m *Composer) UnwrapTaskHandle(ctx context.Context, rc *consumer.RoutableConsumer, handle string) (mcp.TaskRef, error) {
	ret := _m.Called(ctx, rc, handle)

	if len(ret) == 0 {
		panic("no return value specified for UnwrapTaskHandle")
	}

	var r0 mcp.TaskRef
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer, string) (mcp.TaskRef, error)); ok {
		return rf(ctx, rc, handle)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer, string) mcp.TaskRef); ok {
		r0 = rf(ctx, rc, handle)
	} else {
		r0 = ret.Get(0).(mcp.TaskRef)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *consumer.RoutableConsumer, string) error); ok {
		r1 = rf(ctx, rc, handle)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Composer_UnwrapTaskHandle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnwrapTaskHandle'
type Composer_UnwrapTaskHandle_Call struct {
	*mock.Call
}

// UnwrapTaskHandle is a helper method to define mock.On call
//   - ctx context.Context
//   - rc *consumer.RoutableConsumer
//   - handle string
func (_e *Composer_Expecter) UnwrapTaskHandle(ctx interface{}, rc interface{}, handle interface{}) *Composer_UnwrapTaskHandle_Call {
	return &Composer_UnwrapTaskHandle_Call{Call: _e.mock.On("UnwrapTaskHandle", ctx, rc, handle)}
}

func (_c *Composer_UnwrapTaskHandle_Call) Run(run func(ctx context.Context, rc *consumer.RoutableConsumer, handle string)) *Composer_UnwrapTaskHandle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*consumer.RoutableConsumer), args[2].(string))
	})
	return _c
}

func (_c *Composer_UnwrapTaskHandle_Call) Return(_a0 mcp.TaskRef, _a1 error) *Composer_UnwrapTaskHandle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Composer_UnwrapTaskHandle_Call) RunAndReturn(run func(context.Context, *consumer.RoutableConsumer, string) (mcp.TaskRef, error)) *Composer_UnwrapTaskHandle_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function with given fields: ctx, rc, handle, inputResponses
func (_m *Composer) UpdateTask(ctx context.Context, rc *consumer.RoutableConsumer, handle string, inputResponses json.RawMessage) (json.RawMessage, error) {
	ret := _m.Called(ctx, rc, handle, inputResponses)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer, string, json.RawMessage) (json.RawMessage, error)); ok {
		return rf(ctx, rc, handle, inputResponses)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *consumer.RoutableConsumer, string, json.RawMessage) json.RawMessage); ok {
		r0 = rf(ctx, rc, handle, inputResponses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *consumer.RoutableConsumer, string, json.RawMessage) error); ok {
		r1 = rf(ctx, rc, handle, inputResponses)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Composer_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type Composer_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - rc *consumer.RoutableConsumer
//   - handle string
//   - inputResponses json.RawMessage
func (_e *Composer_Expecter) UpdateTask(ctx interface{}, rc interface{}, handle interface{}, inputResponses interface{}) *Composer_UpdateTask_Call {
	return &Composer_UpdateTask_Call{Call: _e.mock.On("UpdateTask", ctx, rc, handle, inputResponses)}
}

func (_c *Composer_UpdateTask_Call) Run(run func(ctx context.Context, rc *consumer.RoutableConsumer, handle string, inputResponses json.RawMessage)) *Composer_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*consumer.RoutableConsumer), args[2].(string), args[3].(json.RawMessage))
	})
	return _c
}

func (_c *Composer_UpdateTask_Call) Return(_a0 json.RawMessage, _a1 error) *Composer_UpdateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Composer_UpdateTask_Call) RunAndReturn(run func(context.Context, *consumer.RoutableConsumer, string, json.RawMessage) (json.RawMessage, error)) *Composer_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewComposer creates a new instance of Composer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewComposer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Composer {
	mock := &Composer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
