// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mcp "github.com/NeuralTrust/TrustGate/pkg/app/mcp"
	mock "github.com/stretchr/testify/mock"
)

// SubscriptionPolicy is an autogenerated mock type for the SubscriptionPolicy type
type SubscriptionPolicy struct {
	mock.Mock
}

type SubscriptionPolicy_Expecter struct {
	mock *mock.Mock
}

func (_m *SubscriptionPolicy) EXPECT() *SubscriptionPolicy_Expecter {
	return &SubscriptionPolicy_Expecter{mock: &_m.Mock}
}

// Evaluate provides a mock function with given fields: ctx, id, prev
func (_m *SubscriptionPolicy) Evaluate(ctx context.Context, id mcp.LeaseIdentity, prev mcp.SurfaceSnapshot) (mcp.Evaluation, error) {
	ret := _m.Called(ctx, id, prev)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 mcp.Evaluation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, mcp.LeaseIdentity, mcp.SurfaceSnapshot) (mcp.Evaluation, error)); ok {
		return rf(ctx, id, prev)
	}
	if rf, ok := ret.Get(0).(func(context.Context, mcp.LeaseIdentity, mcp.SurfaceSnapshot) mcp.Evaluation); ok {
		r0 = rf(ctx, id, prev)
	} else {
		r0 = ret.Get(0).(mcp.Evaluation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, mcp.LeaseIdentity, mcp.SurfaceSnapshot) error); ok {
		r1 = rf(ctx, id, prev)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscriptionPolicy_Evaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evaluate'
type SubscriptionPolicy_Evaluate_Call struct {
	*mock.Call
}

// Evaluate is a helper method to define mock.On call
//   - ctx context.Context
//   - id mcp.LeaseIdentity
//   - prev mcp.SurfaceSnapshot
func (_e *SubscriptionPolicy_Expecter) Evaluate(ctx interface{}, id interface{}, prev interface{}) *SubscriptionPolicy_Evaluate_Call {
	return &SubscriptionPolicy_Evaluate_Call{Call: _e.mock.On("Evaluate", ctx, id, prev)}
}

func (_c *SubscriptionPolicy_Evaluate_Call) Run(run func(ctx context.Context, id mcp.LeaseIdentity, prev mcp.SurfaceSnapshot)) *SubscriptionPolicy_Evaluate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(mcp.LeaseIdentity), args[2].(mcp.SurfaceSnapshot))
	})
	return _c
}

func (_c *SubscriptionPolicy_Evaluate_Call) Return(_a0 mcp.Evaluation, _a1 error) *SubscriptionPolicy_Evaluate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SubscriptionPolicy_Evaluate_Call) RunAndReturn(run func(context.Context, mcp.LeaseIdentity, mcp.SurfaceSnapshot) (mcp.Evaluation, error)) *SubscriptionPolicy_Evaluate_Call {
	_c.Call.Return(run)
	return _c
}

// NewSubscriptionPolicy creates a new instance of SubscriptionPolicy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionPolicy(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionPolicy {
	mock := &SubscriptionPolicy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
