apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: agentgateway-admin
  labels:
    app.kubernetes.io/instance: agentgateway
    component: admin
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: agentgateway
      app.kubernetes.io/instance: agentgateway
      component: admin
