// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ServiceAccountService is an autogenerated mock type for the ServiceAccountService type
type ServiceAccountService struct {
	mock.Mock
}

type ServiceAccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceAccountService) EXPECT() *ServiceAccountService_Expecter {
	return &ServiceAccountService_Expecter{mock: &_m.Mock}
}

// DecryptSA provides a mock function with given fields: upstreamID, targetID, encrypted
func (_m *ServiceAccountService) DecryptSA(upstreamID string, targetID string, encrypted string) (map[string]string, error) {
	ret := _m.Called(upstreamID, targetID, encrypted)

	if len(ret) == 0 {
		panic("no return value specified for DecryptSA")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (map[string]string, error)); ok {
		return rf(upstreamID, targetID, encrypted)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) map[string]string); ok {
		r0 = rf(upstreamID, targetID, encrypted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(upstreamID, targetID, encrypted)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceAccountService_DecryptSA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecryptSA'
type ServiceAccountService_DecryptSA_Call struct {
	*mock.Call
}

// DecryptSA is a helper method to define mock.On call
//   - upstreamID string
//   - targetID string
//   - encrypted string
func (_e *ServiceAccountService_Expecter) DecryptSA(upstreamID interface{}, targetID interface{}, encrypted interface{}) *ServiceAccountService_DecryptSA_Call {
	return &ServiceAccountService_DecryptSA_Call{Call: _e.mock.On("DecryptSA", upstreamID, targetID, encrypted)}
}

func (_c *ServiceAccountService_DecryptSA_Call) Run(run func(upstreamID string, targetID string, encrypted string)) *ServiceAccountService_DecryptSA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ServiceAccountService_DecryptSA_Call) Return(_a0 map[string]string, _a1 error) *ServiceAccountService_DecryptSA_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceAccountService_DecryptSA_Call) RunAndReturn(run func(string, string, string) (map[string]string, error)) *ServiceAccountService_DecryptSA_Call {
	_c.Call.Return(run)
	return _c
}

// EncryptSA provides a mock function with given fields: base64Encoded
func (_m *ServiceAccountService) EncryptSA(base64Encoded string) (string, error) {
	ret := _m.Called(base64Encoded)

	if len(ret) == 0 {
		panic("no return value specified for EncryptSA")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(base64Encoded)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(base64Encoded)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(base64Encoded)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceAccountService_EncryptSA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptSA'
type ServiceAccountService_EncryptSA_Call struct {
	*mock.Call
}

// EncryptSA is a helper method to define mock.On call
//   - base64Encoded string
func (_e *ServiceAccountService_Expecter) EncryptSA(base64Encoded interface{}) *ServiceAccountService_EncryptSA_Call {
	return &ServiceAccountService_EncryptSA_Call{Call: _e.mock.On("EncryptSA", base64Encoded)}
}

func (_c *ServiceAccountService_EncryptSA_Call) Run(run func(base64Encoded string)) *ServiceAccountService_EncryptSA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ServiceAccountService_EncryptSA_Call) Return(_a0 string, _a1 error) *ServiceAccountService_EncryptSA_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceAccountService_EncryptSA_Call) RunAndReturn(run func(string) (string, error)) *ServiceAccountService_EncryptSA_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccessToken provides a mock function with given fields: ctx, upstreamID, targetID, sa
func (_m *ServiceAccountService) GetAccessToken(ctx context.Context, upstreamID string, targetID string, sa map[string]string) (string, error) {
	ret := _m.Called(ctx, upstreamID, targetID, sa)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]string) (string, error)); ok {
		return rf(ctx, upstreamID, targetID, sa)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]string) string); ok {
		r0 = rf(ctx, upstreamID, targetID, sa)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, map[string]string) error); ok {
		r1 = rf(ctx, upstreamID, targetID, sa)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceAccountService_GetAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessToken'
type ServiceAccountService_GetAccessToken_Call struct {
	*mock.Call
}

// GetAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - upstreamID string
//   - targetID string
//   - sa map[string]string
func (_e *ServiceAccountService_Expecter) GetAccessToken(ctx interface{}, upstreamID interface{}, targetID interface{}, sa interface{}) *ServiceAccountService_GetAccessToken_Call {
	return &ServiceAccountService_GetAccessToken_Call{Call: _e.mock.On("GetAccessToken", ctx, upstreamID, targetID, sa)}
}

func (_c *ServiceAccountService_GetAccessToken_Call) Run(run func(ctx context.Context, upstreamID string, targetID string, sa map[string]string)) *ServiceAccountService_GetAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(map[string]string))
	})
	return _c
}

func (_c *ServiceAccountService_GetAccessToken_Call) Return(_a0 string, _a1 error) *ServiceAccountService_GetAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceAccountService_GetAccessToken_Call) RunAndReturn(run func(context.Context, string, string, map[string]string) (string, error)) *ServiceAccountService_GetAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateSACache provides a mock function with given fields: upstreamID, targetID
func (_m *ServiceAccountService) InvalidateSACache(upstreamID string, targetID string) {
	_m.Called(upstreamID, targetID)
}

// ServiceAccountService_InvalidateSACache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateSACache'
type ServiceAccountService_InvalidateSACache_Call struct {
	*mock.Call
}

// InvalidateSACache is a helper method to define mock.On call
//   - upstreamID string
//   - targetID string
func (_e *ServiceAccountService_Expecter) InvalidateSACache(upstreamID interface{}, targetID interface{}) *ServiceAccountService_InvalidateSACache_Call {
	return &ServiceAccountService_InvalidateSACache_Call{Call: _e.mock.On("InvalidateSACache", upstreamID, targetID)}
}

func (_c *ServiceAccountService_InvalidateSACache_Call) Run(run func(upstreamID string, targetID string)) *ServiceAccountService_InvalidateSACache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *ServiceAccountService_InvalidateSACache_Call) Return() *ServiceAccountService_InvalidateSACache_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServiceAccountService_InvalidateSACache_Call) RunAndReturn(run func(string, string)) *ServiceAccountService_InvalidateSACache_Call {
	_c.Run(run)
	return _c
}

// ResolveSAFromEnv provides a mock function with no fields
func (_m *ServiceAccountService) ResolveSAFromEnv() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResolveSAFromEnv")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceAccountService_ResolveSAFromEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveSAFromEnv'
type ServiceAccountService_ResolveSAFromEnv_Call struct {
	*mock.Call
}

// ResolveSAFromEnv is a helper method to define mock.On call
func (_e *ServiceAccountService_Expecter) ResolveSAFromEnv() *ServiceAccountService_ResolveSAFromEnv_Call {
	return &ServiceAccountService_ResolveSAFromEnv_Call{Call: _e.mock.On("ResolveSAFromEnv")}
}

func (_c *ServiceAccountService_ResolveSAFromEnv_Call) Run(run func()) *ServiceAccountService_ResolveSAFromEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServiceAccountService_ResolveSAFromEnv_Call) Return(_a0 string, _a1 error) *ServiceAccountService_ResolveSAFromEnv_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceAccountService_ResolveSAFromEnv_Call) RunAndReturn(run func() (string, error)) *ServiceAccountService_ResolveSAFromEnv_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateSA provides a mock function with given fields: base64Encoded
func (_m *ServiceAccountService) ValidateSA(base64Encoded string) error {
	ret := _m.Called(base64Encoded)

	if len(ret) == 0 {
		panic("no return value specified for ValidateSA")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(base64Encoded)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceAccountService_ValidateSA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateSA'
type ServiceAccountService_ValidateSA_Call struct {
	*mock.Call
}

// ValidateSA is a helper method to define mock.On call
//   - base64Encoded string
func (_e *ServiceAccountService_Expecter) ValidateSA(base64Encoded interface{}) *ServiceAccountService_ValidateSA_Call {
	return &ServiceAccountService_ValidateSA_Call{Call: _e.mock.On("ValidateSA", base64Encoded)}
}

func (_c *ServiceAccountService_ValidateSA_Call) Run(run func(base64Encoded string)) *ServiceAccountService_ValidateSA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ServiceAccountService_ValidateSA_Call) Return(_a0 error) *ServiceAccountService_ValidateSA_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceAccountService_ValidateSA_Call) RunAndReturn(run func(string) error) *ServiceAccountService_ValidateSA_Call {
	_c.Call.Return(run)
	return _c
}

// NewServiceAccountService creates a new instance of ServiceAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceAccountService {
	mock := &ServiceAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
