// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	ids "github.com/NeuralTrust/TrustGate/pkg/domain/ids"
	mock "github.com/stretchr/testify/mock"

	registry "github.com/NeuralTrust/TrustGate/pkg/domain/registry"
)

// PinnedToolRepository is an autogenerated mock type for the PinnedToolRepository type
type PinnedToolRepository struct {
	mock.Mock
}

type PinnedToolRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PinnedToolRepository) EXPECT() *PinnedToolRepository_Expecter {
	return &PinnedToolRepository_Expecter{mock: &_m.Mock}
}

// ApproveAll provides a mock function with given fields: ctx, gatewayID, registryID, tools, decidedBy
func (_m *PinnedToolRepository) ApproveAll(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], registryID ids.ID[ids.RegistryKind], tools []registry.ToolCandidate, decidedBy string) error {
	ret := _m.Called(ctx, gatewayID, registryID, tools, decidedBy)

	if len(ret) == 0 {
		panic("no return value specified for ApproveAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind], []registry.ToolCandidate, string) error); ok {
		r0 = rf(ctx, gatewayID, registryID, tools, decidedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PinnedToolRepository_ApproveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveAll'
type PinnedToolRepository_ApproveAll_Call struct {
	*mock.Call
}

// ApproveAll is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - registryID ids.ID[ids.RegistryKind]
//   - tools []registry.ToolCandidate
//   - decidedBy string
func (_e *PinnedToolRepository_Expecter) ApproveAll(ctx interface{}, gatewayID interface{}, registryID interface{}, tools interface{}, decidedBy interface{}) *PinnedToolRepository_ApproveAll_Call {
	return &PinnedToolRepository_ApproveAll_Call{Call: _e.mock.On("ApproveAll", ctx, gatewayID, registryID, tools, decidedBy)}
}

func (_c *PinnedToolRepository_ApproveAll_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], registryID ids.ID[ids.RegistryKind], tools []registry.ToolCandidate, decidedBy string)) *PinnedToolRepository_ApproveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].(ids.ID[ids.RegistryKind]), args[3].([]registry.ToolCandidate), args[4].(string))
	})
	return _c
}

func (_c *PinnedToolRepository_ApproveAll_Call) Return(_a0 error) *PinnedToolRepository_ApproveAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PinnedToolRepository_ApproveAll_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind], []registry.ToolCandidate, string) error) *PinnedToolRepository_ApproveAll_Call {
	_c.Call.Return(run)
	return _c
}

// Decide provides a mock function with given fields: ctx, gatewayID, registryID, approve, reject, decidedBy
func (_m *PinnedToolRepository) Decide(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], registryID ids.ID[ids.RegistryKind], approve []registry.ToolRef, reject []registry.ToolRef, decidedBy string) error {
	ret := _m.Called(ctx, gatewayID, registryID, approve, reject, decidedBy)

	if len(ret) == 0 {
		panic("no return value specified for Decide")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind], []registry.ToolRef, []registry.ToolRef, string) error); ok {
		r0 = rf(ctx, gatewayID, registryID, approve, reject, decidedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PinnedToolRepository_Decide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decide'
type PinnedToolRepository_Decide_Call struct {
	*mock.Call
}

// Decide is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - registryID ids.ID[ids.RegistryKind]
//   - approve []registry.ToolRef
//   - reject []registry.ToolRef
//   - decidedBy string
func (_e *PinnedToolRepository_Expecter) Decide(ctx interface{}, gatewayID interface{}, registryID interface{}, approve interface{}, reject interface{}, decidedBy interface{}) *PinnedToolRepository_Decide_Call {
	return &PinnedToolRepository_Decide_Call{Call: _e.mock.On("Decide", ctx, gatewayID, registryID, approve, reject, decidedBy)}
}

func (_c *PinnedToolRepository_Decide_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], registryID ids.ID[ids.RegistryKind], approve []registry.ToolRef, reject []registry.ToolRef, decidedBy string)) *PinnedToolRepository_Decide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].(ids.ID[ids.RegistryKind]), args[3].([]registry.ToolRef), args[4].([]registry.ToolRef), args[5].(string))
	})
	return _c
}

func (_c *PinnedToolRepository_Decide_Call) Return(_a0 error) *PinnedToolRepository_Decide_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PinnedToolRepository_Decide_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind], []registry.ToolRef, []registry.ToolRef, string) error) *PinnedToolRepository_Decide_Call {
	_c.Call.Return(run)
	return _c
}

// ListByRegistry provides a mock function with given fields: ctx, gatewayID, registryID
func (_m *PinnedToolRepository) ListByRegistry(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], registryID ids.ID[ids.RegistryKind]) ([]registry.PinnedTool, error) {
	ret := _m.Called(ctx, gatewayID, registryID)

	if len(ret) == 0 {
		panic("no return value specified for ListByRegistry")
	}

	var r0 []registry.PinnedTool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind]) ([]registry.PinnedTool, error)); ok {
		return rf(ctx, gatewayID, registryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind]) []registry.PinnedTool); ok {
		r0 = rf(ctx, gatewayID, registryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]registry.PinnedTool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind]) error); ok {
		r1 = rf(ctx, gatewayID, registryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PinnedToolRepository_ListByRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByRegistry'
type PinnedToolRepository_ListByRegistry_Call struct {
	*mock.Call
}

// ListByRegistry is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - registryID ids.ID[ids.RegistryKind]
func (_e *PinnedToolRepository_Expecter) ListByRegistry(ctx interface{}, gatewayID interface{}, registryID interface{}) *PinnedToolRepository_ListByRegistry_Call {
	return &PinnedToolRepository_ListByRegistry_Call{Call: _e.mock.On("ListByRegistry", ctx, gatewayID, registryID)}
}

func (_c *PinnedToolRepository_ListByRegistry_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], registryID ids.ID[ids.RegistryKind])) *PinnedToolRepository_ListByRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].(ids.ID[ids.RegistryKind]))
	})
	return _c
}

func (_c *PinnedToolRepository_ListByRegistry_Call) Return(_a0 []registry.PinnedTool, _a1 error) *PinnedToolRepository_ListByRegistry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PinnedToolRepository_ListByRegistry_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind]) ([]registry.PinnedTool, error)) *PinnedToolRepository_ListByRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// Pin provides a mock function with given fields: ctx, gatewayID, registryID, tools, decidedBy
func (_m *PinnedToolRepository) Pin(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], registryID ids.ID[ids.RegistryKind], tools []registry.ToolCandidate, decidedBy string) error {
	ret := _m.Called(ctx, gatewayID, registryID, tools, decidedBy)

	if len(ret) == 0 {
		panic("no return value specified for Pin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind], []registry.ToolCandidate, string) error); ok {
		r0 = rf(ctx, gatewayID, registryID, tools, decidedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PinnedToolRepository_Pin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pin'
type PinnedToolRepository_Pin_Call struct {
	*mock.Call
}

// Pin is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - registryID ids.ID[ids.RegistryKind]
//   - tools []registry.ToolCandidate
//   - decidedBy string
func (_e *PinnedToolRepository_Expecter) Pin(ctx interface{}, gatewayID interface{}, registryID interface{}, tools interface{}, decidedBy interface{}) *PinnedToolRepository_Pin_Call {
	return &PinnedToolRepository_Pin_Call{Call: _e.mock.On("Pin", ctx, gatewayID, registryID, tools, decidedBy)}
}

func (_c *PinnedToolRepository_Pin_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], registryID ids.ID[ids.RegistryKind], tools []registry.ToolCandidate, decidedBy string)) *PinnedToolRepository_Pin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].(ids.ID[ids.RegistryKind]), args[3].([]registry.ToolCandidate), args[4].(string))
	})
	return _c
}

func (_c *PinnedToolRepository_Pin_Call) Return(_a0 error) *PinnedToolRepository_Pin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PinnedToolRepository_Pin_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind], []registry.ToolCandidate, string) error) *PinnedToolRepository_Pin_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatus provides a mock function with given fields: ctx, gatewayID, registryID, refs, status, decidedBy
func (_m *PinnedToolRepository) SetStatus(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], registryID ids.ID[ids.RegistryKind], refs []registry.ToolRef, status registry.ToolStatus, decidedBy string) (int, error) {
	ret := _m.Called(ctx, gatewayID, registryID, refs, status, decidedBy)

	if len(ret) == 0 {
		panic("no return value specified for SetStatus")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind], []registry.ToolRef, registry.ToolStatus, string) (int, error)); ok {
		return rf(ctx, gatewayID, registryID, refs, status, decidedBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind], []registry.ToolRef, registry.ToolStatus, string) int); ok {
		r0 = rf(ctx, gatewayID, registryID, refs, status, decidedBy)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind], []registry.ToolRef, registry.ToolStatus, string) error); ok {
		r1 = rf(ctx, gatewayID, registryID, refs, status, decidedBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PinnedToolRepository_SetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatus'
type PinnedToolRepository_SetStatus_Call struct {
	*mock.Call
}

// SetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - registryID ids.ID[ids.RegistryKind]
//   - refs []registry.ToolRef
//   - status registry.ToolStatus
//   - decidedBy string
func (_e *PinnedToolRepository_Expecter) SetStatus(ctx interface{}, gatewayID interface{}, registryID interface{}, refs interface{}, status interface{}, decidedBy interface{}) *PinnedToolRepository_SetStatus_Call {
	return &PinnedToolRepository_SetStatus_Call{Call: _e.mock.On("SetStatus", ctx, gatewayID, registryID, refs, status, decidedBy)}
}

func (_c *PinnedToolRepository_SetStatus_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], registryID ids.ID[ids.RegistryKind], refs []registry.ToolRef, status registry.ToolStatus, decidedBy string)) *PinnedToolRepository_SetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].(ids.ID[ids.RegistryKind]), args[3].([]registry.ToolRef), args[4].(registry.ToolStatus), args[5].(string))
	})
	return _c
}

func (_c *PinnedToolRepository_SetStatus_Call) Return(_a0 int, _a1 error) *PinnedToolRepository_SetStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PinnedToolRepository_SetStatus_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind], []registry.ToolRef, registry.ToolStatus, string) (int, error)) *PinnedToolRepository_SetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertPending provides a mock function with given fields: ctx, gatewayID, registryID, tools
func (_m *PinnedToolRepository) UpsertPending(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], registryID ids.ID[ids.RegistryKind], tools []registry.ToolCandidate) (int, error) {
	ret := _m.Called(ctx, gatewayID, registryID, tools)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPending")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind], []registry.ToolCandidate) (int, error)); ok {
		return rf(ctx, gatewayID, registryID, tools)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind], []registry.ToolCandidate) int); ok {
		r0 = rf(ctx, gatewayID, registryID, tools)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind], []registry.ToolCandidate) error); ok {
		r1 = rf(ctx, gatewayID, registryID, tools)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PinnedToolRepository_UpsertPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPending'
type PinnedToolRepository_UpsertPending_Call struct {
	*mock.Call
}

// UpsertPending is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - registryID ids.ID[ids.RegistryKind]
//   - tools []registry.ToolCandidate
func (_e *PinnedToolRepository_Expecter) UpsertPending(ctx interface{}, gatewayID interface{}, registryID interface{}, tools interface{}) *PinnedToolRepository_UpsertPending_Call {
	return &PinnedToolRepository_UpsertPending_Call{Call: _e.mock.On("UpsertPending", ctx, gatewayID, registryID, tools)}
}

func (_c *PinnedToolRepository_UpsertPending_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], registryID ids.ID[ids.RegistryKind], tools []registry.ToolCandidate)) *PinnedToolRepository_UpsertPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].(ids.ID[ids.RegistryKind]), args[3].([]registry.ToolCandidate))
	})
	return _c
}

func (_c *PinnedToolRepository_UpsertPending_Call) Return(_a0 int, _a1 error) *PinnedToolRepository_UpsertPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PinnedToolRepository_UpsertPending_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind], []registry.ToolCandidate) (int, error)) *PinnedToolRepository_UpsertPending_Call {
	_c.Call.Return(run)
	return _c
}

// NewPinnedToolRepository creates a new instance of PinnedToolRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPinnedToolRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PinnedToolRepository {
	mock := &PinnedToolRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
