// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	ids "github.com/NeuralTrust/TrustGate/pkg/domain/ids"
	registry "github.com/NeuralTrust/TrustGate/pkg/domain/registry"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, gatewayID, id
func (_m *Repository) Delete(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], id ids.ID[ids.RegistryKind]) error {
	ret := _m.Called(ctx, gatewayID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind]) error); ok {
		r0 = rf(ctx, gatewayID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Repository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - id ids.ID[ids.RegistryKind]
func (_e *Repository_Expecter) Delete(ctx interface{}, gatewayID interface{}, id interface{}) *Repository_Delete_Call {
	return &Repository_Delete_Call{Call: _e.mock.On("Delete", ctx, gatewayID, id)}
}

func (_c *Repository_Delete_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], id ids.ID[ids.RegistryKind])) *Repository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].(ids.ID[ids.RegistryKind]))
	})
	return _c
}

func (_c *Repository_Delete_Call) Return(_a0 error) *Repository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Delete_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RegistryKind]) error) *Repository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *Repository) FindByID(ctx context.Context, id ids.ID[ids.RegistryKind]) (*registry.Registry, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *registry.Registry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.RegistryKind]) (*registry.Registry, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.RegistryKind]) *registry.Registry); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*registry.Registry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.RegistryKind]) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type Repository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id ids.ID[ids.RegistryKind]
func (_e *Repository_Expecter) FindByID(ctx interface{}, id interface{}) *Repository_FindByID_Call {
	return &Repository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *Repository_FindByID_Call) Run(run func(ctx context.Context, id ids.ID[ids.RegistryKind])) *Repository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.RegistryKind]))
	})
	return _c
}

func (_c *Repository_FindByID_Call) Return(_a0 *registry.Registry, _a1 error) *Repository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByID_Call) RunAndReturn(run func(context.Context, ids.ID[ids.RegistryKind]) (*registry.Registry, error)) *Repository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDs provides a mock function with given fields: ctx, gatewayID, registryIDs
func (_m *Repository) FindByIDs(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], registryIDs []ids.ID[ids.RegistryKind]) ([]*registry.Registry, error) {
	ret := _m.Called(ctx, gatewayID, registryIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []*registry.Registry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], []ids.ID[ids.RegistryKind]) ([]*registry.Registry, error)); ok {
		return rf(ctx, gatewayID, registryIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], []ids.ID[ids.RegistryKind]) []*registry.Registry); ok {
		r0 = rf(ctx, gatewayID, registryIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*registry.Registry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.GatewayKind], []ids.ID[ids.RegistryKind]) error); ok {
		r1 = rf(ctx, gatewayID, registryIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type Repository_FindByIDs_Call struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - registryIDs []ids.ID[ids.RegistryKind]
func (_e *Repository_Expecter) FindByIDs(ctx interface{}, gatewayID interface{}, registryIDs interface{}) *Repository_FindByIDs_Call {
	return &Repository_FindByIDs_Call{Call: _e.mock.On("FindByIDs", ctx, gatewayID, registryIDs)}
}

func (_c *Repository_FindByIDs_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], registryIDs []ids.ID[ids.RegistryKind])) *Repository_FindByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].([]ids.ID[ids.RegistryKind]))
	})
	return _c
}

func (_c *Repository_FindByIDs_Call) Return(_a0 []*registry.Registry, _a1 error) *Repository_FindByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByIDs_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], []ids.ID[ids.RegistryKind]) ([]*registry.Registry, error)) *Repository_FindByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *Repository) List(ctx context.Context, filter registry.ListFilter) ([]*registry.Registry, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*registry.Registry
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, registry.ListFilter) ([]*registry.Registry, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, registry.ListFilter) []*registry.Registry); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*registry.Registry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, registry.ListFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, registry.ListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Repository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter registry.ListFilter
func (_e *Repository_Expecter) List(ctx interface{}, filter interface{}) *Repository_List_Call {
	return &Repository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *Repository_List_Call) Run(run func(ctx context.Context, filter registry.ListFilter)) *Repository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(registry.ListFilter))
	})
	return _c
}

func (_c *Repository_List_Call) Return(items []*registry.Registry, total int, err error) *Repository_List_Call {
	_c.Call.Return(items, total, err)
	return _c
}

func (_c *Repository_List_Call) RunAndReturn(run func(context.Context, registry.ListFilter) ([]*registry.Registry, int, error)) *Repository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, b
func (_m *Repository) Save(ctx context.Context, b *registry.Registry) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *registry.Registry) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Repository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - b *registry.Registry
func (_e *Repository_Expecter) Save(ctx interface{}, b interface{}) *Repository_Save_Call {
	return &Repository_Save_Call{Call: _e.mock.On("Save", ctx, b)}
}

func (_c *Repository_Save_Call) Run(run func(ctx context.Context, b *registry.Registry)) *Repository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*registry.Registry))
	})
	return _c
}

func (_c *Repository_Save_Call) Return(_a0 error) *Repository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Save_Call) RunAndReturn(run func(context.Context, *registry.Registry) error) *Repository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, b
func (_m *Repository) Update(ctx context.Context, b *registry.Registry) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *registry.Registry) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - b *registry.Registry
func (_e *Repository_Expecter) Update(ctx interface{}, b interface{}) *Repository_Update_Call {
	return &Repository_Update_Call{Call: _e.mock.On("Update", ctx, b)}
}

func (_c *Repository_Update_Call) Run(run func(ctx context.Context, b *registry.Registry)) *Repository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*registry.Registry))
	})
	return _c
}

func (_c *Repository_Update_Call) Return(_a0 error) *Repository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Update_Call) RunAndReturn(run func(context.Context, *registry.Registry) error) *Repository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
