// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	ids "github.com/NeuralTrust/AgentGateway/pkg/domain/ids"
	policy "github.com/NeuralTrust/AgentGateway/pkg/domain/policy"
	mock "github.com/stretchr/testify/mock"
)

// Duplicator is an autogenerated mock type for the Duplicator type
type Duplicator struct {
	mock.Mock
}

type Duplicator_Expecter struct {
	mock *mock.Mock
}

func (_m *Duplicator) EXPECT() *Duplicator_Expecter {
	return &Duplicator_Expecter{mock: &_m.Mock}
}

// Duplicate provides a mock function with given fields: ctx, gatewayID, id
func (_m *Duplicator) Duplicate(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], id ids.ID[ids.PolicyKind]) (*policy.Policy, error) {
	ret := _m.Called(ctx, gatewayID, id)

	if len(ret) == 0 {
		panic("no return value specified for Duplicate")
	}

	var r0 *policy.Policy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.PolicyKind]) (*policy.Policy, error)); ok {
		return rf(ctx, gatewayID, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.PolicyKind]) *policy.Policy); ok {
		r0 = rf(ctx, gatewayID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*policy.Policy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.PolicyKind]) error); ok {
		r1 = rf(ctx, gatewayID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Duplicator_Duplicate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Duplicate'
type Duplicator_Duplicate_Call struct {
	*mock.Call
}

// Duplicate is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - id ids.ID[ids.PolicyKind]
func (_e *Duplicator_Expecter) Duplicate(ctx interface{}, gatewayID interface{}, id interface{}) *Duplicator_Duplicate_Call {
	return &Duplicator_Duplicate_Call{Call: _e.mock.On("Duplicate", ctx, gatewayID, id)}
}

func (_c *Duplicator_Duplicate_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], id ids.ID[ids.PolicyKind])) *Duplicator_Duplicate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].(ids.ID[ids.PolicyKind]))
	})
	return _c
}

func (_c *Duplicator_Duplicate_Call) Return(_a0 *policy.Policy, _a1 error) *Duplicator_Duplicate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Duplicator_Duplicate_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.PolicyKind]) (*policy.Policy, error)) *Duplicator_Duplicate_Call {
	_c.Call.Return(run)
	return _c
}

// NewDuplicator creates a new instance of Duplicator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDuplicator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Duplicator {
	mock := &Duplicator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
