// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	ids "github.com/NeuralTrust/TrustGate/pkg/domain/ids"
	mock "github.com/stretchr/testify/mock"

	policy "github.com/NeuralTrust/TrustGate/pkg/domain/policy"
)

// Warner is an autogenerated mock type for the Warner type
type Warner struct {
	mock.Mock
}

type Warner_Expecter struct {
	mock *mock.Mock
}

func (_m *Warner) EXPECT() *Warner_Expecter {
	return &Warner_Expecter{mock: &_m.Mock}
}

// Overlaps provides a mock function with given fields: ctx, p
func (_m *Warner) Overlaps(ctx context.Context, p *policy.Policy) ([]string, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Overlaps")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *policy.Policy) ([]string, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *policy.Policy) []string); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *policy.Policy) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Warner_Overlaps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Overlaps'
type Warner_Overlaps_Call struct {
	*mock.Call
}

// Overlaps is a helper method to define mock.On call
//   - ctx context.Context
//   - p *policy.Policy
func (_e *Warner_Expecter) Overlaps(ctx interface{}, p interface{}) *Warner_Overlaps_Call {
	return &Warner_Overlaps_Call{Call: _e.mock.On("Overlaps", ctx, p)}
}

func (_c *Warner_Overlaps_Call) Run(run func(ctx context.Context, p *policy.Policy)) *Warner_Overlaps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*policy.Policy))
	})
	return _c
}

func (_c *Warner_Overlaps_Call) Return(_a0 []string, _a1 error) *Warner_Overlaps_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Warner_Overlaps_Call) RunAndReturn(run func(context.Context, *policy.Policy) ([]string, error)) *Warner_Overlaps_Call {
	_c.Call.Return(run)
	return _c
}

// OverlapsOnAttach provides a mock function with given fields: ctx, gatewayID, consumerID, policyID
func (_m *Warner) OverlapsOnAttach(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], consumerID ids.ID[ids.ConsumerKind], policyID ids.ID[ids.PolicyKind]) ([]string, error) {
	ret := _m.Called(ctx, gatewayID, consumerID, policyID)

	if len(ret) == 0 {
		panic("no return value specified for OverlapsOnAttach")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.ConsumerKind], ids.ID[ids.PolicyKind]) ([]string, error)); ok {
		return rf(ctx, gatewayID, consumerID, policyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.ConsumerKind], ids.ID[ids.PolicyKind]) []string); ok {
		r0 = rf(ctx, gatewayID, consumerID, policyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.ConsumerKind], ids.ID[ids.PolicyKind]) error); ok {
		r1 = rf(ctx, gatewayID, consumerID, policyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Warner_OverlapsOnAttach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OverlapsOnAttach'
type Warner_OverlapsOnAttach_Call struct {
	*mock.Call
}

// OverlapsOnAttach is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - consumerID ids.ID[ids.ConsumerKind]
//   - policyID ids.ID[ids.PolicyKind]
func (_e *Warner_Expecter) OverlapsOnAttach(ctx interface{}, gatewayID interface{}, consumerID interface{}, policyID interface{}) *Warner_OverlapsOnAttach_Call {
	return &Warner_OverlapsOnAttach_Call{Call: _e.mock.On("OverlapsOnAttach", ctx, gatewayID, consumerID, policyID)}
}

func (_c *Warner_OverlapsOnAttach_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], consumerID ids.ID[ids.ConsumerKind], policyID ids.ID[ids.PolicyKind])) *Warner_OverlapsOnAttach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].(ids.ID[ids.ConsumerKind]), args[3].(ids.ID[ids.PolicyKind]))
	})
	return _c
}

func (_c *Warner_OverlapsOnAttach_Call) Return(_a0 []string, _a1 error) *Warner_OverlapsOnAttach_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Warner_OverlapsOnAttach_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.ConsumerKind], ids.ID[ids.PolicyKind]) ([]string, error)) *Warner_OverlapsOnAttach_Call {
	_c.Call.Return(run)
	return _c
}

// NewWarner creates a new instance of Warner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWarner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Warner {
	mock := &Warner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
