// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	ids "github.com/NeuralTrust/TrustGate/pkg/domain/ids"
	infracontext "github.com/NeuralTrust/TrustGate/pkg/infra/context"

	mock "github.com/stretchr/testify/mock"

	proxy "github.com/NeuralTrust/TrustGate/pkg/app/proxy"
)

// Forwarder is an autogenerated mock type for the Forwarder type
type Forwarder struct {
	mock.Mock
}

type Forwarder_Expecter struct {
	mock *mock.Mock
}

func (_m *Forwarder) EXPECT() *Forwarder_Expecter {
	return &Forwarder_Expecter{mock: &_m.Mock}
}

// Forward provides a mock function with given fields: ctx, in
func (_m *Forwarder) Forward(ctx context.Context, in proxy.ForwardInput) (*proxy.ForwardResult, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Forward")
	}

	var r0 *proxy.ForwardResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, proxy.ForwardInput) (*proxy.ForwardResult, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, proxy.ForwardInput) *proxy.ForwardResult); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proxy.ForwardResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, proxy.ForwardInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Forwarder_Forward_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forward'
type Forwarder_Forward_Call struct {
	*mock.Call
}

// Forward is a helper method to define mock.On call
//   - ctx context.Context
//   - in proxy.ForwardInput
func (_e *Forwarder_Expecter) Forward(ctx interface{}, in interface{}) *Forwarder_Forward_Call {
	return &Forwarder_Forward_Call{Call: _e.mock.On("Forward", ctx, in)}
}

func (_c *Forwarder_Forward_Call) Run(run func(ctx context.Context, in proxy.ForwardInput)) *Forwarder_Forward_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(proxy.ForwardInput))
	})
	return _c
}

func (_c *Forwarder_Forward_Call) Return(_a0 *proxy.ForwardResult, _a1 error) *Forwarder_Forward_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Forwarder_Forward_Call) RunAndReturn(run func(context.Context, proxy.ForwardInput) (*proxy.ForwardResult, error)) *Forwarder_Forward_Call {
	_c.Call.Return(run)
	return _c
}

// Precheck provides a mock function with given fields: ctx, gatewayID, req
func (_m *Forwarder) Precheck(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], req *infracontext.RequestContext) (*proxy.ForwardResult, error) {
	ret := _m.Called(ctx, gatewayID, req)

	if len(ret) == 0 {
		panic("no return value specified for Precheck")
	}

	var r0 *proxy.ForwardResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], *infracontext.RequestContext) (*proxy.ForwardResult, error)); ok {
		return rf(ctx, gatewayID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], *infracontext.RequestContext) *proxy.ForwardResult); ok {
		r0 = rf(ctx, gatewayID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proxy.ForwardResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.GatewayKind], *infracontext.RequestContext) error); ok {
		r1 = rf(ctx, gatewayID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Forwarder_Precheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Precheck'
type Forwarder_Precheck_Call struct {
	*mock.Call
}

// Precheck is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - req *infracontext.RequestContext
func (_e *Forwarder_Expecter) Precheck(ctx interface{}, gatewayID interface{}, req interface{}) *Forwarder_Precheck_Call {
	return &Forwarder_Precheck_Call{Call: _e.mock.On("Precheck", ctx, gatewayID, req)}
}

func (_c *Forwarder_Precheck_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], req *infracontext.RequestContext)) *Forwarder_Precheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].(*infracontext.RequestContext))
	})
	return _c
}

func (_c *Forwarder_Precheck_Call) Return(_a0 *proxy.ForwardResult, _a1 error) *Forwarder_Precheck_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Forwarder_Precheck_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], *infracontext.RequestContext) (*proxy.ForwardResult, error)) *Forwarder_Precheck_Call {
	_c.Call.Return(run)
	return _c
}

// NewForwarder creates a new instance of Forwarder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewForwarder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Forwarder {
	mock := &Forwarder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
