// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	proxy "github.com/NeuralTrust/TrustGate/pkg/app/proxy"
	mock "github.com/stretchr/testify/mock"
)

// StoreModels is an autogenerated mock type for the StoreModels type
type StoreModels struct {
	mock.Mock
}

type StoreModels_Expecter struct {
	mock *mock.Mock
}

func (_m *StoreModels) EXPECT() *StoreModels_Expecter {
	return &StoreModels_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, in, id
func (_m *StoreModels) Get(ctx context.Context, in proxy.StoreModelsInput, id string) (*proxy.ModelCard, error) {
	ret := _m.Called(ctx, in, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *proxy.ModelCard
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, proxy.StoreModelsInput, string) (*proxy.ModelCard, error)); ok {
		return rf(ctx, in, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, proxy.StoreModelsInput, string) *proxy.ModelCard); ok {
		r0 = rf(ctx, in, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proxy.ModelCard)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, proxy.StoreModelsInput, string) error); ok {
		r1 = rf(ctx, in, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreModels_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type StoreModels_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - in proxy.StoreModelsInput
//   - id string
func (_e *StoreModels_Expecter) Get(ctx interface{}, in interface{}, id interface{}) *StoreModels_Get_Call {
	return &StoreModels_Get_Call{Call: _e.mock.On("Get", ctx, in, id)}
}

func (_c *StoreModels_Get_Call) Run(run func(ctx context.Context, in proxy.StoreModelsInput, id string)) *StoreModels_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(proxy.StoreModelsInput), args[2].(string))
	})
	return _c
}

func (_c *StoreModels_Get_Call) Return(_a0 *proxy.ModelCard, _a1 error) *StoreModels_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StoreModels_Get_Call) RunAndReturn(run func(context.Context, proxy.StoreModelsInput, string) (*proxy.ModelCard, error)) *StoreModels_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, in
func (_m *StoreModels) List(ctx context.Context, in proxy.StoreModelsInput) (*proxy.ModelsList, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *proxy.ModelsList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, proxy.StoreModelsInput) (*proxy.ModelsList, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, proxy.StoreModelsInput) *proxy.ModelsList); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proxy.ModelsList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, proxy.StoreModelsInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreModels_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type StoreModels_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - in proxy.StoreModelsInput
func (_e *StoreModels_Expecter) List(ctx interface{}, in interface{}) *StoreModels_List_Call {
	return &StoreModels_List_Call{Call: _e.mock.On("List", ctx, in)}
}

func (_c *StoreModels_List_Call) Run(run func(ctx context.Context, in proxy.StoreModelsInput)) *StoreModels_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(proxy.StoreModelsInput))
	})
	return _c
}

func (_c *StoreModels_List_Call) Return(_a0 *proxy.ModelsList, _a1 error) *StoreModels_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StoreModels_List_Call) RunAndReturn(run func(context.Context, proxy.StoreModelsInput) (*proxy.ModelsList, error)) *StoreModels_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewStoreModels creates a new instance of StoreModels. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreModels(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreModels {
	mock := &StoreModels{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
