// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	gateway "github.com/NeuralTrust/TrustGate/pkg/domain/gateway"
	cache "github.com/NeuralTrust/TrustGate/pkg/infra/cache"
	redis "github.com/redis/go-redis/v9"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// ClearAllTTLMaps provides a mock function with no fields
func (_m *Client) ClearAllTTLMaps() {
	_m.Called()
}

// Client_ClearAllTTLMaps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearAllTTLMaps'
type Client_ClearAllTTLMaps_Call struct {
	*mock.Call
}

// ClearAllTTLMaps is a helper method to define mock.On call
func (_e *Client_Expecter) ClearAllTTLMaps() *Client_ClearAllTTLMaps_Call {
	return &Client_ClearAllTTLMaps_Call{Call: _e.mock.On("ClearAllTTLMaps")}
}

func (_c *Client_ClearAllTTLMaps_Call) Run(run func()) *Client_ClearAllTTLMaps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_ClearAllTTLMaps_Call) Return() *Client_ClearAllTTLMaps_Call {
	_c.Call.Return()
	return _c
}

func (_c *Client_ClearAllTTLMaps_Call) RunAndReturn(run func()) *Client_ClearAllTTLMaps_Call {
	_c.Run(run)
	return _c
}

// CreateTTLMap provides a mock function with given fields: name, ttl
func (_m *Client) CreateTTLMap(name string, ttl time.Duration) *cache.TTLMap {
	ret := _m.Called(name, ttl)

	if len(ret) == 0 {
		panic("no return value specified for CreateTTLMap")
	}

	var r0 *cache.TTLMap
	if rf, ok := ret.Get(0).(func(string, time.Duration) *cache.TTLMap); ok {
		r0 = rf(name, ttl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cache.TTLMap)
		}
	}

	return r0
}

// Client_CreateTTLMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTTLMap'
type Client_CreateTTLMap_Call struct {
	*mock.Call
}

// CreateTTLMap is a helper method to define mock.On call
//   - name string
//   - ttl time.Duration
func (_e *Client_Expecter) CreateTTLMap(name interface{}, ttl interface{}) *Client_CreateTTLMap_Call {
	return &Client_CreateTTLMap_Call{Call: _e.mock.On("CreateTTLMap", name, ttl)}
}

func (_c *Client_CreateTTLMap_Call) Run(run func(name string, ttl time.Duration)) *Client_CreateTTLMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration))
	})
	return _c
}

func (_c *Client_CreateTTLMap_Call) Return(_a0 *cache.TTLMap) *Client_CreateTTLMap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_CreateTTLMap_Call) RunAndReturn(run func(string, time.Duration) *cache.TTLMap) *Client_CreateTTLMap_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, key
func (_m *Client) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Client_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *Client_Expecter) Delete(ctx interface{}, key interface{}) *Client_Delete_Call {
	return &Client_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *Client_Delete_Call) Run(run func(ctx context.Context, key string)) *Client_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_Delete_Call) Return(_a0 error) *Client_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_Delete_Call) RunAndReturn(run func(context.Context, string) error) *Client_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllByGatewayID provides a mock function with given fields: ctx, gatewayID
func (_m *Client) DeleteAllByGatewayID(ctx context.Context, gatewayID string) error {
	ret := _m.Called(ctx, gatewayID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllByGatewayID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, gatewayID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_DeleteAllByGatewayID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllByGatewayID'
type Client_DeleteAllByGatewayID_Call struct {
	*mock.Call
}

// DeleteAllByGatewayID is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID string
func (_e *Client_Expecter) DeleteAllByGatewayID(ctx interface{}, gatewayID interface{}) *Client_DeleteAllByGatewayID_Call {
	return &Client_DeleteAllByGatewayID_Call{Call: _e.mock.On("DeleteAllByGatewayID", ctx, gatewayID)}
}

func (_c *Client_DeleteAllByGatewayID_Call) Run(run func(ctx context.Context, gatewayID string)) *Client_DeleteAllByGatewayID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_DeleteAllByGatewayID_Call) Return(_a0 error) *Client_DeleteAllByGatewayID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_DeleteAllByGatewayID_Call) RunAndReturn(run func(context.Context, string) error) *Client_DeleteAllByGatewayID_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *Client) Get(ctx context.Context, key string) (string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Client_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *Client_Expecter) Get(ctx interface{}, key interface{}) *Client_Get_Call {
	return &Client_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *Client_Get_Call) Run(run func(ctx context.Context, key string)) *Client_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_Get_Call) Return(_a0 string, _a1 error) *Client_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_Get_Call) RunAndReturn(run func(context.Context, string) (string, error)) *Client_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetGateway provides a mock function with given fields: ctx, id
func (_m *Client) GetGateway(ctx context.Context, id string) (*gateway.Gateway, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetGateway")
	}

	var r0 *gateway.Gateway
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*gateway.Gateway, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *gateway.Gateway); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.Gateway)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetGateway_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGateway'
type Client_GetGateway_Call struct {
	*mock.Call
}

// GetGateway is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Client_Expecter) GetGateway(ctx interface{}, id interface{}) *Client_GetGateway_Call {
	return &Client_GetGateway_Call{Call: _e.mock.On("GetGateway", ctx, id)}
}

func (_c *Client_GetGateway_Call) Run(run func(ctx context.Context, id string)) *Client_GetGateway_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Client_GetGateway_Call) Return(_a0 *gateway.Gateway, _a1 error) *Client_GetGateway_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetGateway_Call) RunAndReturn(run func(context.Context, string) (*gateway.Gateway, error)) *Client_GetGateway_Call {
	_c.Call.Return(run)
	return _c
}

// GetTTLMap provides a mock function with given fields: name
func (_m *Client) GetTTLMap(name string) *cache.TTLMap {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetTTLMap")
	}

	var r0 *cache.TTLMap
	if rf, ok := ret.Get(0).(func(string) *cache.TTLMap); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cache.TTLMap)
		}
	}

	return r0
}

// Client_GetTTLMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTTLMap'
type Client_GetTTLMap_Call struct {
	*mock.Call
}

// GetTTLMap is a helper method to define mock.On call
//   - name string
func (_e *Client_Expecter) GetTTLMap(name interface{}) *Client_GetTTLMap_Call {
	return &Client_GetTTLMap_Call{Call: _e.mock.On("GetTTLMap", name)}
}

func (_c *Client_GetTTLMap_Call) Run(run func(name string)) *Client_GetTTLMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Client_GetTTLMap_Call) Return(_a0 *cache.TTLMap) *Client_GetTTLMap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_GetTTLMap_Call) RunAndReturn(run func(string) *cache.TTLMap) *Client_GetTTLMap_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateAll provides a mock function with given fields: ctx
func (_m *Client) InvalidateAll(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_InvalidateAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateAll'
type Client_InvalidateAll_Call struct {
	*mock.Call
}

// InvalidateAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Client_Expecter) InvalidateAll(ctx interface{}) *Client_InvalidateAll_Call {
	return &Client_InvalidateAll_Call{Call: _e.mock.On("InvalidateAll", ctx)}
}

func (_c *Client_InvalidateAll_Call) Run(run func(ctx context.Context)) *Client_InvalidateAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Client_InvalidateAll_Call) Return(_a0 error) *Client_InvalidateAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_InvalidateAll_Call) RunAndReturn(run func(context.Context) error) *Client_InvalidateAll_Call {
	_c.Call.Return(run)
	return _c
}

// RedisClient provides a mock function with no fields
func (_m *Client) RedisClient() *redis.Client {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RedisClient")
	}

	var r0 *redis.Client
	if rf, ok := ret.Get(0).(func() *redis.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.Client)
		}
	}

	return r0
}

// Client_RedisClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RedisClient'
type Client_RedisClient_Call struct {
	*mock.Call
}

// RedisClient is a helper method to define mock.On call
func (_e *Client_Expecter) RedisClient() *Client_RedisClient_Call {
	return &Client_RedisClient_Call{Call: _e.mock.On("RedisClient")}
}

func (_c *Client_RedisClient_Call) Run(run func()) *Client_RedisClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_RedisClient_Call) Return(_a0 *redis.Client) *Client_RedisClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_RedisClient_Call) RunAndReturn(run func() *redis.Client) *Client_RedisClient_Call {
	_c.Call.Return(run)
	return _c
}

// SaveGateway provides a mock function with given fields: ctx, _a1
func (_m *Client) SaveGateway(ctx context.Context, _a1 *gateway.Gateway) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveGateway")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gateway.Gateway) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_SaveGateway_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveGateway'
type Client_SaveGateway_Call struct {
	*mock.Call
}

// SaveGateway is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *gateway.Gateway
func (_e *Client_Expecter) SaveGateway(ctx interface{}, _a1 interface{}) *Client_SaveGateway_Call {
	return &Client_SaveGateway_Call{Call: _e.mock.On("SaveGateway", ctx, _a1)}
}

func (_c *Client_SaveGateway_Call) Run(run func(ctx context.Context, _a1 *gateway.Gateway)) *Client_SaveGateway_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gateway.Gateway))
	})
	return _c
}

func (_c *Client_SaveGateway_Call) Return(_a0 error) *Client_SaveGateway_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_SaveGateway_Call) RunAndReturn(run func(context.Context, *gateway.Gateway) error) *Client_SaveGateway_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, expiration
func (_m *Client) Set(ctx context.Context, key string, value string, expiration time.Duration) error {
	ret := _m.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Client_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
//   - expiration time.Duration
func (_e *Client_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *Client_Set_Call {
	return &Client_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *Client_Set_Call) Run(run func(ctx context.Context, key string, value string, expiration time.Duration)) *Client_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *Client_Set_Call) Return(_a0 error) *Client_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_Set_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) error) *Client_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
