// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	fingerprint "github.com/NeuralTrust/AgentGateway/pkg/infra/fingerprint"
	fiber "github.com/gofiber/fiber/v2"
	mock "github.com/stretchr/testify/mock"
)

// Tracker is an autogenerated mock type for the Tracker type
type Tracker struct {
	mock.Mock
}

type Tracker_Expecter struct {
	mock *mock.Mock
}

func (_m *Tracker) EXPECT() *Tracker_Expecter {
	return &Tracker_Expecter{mock: &_m.Mock}
}

// MakeFingerprint provides a mock function with given fields: ctx
func (_m *Tracker) MakeFingerprint(ctx *fiber.Ctx) fingerprint.Fingerprint {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for MakeFingerprint")
	}

	var r0 fingerprint.Fingerprint
	if rf, ok := ret.Get(0).(func(*fiber.Ctx) fingerprint.Fingerprint); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(fingerprint.Fingerprint)
	}

	return r0
}

// Tracker_MakeFingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeFingerprint'
type Tracker_MakeFingerprint_Call struct {
	*mock.Call
}

// MakeFingerprint is a helper method to define mock.On call
//   - ctx *fiber.Ctx
func (_e *Tracker_Expecter) MakeFingerprint(ctx interface{}) *Tracker_MakeFingerprint_Call {
	return &Tracker_MakeFingerprint_Call{Call: _e.mock.On("MakeFingerprint", ctx)}
}

func (_c *Tracker_MakeFingerprint_Call) Run(run func(ctx *fiber.Ctx)) *Tracker_MakeFingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*fiber.Ctx))
	})
	return _c
}

func (_c *Tracker_MakeFingerprint_Call) Return(_a0 fingerprint.Fingerprint) *Tracker_MakeFingerprint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Tracker_MakeFingerprint_Call) RunAndReturn(run func(*fiber.Ctx) fingerprint.Fingerprint) *Tracker_MakeFingerprint_Call {
	_c.Call.Return(run)
	return _c
}

// NewTracker creates a new instance of Tracker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTracker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Tracker {
	mock := &Tracker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
