// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	gateway "github.com/NeuralTrust/TrustGate/pkg/domain/gateway"
	ids "github.com/NeuralTrust/TrustGate/pkg/domain/ids"
	mock "github.com/stretchr/testify/mock"
)

// Finder is an autogenerated mock type for the Finder type
type Finder struct {
	mock.Mock
}

type Finder_Expecter struct {
	mock *mock.Mock
}

func (_m *Finder) EXPECT() *Finder_Expecter {
	return &Finder_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *Finder) FindByID(ctx context.Context, id ids.ID[ids.GatewayKind]) (*gateway.Gateway, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *gateway.Gateway
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind]) (*gateway.Gateway, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind]) *gateway.Gateway); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.Gateway)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.GatewayKind]) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Finder_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type Finder_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id ids.ID[ids.GatewayKind]
func (_e *Finder_Expecter) FindByID(ctx interface{}, id interface{}) *Finder_FindByID_Call {
	return &Finder_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *Finder_FindByID_Call) Run(run func(ctx context.Context, id ids.ID[ids.GatewayKind])) *Finder_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]))
	})
	return _c
}

func (_c *Finder_FindByID_Call) Return(_a0 *gateway.Gateway, _a1 error) *Finder_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Finder_FindByID_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind]) (*gateway.Gateway, error)) *Finder_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySlug provides a mock function with given fields: ctx, slug
func (_m *Finder) FindBySlug(ctx context.Context, slug string) (*gateway.Gateway, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for FindBySlug")
	}

	var r0 *gateway.Gateway
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*gateway.Gateway, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *gateway.Gateway); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gateway.Gateway)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Finder_FindBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySlug'
type Finder_FindBySlug_Call struct {
	*mock.Call
}

// FindBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *Finder_Expecter) FindBySlug(ctx interface{}, slug interface{}) *Finder_FindBySlug_Call {
	return &Finder_FindBySlug_Call{Call: _e.mock.On("FindBySlug", ctx, slug)}
}

func (_c *Finder_FindBySlug_Call) Run(run func(ctx context.Context, slug string)) *Finder_FindBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Finder_FindBySlug_Call) Return(_a0 *gateway.Gateway, _a1 error) *Finder_FindBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Finder_FindBySlug_Call) RunAndReturn(run func(context.Context, string) (*gateway.Gateway, error)) *Finder_FindBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *Finder) List(ctx context.Context, filter gateway.ListFilter) ([]*gateway.Gateway, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*gateway.Gateway
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, gateway.ListFilter) ([]*gateway.Gateway, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, gateway.ListFilter) []*gateway.Gateway); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gateway.Gateway)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, gateway.ListFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, gateway.ListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Finder_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Finder_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter gateway.ListFilter
func (_e *Finder_Expecter) List(ctx interface{}, filter interface{}) *Finder_List_Call {
	return &Finder_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *Finder_List_Call) Run(run func(ctx context.Context, filter gateway.ListFilter)) *Finder_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(gateway.ListFilter))
	})
	return _c
}

func (_c *Finder_List_Call) Return(_a0 []*gateway.Gateway, _a1 int, _a2 error) *Finder_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Finder_List_Call) RunAndReturn(run func(context.Context, gateway.ListFilter) ([]*gateway.Gateway, int, error)) *Finder_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewFinder creates a new instance of Finder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Finder {
	mock := &Finder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
