// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	embedding "github.com/NeuralTrust/TrustGate/pkg/domain/embedding"
	semantic "github.com/NeuralTrust/TrustGate/pkg/infra/cache/semantic"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// EnsureIndex provides a mock function with given fields: ctx, dimension
func (_m *Store) EnsureIndex(ctx context.Context, dimension int) error {
	ret := _m.Called(ctx, dimension)

	if len(ret) == 0 {
		panic("no return value specified for EnsureIndex")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, dimension)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_EnsureIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureIndex'
type Store_EnsureIndex_Call struct {
	*mock.Call
}

// EnsureIndex is a helper method to define mock.On call
//   - ctx context.Context
//   - dimension int
func (_e *Store_Expecter) EnsureIndex(ctx interface{}, dimension interface{}) *Store_EnsureIndex_Call {
	return &Store_EnsureIndex_Call{Call: _e.mock.On("EnsureIndex", ctx, dimension)}
}

func (_c *Store_EnsureIndex_Call) Run(run func(ctx context.Context, dimension int)) *Store_EnsureIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *Store_EnsureIndex_Call) Return(_a0 error) *Store_EnsureIndex_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_EnsureIndex_Call) RunAndReturn(run func(context.Context, int) error) *Store_EnsureIndex_Call {
	_c.Call.Return(run)
	return _c
}

// GetExact provides a mock function with given fields: ctx, ruleID, key
func (_m *Store) GetExact(ctx context.Context, ruleID string, key string) (string, bool, error) {
	ret := _m.Called(ctx, ruleID, key)

	if len(ret) == 0 {
		panic("no return value specified for GetExact")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, bool, error)); ok {
		return rf(ctx, ruleID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, ruleID, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = rf(ctx, ruleID, key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, ruleID, key)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Store_GetExact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExact'
type Store_GetExact_Call struct {
	*mock.Call
}

// GetExact is a helper method to define mock.On call
//   - ctx context.Context
//   - ruleID string
//   - key string
func (_e *Store_Expecter) GetExact(ctx interface{}, ruleID interface{}, key interface{}) *Store_GetExact_Call {
	return &Store_GetExact_Call{Call: _e.mock.On("GetExact", ctx, ruleID, key)}
}

func (_c *Store_GetExact_Call) Run(run func(ctx context.Context, ruleID string, key string)) *Store_GetExact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Store_GetExact_Call) Return(_a0 string, _a1 bool, _a2 error) *Store_GetExact_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Store_GetExact_Call) RunAndReturn(run func(context.Context, string, string) (string, bool, error)) *Store_GetExact_Call {
	_c.Call.Return(run)
	return _c
}

// Lookup provides a mock function with given fields: ctx, ruleID, emb, topK
func (_m *Store) Lookup(ctx context.Context, ruleID string, emb *embedding.Embedding, topK int) ([]semantic.Candidate, error) {
	ret := _m.Called(ctx, ruleID, emb, topK)

	if len(ret) == 0 {
		panic("no return value specified for Lookup")
	}

	var r0 []semantic.Candidate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *embedding.Embedding, int) ([]semantic.Candidate, error)); ok {
		return rf(ctx, ruleID, emb, topK)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *embedding.Embedding, int) []semantic.Candidate); ok {
		r0 = rf(ctx, ruleID, emb, topK)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]semantic.Candidate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *embedding.Embedding, int) error); ok {
		r1 = rf(ctx, ruleID, emb, topK)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_Lookup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lookup'
type Store_Lookup_Call struct {
	*mock.Call
}

// Lookup is a helper method to define mock.On call
//   - ctx context.Context
//   - ruleID string
//   - emb *embedding.Embedding
//   - topK int
func (_e *Store_Expecter) Lookup(ctx interface{}, ruleID interface{}, emb interface{}, topK interface{}) *Store_Lookup_Call {
	return &Store_Lookup_Call{Call: _e.mock.On("Lookup", ctx, ruleID, emb, topK)}
}

func (_c *Store_Lookup_Call) Run(run func(ctx context.Context, ruleID string, emb *embedding.Embedding, topK int)) *Store_Lookup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*embedding.Embedding), args[3].(int))
	})
	return _c
}

func (_c *Store_Lookup_Call) Return(_a0 []semantic.Candidate, _a1 error) *Store_Lookup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_Lookup_Call) RunAndReturn(run func(context.Context, string, *embedding.Embedding, int) ([]semantic.Candidate, error)) *Store_Lookup_Call {
	_c.Call.Return(run)
	return _c
}

// PutExact provides a mock function with given fields: ctx, ruleID, key, response, ttl
func (_m *Store) PutExact(ctx context.Context, ruleID string, key string, response string, ttl time.Duration) error {
	ret := _m.Called(ctx, ruleID, key, response, ttl)

	if len(ret) == 0 {
		panic("no return value specified for PutExact")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Duration) error); ok {
		r0 = rf(ctx, ruleID, key, response, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_PutExact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutExact'
type Store_PutExact_Call struct {
	*mock.Call
}

// PutExact is a helper method to define mock.On call
//   - ctx context.Context
//   - ruleID string
//   - key string
//   - response string
//   - ttl time.Duration
func (_e *Store_Expecter) PutExact(ctx interface{}, ruleID interface{}, key interface{}, response interface{}, ttl interface{}) *Store_PutExact_Call {
	return &Store_PutExact_Call{Call: _e.mock.On("PutExact", ctx, ruleID, key, response, ttl)}
}

func (_c *Store_PutExact_Call) Run(run func(ctx context.Context, ruleID string, key string, response string, ttl time.Duration)) *Store_PutExact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(time.Duration))
	})
	return _c
}

func (_c *Store_PutExact_Call) Return(_a0 error) *Store_PutExact_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_PutExact_Call) RunAndReturn(run func(context.Context, string, string, string, time.Duration) error) *Store_PutExact_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, entry
func (_m *Store) Store(ctx context.Context, entry semantic.Entry) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, semantic.Entry) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type Store_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - entry semantic.Entry
func (_e *Store_Expecter) Store(ctx interface{}, entry interface{}) *Store_Store_Call {
	return &Store_Store_Call{Call: _e.mock.On("Store", ctx, entry)}
}

func (_c *Store_Store_Call) Run(run func(ctx context.Context, entry semantic.Entry)) *Store_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(semantic.Entry))
	})
	return _c
}

func (_c *Store_Store_Call) Return(_a0 error) *Store_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_Store_Call) RunAndReturn(run func(context.Context, semantic.Entry) error) *Store_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
