// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	ids "github.com/NeuralTrust/AgentGateway/pkg/domain/ids"
	role "github.com/NeuralTrust/AgentGateway/pkg/domain/role"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// AttachRegistry provides a mock function with given fields: ctx, roleID, registryID
func (_m *Repository) AttachRegistry(ctx context.Context, roleID ids.ID[ids.RoleKind], registryID ids.ID[ids.RegistryKind]) error {
	ret := _m.Called(ctx, roleID, registryID)

	if len(ret) == 0 {
		panic("no return value specified for AttachRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.RoleKind], ids.ID[ids.RegistryKind]) error); ok {
		r0 = rf(ctx, roleID, registryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_AttachRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachRegistry'
type Repository_AttachRegistry_Call struct {
	*mock.Call
}

// AttachRegistry is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID ids.ID[ids.RoleKind]
//   - registryID ids.ID[ids.RegistryKind]
func (_e *Repository_Expecter) AttachRegistry(ctx interface{}, roleID interface{}, registryID interface{}) *Repository_AttachRegistry_Call {
	return &Repository_AttachRegistry_Call{Call: _e.mock.On("AttachRegistry", ctx, roleID, registryID)}
}

func (_c *Repository_AttachRegistry_Call) Run(run func(ctx context.Context, roleID ids.ID[ids.RoleKind], registryID ids.ID[ids.RegistryKind])) *Repository_AttachRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.RoleKind]), args[2].(ids.ID[ids.RegistryKind]))
	})
	return _c
}

func (_c *Repository_AttachRegistry_Call) Return(_a0 error) *Repository_AttachRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_AttachRegistry_Call) RunAndReturn(run func(context.Context, ids.ID[ids.RoleKind], ids.ID[ids.RegistryKind]) error) *Repository_AttachRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Repository) Delete(ctx context.Context, id ids.ID[ids.RoleKind]) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.RoleKind]) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Repository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id ids.ID[ids.RoleKind]
func (_e *Repository_Expecter) Delete(ctx interface{}, id interface{}) *Repository_Delete_Call {
	return &Repository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *Repository_Delete_Call) Run(run func(ctx context.Context, id ids.ID[ids.RoleKind])) *Repository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.RoleKind]))
	})
	return _c
}

func (_c *Repository_Delete_Call) Return(_a0 error) *Repository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Delete_Call) RunAndReturn(run func(context.Context, ids.ID[ids.RoleKind]) error) *Repository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DetachRegistry provides a mock function with given fields: ctx, roleID, registryID
func (_m *Repository) DetachRegistry(ctx context.Context, roleID ids.ID[ids.RoleKind], registryID ids.ID[ids.RegistryKind]) error {
	ret := _m.Called(ctx, roleID, registryID)

	if len(ret) == 0 {
		panic("no return value specified for DetachRegistry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.RoleKind], ids.ID[ids.RegistryKind]) error); ok {
		r0 = rf(ctx, roleID, registryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_DetachRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetachRegistry'
type Repository_DetachRegistry_Call struct {
	*mock.Call
}

// DetachRegistry is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID ids.ID[ids.RoleKind]
//   - registryID ids.ID[ids.RegistryKind]
func (_e *Repository_Expecter) DetachRegistry(ctx interface{}, roleID interface{}, registryID interface{}) *Repository_DetachRegistry_Call {
	return &Repository_DetachRegistry_Call{Call: _e.mock.On("DetachRegistry", ctx, roleID, registryID)}
}

func (_c *Repository_DetachRegistry_Call) Run(run func(ctx context.Context, roleID ids.ID[ids.RoleKind], registryID ids.ID[ids.RegistryKind])) *Repository_DetachRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.RoleKind]), args[2].(ids.ID[ids.RegistryKind]))
	})
	return _c
}

func (_c *Repository_DetachRegistry_Call) Return(_a0 error) *Repository_DetachRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_DetachRegistry_Call) RunAndReturn(run func(context.Context, ids.ID[ids.RoleKind], ids.ID[ids.RegistryKind]) error) *Repository_DetachRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// DetachRegistryIfUnreferenced provides a mock function with given fields: ctx, gatewayID, roleID, registryID
func (_m *Repository) DetachRegistryIfUnreferenced(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], roleID ids.ID[ids.RoleKind], registryID ids.ID[ids.RegistryKind]) (*role.Role, error) {
	ret := _m.Called(ctx, gatewayID, roleID, registryID)

	if len(ret) == 0 {
		panic("no return value specified for DetachRegistryIfUnreferenced")
	}

	var r0 *role.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RoleKind], ids.ID[ids.RegistryKind]) (*role.Role, error)); ok {
		return rf(ctx, gatewayID, roleID, registryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RoleKind], ids.ID[ids.RegistryKind]) *role.Role); ok {
		r0 = rf(ctx, gatewayID, roleID, registryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*role.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RoleKind], ids.ID[ids.RegistryKind]) error); ok {
		r1 = rf(ctx, gatewayID, roleID, registryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_DetachRegistryIfUnreferenced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetachRegistryIfUnreferenced'
type Repository_DetachRegistryIfUnreferenced_Call struct {
	*mock.Call
}

// DetachRegistryIfUnreferenced is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - roleID ids.ID[ids.RoleKind]
//   - registryID ids.ID[ids.RegistryKind]
func (_e *Repository_Expecter) DetachRegistryIfUnreferenced(ctx interface{}, gatewayID interface{}, roleID interface{}, registryID interface{}) *Repository_DetachRegistryIfUnreferenced_Call {
	return &Repository_DetachRegistryIfUnreferenced_Call{Call: _e.mock.On("DetachRegistryIfUnreferenced", ctx, gatewayID, roleID, registryID)}
}

func (_c *Repository_DetachRegistryIfUnreferenced_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], roleID ids.ID[ids.RoleKind], registryID ids.ID[ids.RegistryKind])) *Repository_DetachRegistryIfUnreferenced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].(ids.ID[ids.RoleKind]), args[3].(ids.ID[ids.RegistryKind]))
	})
	return _c
}

func (_c *Repository_DetachRegistryIfUnreferenced_Call) Return(_a0 *role.Role, _a1 error) *Repository_DetachRegistryIfUnreferenced_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_DetachRegistryIfUnreferenced_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], ids.ID[ids.RoleKind], ids.ID[ids.RegistryKind]) (*role.Role, error)) *Repository_DetachRegistryIfUnreferenced_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *Repository) FindByID(ctx context.Context, id ids.ID[ids.RoleKind]) (*role.Role, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *role.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.RoleKind]) (*role.Role, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.RoleKind]) *role.Role); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*role.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.RoleKind]) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type Repository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id ids.ID[ids.RoleKind]
func (_e *Repository_Expecter) FindByID(ctx interface{}, id interface{}) *Repository_FindByID_Call {
	return &Repository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *Repository_FindByID_Call) Run(run func(ctx context.Context, id ids.ID[ids.RoleKind])) *Repository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.RoleKind]))
	})
	return _c
}

func (_c *Repository_FindByID_Call) Return(_a0 *role.Role, _a1 error) *Repository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByID_Call) RunAndReturn(run func(context.Context, ids.ID[ids.RoleKind]) (*role.Role, error)) *Repository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDs provides a mock function with given fields: ctx, gatewayID, roleIDs
func (_m *Repository) FindByIDs(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], roleIDs []ids.ID[ids.RoleKind]) ([]*role.Role, error) {
	ret := _m.Called(ctx, gatewayID, roleIDs)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDs")
	}

	var r0 []*role.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], []ids.ID[ids.RoleKind]) ([]*role.Role, error)); ok {
		return rf(ctx, gatewayID, roleIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind], []ids.ID[ids.RoleKind]) []*role.Role); ok {
		r0 = rf(ctx, gatewayID, roleIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*role.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.GatewayKind], []ids.ID[ids.RoleKind]) error); ok {
		r1 = rf(ctx, gatewayID, roleIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_FindByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDs'
type Repository_FindByIDs_Call struct {
	*mock.Call
}

// FindByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
//   - roleIDs []ids.ID[ids.RoleKind]
func (_e *Repository_Expecter) FindByIDs(ctx interface{}, gatewayID interface{}, roleIDs interface{}) *Repository_FindByIDs_Call {
	return &Repository_FindByIDs_Call{Call: _e.mock.On("FindByIDs", ctx, gatewayID, roleIDs)}
}

func (_c *Repository_FindByIDs_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind], roleIDs []ids.ID[ids.RoleKind])) *Repository_FindByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]), args[2].([]ids.ID[ids.RoleKind]))
	})
	return _c
}

func (_c *Repository_FindByIDs_Call) Return(_a0 []*role.Role, _a1 error) *Repository_FindByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_FindByIDs_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind], []ids.ID[ids.RoleKind]) ([]*role.Role, error)) *Repository_FindByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *Repository) List(ctx context.Context, filter role.ListFilter) ([]*role.Role, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*role.Role
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, role.ListFilter) ([]*role.Role, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, role.ListFilter) []*role.Role); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*role.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, role.ListFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, role.ListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Repository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter role.ListFilter
func (_e *Repository_Expecter) List(ctx interface{}, filter interface{}) *Repository_List_Call {
	return &Repository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *Repository_List_Call) Run(run func(ctx context.Context, filter role.ListFilter)) *Repository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(role.ListFilter))
	})
	return _c
}

func (_c *Repository_List_Call) Return(items []*role.Role, total int, err error) *Repository_List_Call {
	_c.Call.Return(items, total, err)
	return _c
}

func (_c *Repository_List_Call) RunAndReturn(run func(context.Context, role.ListFilter) ([]*role.Role, int, error)) *Repository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByGateway provides a mock function with given fields: ctx, gatewayID
func (_m *Repository) ListByGateway(ctx context.Context, gatewayID ids.ID[ids.GatewayKind]) ([]*role.Role, error) {
	ret := _m.Called(ctx, gatewayID)

	if len(ret) == 0 {
		panic("no return value specified for ListByGateway")
	}

	var r0 []*role.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind]) ([]*role.Role, error)); ok {
		return rf(ctx, gatewayID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ids.ID[ids.GatewayKind]) []*role.Role); ok {
		r0 = rf(ctx, gatewayID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*role.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ids.ID[ids.GatewayKind]) error); ok {
		r1 = rf(ctx, gatewayID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_ListByGateway_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByGateway'
type Repository_ListByGateway_Call struct {
	*mock.Call
}

// ListByGateway is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID ids.ID[ids.GatewayKind]
func (_e *Repository_Expecter) ListByGateway(ctx interface{}, gatewayID interface{}) *Repository_ListByGateway_Call {
	return &Repository_ListByGateway_Call{Call: _e.mock.On("ListByGateway", ctx, gatewayID)}
}

func (_c *Repository_ListByGateway_Call) Run(run func(ctx context.Context, gatewayID ids.ID[ids.GatewayKind])) *Repository_ListByGateway_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ids.ID[ids.GatewayKind]))
	})
	return _c
}

func (_c *Repository_ListByGateway_Call) Return(_a0 []*role.Role, _a1 error) *Repository_ListByGateway_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_ListByGateway_Call) RunAndReturn(run func(context.Context, ids.ID[ids.GatewayKind]) ([]*role.Role, error)) *Repository_ListByGateway_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, r
func (_m *Repository) Save(ctx context.Context, r *role.Role) error {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *role.Role) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Repository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - r *role.Role
func (_e *Repository_Expecter) Save(ctx interface{}, r interface{}) *Repository_Save_Call {
	return &Repository_Save_Call{Call: _e.mock.On("Save", ctx, r)}
}

func (_c *Repository_Save_Call) Run(run func(ctx context.Context, r *role.Role)) *Repository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*role.Role))
	})
	return _c
}

func (_c *Repository_Save_Call) Return(_a0 error) *Repository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Save_Call) RunAndReturn(run func(context.Context, *role.Role) error) *Repository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, r
func (_m *Repository) Update(ctx context.Context, r *role.Role) error {
	ret := _m.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *role.Role) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - r *role.Role
func (_e *Repository_Expecter) Update(ctx interface{}, r interface{}) *Repository_Update_Call {
	return &Repository_Update_Call{Call: _e.mock.On("Update", ctx, r)}
}

func (_c *Repository_Update_Call) Run(run func(ctx context.Context, r *role.Role)) *Repository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*role.Role))
	})
	return _c
}

func (_c *Repository_Update_Call) Return(_a0 error) *Repository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Update_Call) RunAndReturn(run func(context.Context, *role.Role) error) *Repository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
