apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: agentgateway-secrets
  labels:
    app.kubernetes.io/instance: agentgateway
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: projects/neuraltrust-prod-us/secrets/agentgateway/versions/latest
        path: .env
