// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	url "net/url"

	sts "github.com/NeuralTrust/TrustGate/pkg/app/identity/sts"
	mock "github.com/stretchr/testify/mock"
)

// IdPTokenClient is an autogenerated mock type for the IdPTokenClient type
type IdPTokenClient struct {
	mock.Mock
}

type IdPTokenClient_Expecter struct {
	mock *mock.Mock
}

func (_m *IdPTokenClient) EXPECT() *IdPTokenClient_Expecter {
	return &IdPTokenClient_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: ctx, issuer, form
func (_m *IdPTokenClient) Call(ctx context.Context, issuer string, form url.Values) (*sts.Token, error) {
	ret := _m.Called(ctx, issuer, form)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *sts.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, url.Values) (*sts.Token, error)); ok {
		return rf(ctx, issuer, form)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, url.Values) *sts.Token); ok {
		r0 = rf(ctx, issuer, form)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sts.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, url.Values) error); ok {
		r1 = rf(ctx, issuer, form)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IdPTokenClient_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type IdPTokenClient_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - issuer string
//   - form url.Values
func (_e *IdPTokenClient_Expecter) Call(ctx interface{}, issuer interface{}, form interface{}) *IdPTokenClient_Call_Call {
	return &IdPTokenClient_Call_Call{Call: _e.mock.On("Call", ctx, issuer, form)}
}

func (_c *IdPTokenClient_Call_Call) Run(run func(ctx context.Context, issuer string, form url.Values)) *IdPTokenClient_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(url.Values))
	})
	return _c
}

func (_c *IdPTokenClient_Call_Call) Return(_a0 *sts.Token, _a1 error) *IdPTokenClient_Call_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IdPTokenClient_Call_Call) RunAndReturn(run func(context.Context, string, url.Values) (*sts.Token, error)) *IdPTokenClient_Call_Call {
	_c.Call.Return(run)
	return _c
}

// NewIdPTokenClient creates a new instance of IdPTokenClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdPTokenClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdPTokenClient {
	mock := &IdPTokenClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
