// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	sts "github.com/NeuralTrust/TrustGate/pkg/app/identity/sts"
	identity "github.com/NeuralTrust/TrustGate/pkg/domain/identity"
	ids "github.com/NeuralTrust/TrustGate/pkg/domain/ids"
	registry "github.com/NeuralTrust/TrustGate/pkg/domain/registry"
	mock "github.com/stretchr/testify/mock"
)

// Exchanger is an autogenerated mock type for the Exchanger type
type Exchanger struct {
	mock.Mock
}

type Exchanger_Expecter struct {
	mock *mock.Mock
}

func (_m *Exchanger) EXPECT() *Exchanger_Expecter {
	return &Exchanger_Expecter{mock: &_m.Mock}
}

// Exchange provides a mock function with given fields: ctx, principal, gatewayID, cfg, cacheKey
func (_m *Exchanger) Exchange(ctx context.Context, principal *identity.Principal, gatewayID ids.GatewayID, cfg *registry.MCPAuth, cacheKey string) (*sts.Token, error) {
	ret := _m.Called(ctx, principal, gatewayID, cfg, cacheKey)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 *sts.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *identity.Principal, ids.GatewayID, *registry.MCPAuth, string) (*sts.Token, error)); ok {
		return rf(ctx, principal, gatewayID, cfg, cacheKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *identity.Principal, ids.GatewayID, *registry.MCPAuth, string) *sts.Token); ok {
		r0 = rf(ctx, principal, gatewayID, cfg, cacheKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sts.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *identity.Principal, ids.GatewayID, *registry.MCPAuth, string) error); ok {
		r1 = rf(ctx, principal, gatewayID, cfg, cacheKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Exchanger_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type Exchanger_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - principal *identity.Principal
//   - gatewayID ids.GatewayID
//   - cfg *registry.MCPAuth
//   - cacheKey string
func (_e *Exchanger_Expecter) Exchange(ctx interface{}, principal interface{}, gatewayID interface{}, cfg interface{}, cacheKey interface{}) *Exchanger_Exchange_Call {
	return &Exchanger_Exchange_Call{Call: _e.mock.On("Exchange", ctx, principal, gatewayID, cfg, cacheKey)}
}

func (_c *Exchanger_Exchange_Call) Run(run func(ctx context.Context, principal *identity.Principal, gatewayID ids.GatewayID, cfg *registry.MCPAuth, cacheKey string)) *Exchanger_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*identity.Principal), args[2].(ids.GatewayID), args[3].(*registry.MCPAuth), args[4].(string))
	})
	return _c
}

func (_c *Exchanger_Exchange_Call) Return(_a0 *sts.Token, _a1 error) *Exchanger_Exchange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Exchanger_Exchange_Call) RunAndReturn(run func(context.Context, *identity.Principal, ids.GatewayID, *registry.MCPAuth, string) (*sts.Token, error)) *Exchanger_Exchange_Call {
	_c.Call.Return(run)
	return _c
}

// NewExchanger creates a new instance of Exchanger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExchanger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Exchanger {
	mock := &Exchanger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
