// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	jwt "github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TokenSigner is an autogenerated mock type for the TokenSigner type
type TokenSigner struct {
	mock.Mock
}

type TokenSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenSigner) EXPECT() *TokenSigner_Expecter {
	return &TokenSigner_Expecter{mock: &_m.Mock}
}

// Issuer provides a mock function with no fields
func (_m *TokenSigner) Issuer() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Issuer")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// TokenSigner_Issuer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issuer'
type TokenSigner_Issuer_Call struct {
	*mock.Call
}

// Issuer is a helper method to define mock.On call
func (_e *TokenSigner_Expecter) Issuer() *TokenSigner_Issuer_Call {
	return &TokenSigner_Issuer_Call{Call: _e.mock.On("Issuer")}
}

func (_c *TokenSigner_Issuer_Call) Run(run func()) *TokenSigner_Issuer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TokenSigner_Issuer_Call) Return(_a0 string) *TokenSigner_Issuer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TokenSigner_Issuer_Call) RunAndReturn(run func() string) *TokenSigner_Issuer_Call {
	_c.Call.Return(run)
	return _c
}

// JWKS provides a mock function with no fields
func (_m *TokenSigner) JWKS() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for JWKS")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// TokenSigner_JWKS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JWKS'
type TokenSigner_JWKS_Call struct {
	*mock.Call
}

// JWKS is a helper method to define mock.On call
func (_e *TokenSigner_Expecter) JWKS() *TokenSigner_JWKS_Call {
	return &TokenSigner_JWKS_Call{Call: _e.mock.On("JWKS")}
}

func (_c *TokenSigner_JWKS_Call) Run(run func()) *TokenSigner_JWKS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TokenSigner_JWKS_Call) Return(_a0 map[string]interface{}) *TokenSigner_JWKS_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TokenSigner_JWKS_Call) RunAndReturn(run func() map[string]interface{}) *TokenSigner_JWKS_Call {
	_c.Call.Return(run)
	return _c
}

// MintClaims provides a mock function with given fields: claims, ttl
func (_m *TokenSigner) MintClaims(claims jwt.MapClaims, ttl time.Duration) (string, error) {
	ret := _m.Called(claims, ttl)

	if len(ret) == 0 {
		panic("no return value specified for MintClaims")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(jwt.MapClaims, time.Duration) (string, error)); ok {
		return rf(claims, ttl)
	}
	if rf, ok := ret.Get(0).(func(jwt.MapClaims, time.Duration) string); ok {
		r0 = rf(claims, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(jwt.MapClaims, time.Duration) error); ok {
		r1 = rf(claims, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenSigner_MintClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MintClaims'
type TokenSigner_MintClaims_Call struct {
	*mock.Call
}

// MintClaims is a helper method to define mock.On call
//   - claims jwt.MapClaims
//   - ttl time.Duration
func (_e *TokenSigner_Expecter) MintClaims(claims interface{}, ttl interface{}) *TokenSigner_MintClaims_Call {
	return &TokenSigner_MintClaims_Call{Call: _e.mock.On("MintClaims", claims, ttl)}
}

func (_c *TokenSigner_MintClaims_Call) Run(run func(claims jwt.MapClaims, ttl time.Duration)) *TokenSigner_MintClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(jwt.MapClaims), args[1].(time.Duration))
	})
	return _c
}

func (_c *TokenSigner_MintClaims_Call) Return(_a0 string, _a1 error) *TokenSigner_MintClaims_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenSigner_MintClaims_Call) RunAndReturn(run func(jwt.MapClaims, time.Duration) (string, error)) *TokenSigner_MintClaims_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenSigner creates a new instance of TokenSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenSigner {
	mock := &TokenSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
