apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: agentgateway
resources:
- ../../base
- secretproviderclass/agentgateway-secrets.yaml
# - patches/hpa-patch.yaml
patchesStrategicMerge:
- patches/replicas-patch.yaml
- patches/resources-patch.yaml
- patches/pdb-patch.yaml
- patches/httproute-patch.yaml
- patches/sa-annotation-patch.yaml
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  environment: dev
namespace: agentgateway
images:
- name: agentgateway
  newName: europe-west1-docker.pkg.dev/neuraltrust-app-dev/nt-docker/agentgateway
  newTag: 2a39ec313f284f9c3ec173d8d544ceda911d24fd
configMapGenerator:
- behavior: create
  envs:
  - config.env
  name: agentgateway-config
