apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: agentgateway
# config-sync gRPC public endpoint (hybrid data planes) + its cert-manager cert
resources:
- ../../base
- secretproviderclass/agentgateway-secrets.yaml
- service-configsync-external.yaml
- config-sync-cert.yaml
patchesStrategicMerge:
- patches/hpa-patch.yaml
- patches/resources-patch.yaml
- patches/pdb-patch.yaml
- patches/httproute-patch.yaml
- patches/sa-annotation-patch.yaml
- patches/config-sync-tls-patch.yaml
- patches/config-sync-internal-lb-patch.yaml
patches:
- patch: |-
    - op: remove
      path: /spec/replicas
  target:
    kind: Deployment
    name: agentgateway-admin
- patch: |-
    - op: remove
      path: /spec/replicas
  target:
    kind: Deployment
    name: agentgateway-proxy
- patch: |-
    - op: remove
      path: /spec/replicas
  target:
    kind: Deployment
    name: agentgateway-mcp
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  environment: dev
namespace: agentgateway
images:
- name: agentgateway
  newName: europe-west1-docker.pkg.dev/neuraltrust-app-dev/nt-docker/agentgateway
  newTag: 59b95f5c030a268eba2bf2c386322e077ca3d21c
configMapGenerator:
- behavior: create
  envs:
  - config.env
  name: agentgateway-config
- behavior: create
  files:
  - telemetry.yaml
  name: agentgateway-telemetry
